### ISSUE TITLE
Install in Ubuntu VESTA CP

### ISSUE THREAD

**Issue by vokuev** [themosis/themosis#102]
Hi! 

I have installed Themosis in /web/domen.com/

htdocs -> rename - public_html

Does it work ?

Home page is worked but when added in routes.php

Route::get('sample-page', function()
{
    return 'Hello!';
});

Unhandled Exception
Message:

The route condition [sample-page] was not found.

Location:

/home/admin/web/domen.com/public_html/content/mu-plugins/themosis-framework/src/Themosis/Route/Route.php on line 153

Stack Trace:

#0 /home/admin/web/domen.com/public_html/content/mu-plugins/themosis-framework/src/Themosis/Route/Route.php(75): Themosis\Route\Route->parseCondition('sample-page')
#1 /home/admin/web/domen.com/public_html/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(143): Themosis\Route\Route->__construct(Array, 'sample-page', Object(Closure))
#2 /home/admin/web/domen.com/public_html/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(123): Themosis\Route\Router->createRoute(Array, 'sample-page', Object(Closure))
#3 /home/admin/web/domen.com/public_html/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(66): Themosis\Route\Router->addRoute(Array, 'sample-page', Object(Closure))
#4 [internal function]: Themosis\Route\Router->get('sample-page', Object(Closure))
#5 /home/admin/web/domen.com/public_html/content/mu-plugins/themosis-framework/src/Themosis/Facades/Facade.php(107): call_user_func_array(Array, Array)
#6 /home/admin/web/domen.com/public_html/content/themes/themosis-theme/resources/routes.php(19): Themosis\Facades\Facade::__callStatic('get', Array)
#7 /home/admin/web/domen.com/public_html/content/themes/themosis-theme/resources/routes.php(19): Themosis\Facades\Route::get('sample-page', Object(Closure))
#8 /home/admin/web/domen.com/public_html/content/themes/themosis-theme/bootstrap/start.php(219): require('/home/admin/web...')
#9 /home/admin/web/domen.com/public_html/content/themes/themosis-theme/index.php(9): themosis_start_app()
#10 /home/admin/web/domen.com/public_html/cms/wp-includes/template-loader.php(75): include('/home/admin/web...')
#11 /home/admin/web/domen.com/public_html/cms/wp-blog-header.php(19): require_once('/home/admin/web...')
#12 /home/admin/web/domen.com/public_html/index.php(11): require('/home/admin/web...')
#13 {main}

**Comment by jlambe** [comment]
The framework do not handle yet custom routes. If you're looking after the page with the URI `sample-page`, you need to write this code:
```php
Route::get('page', ['sample-page', function () {
    return 'Sample';
}]);
```

Custom routes are coming in the next release (1.3.0). Please read the routing docs: http://framework.themosis.com/docs/routing/

**Comment by vokuev** [comment]
Thank you!

There is one more problem : 

When I come to http://domen.com/cms/wp-admin -> Redirect  to http://domen.com/

/web/domen.com/public_html/.htaccess

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

This htaccess is correct ?

**Comment by vokuev** [comment]
http://domen.com/cms/wp-login.php is work!

https://github.com/themosis/themosis/issues/38

Thank you!

**Comment by jlambe** [comment]
In fact, the default theme do not let people access `wp-admin` if there are not logged in.

**Comment by jlambe** [comment]
The default `.htaccess` of WordPress is the good one.
