### ISSUE TITLE
Overwrite Template of Plug-In

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/themosis#105]
Hello,

how can I overwrite a plugin template with themosis framework ? 

Can u help me ? 
Thanks.

**Comment by jlambe** [comment]
Hello,

what kind of templates? Custom post type? Taxonomy ? ...

**Comment by heikobihlmaier** [comment]
All of them :) Especially currently i need to overwrite an output template.

**Comment by jlambe** [comment]
You need to find the plugin custom post type slug and then write the route in your theme and you should be good to go. Depending on what you need to overwrite: archive, singular, ... you add the routes you need in the `routes.php` file and return a custom view.

**Comment by heikobihlmaier** [comment]
And how can I overwrite for example a shortcode layout ? in the normal wordpress I copy the file to my theme folder.

**Comment by jlambe** [comment]
I suppose the original shortcode has its template hard coded in it with a check to the theme. You should check the shortcode code for this.
