### ISSUE TITLE
Add new Features to Create / Edit Posts

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/themosis#107]
Hello and Good Morning,

I have a little question: I want to extend the create / edit post function within the backend of wordpress.

Below the text editor I want to add new functions in a panel view (like YOAST Seo: https://ps.w.org/wordpress-seo/assets/screenshot-1.png?rev=1266422).

How can I do this in your wonderful framework ?

Greetings from Germany to Belgium.

Heiko
<img width="968" alt="screenshot-1" src="https://cloud.githubusercontent.com/assets/10707232/17882543/49993ee4-690d-11e6-82af-97b69e98d897.png">

**Comment by jlambe** [comment]
You'll need to use the Metabox class and pass it a custom view in order to build your tabs. Finally in order to load the JS file necessary to make it work, I'll define a view composer where you call the Asset class so the JS file is only loaded when the metabox view is required.

Regarding the layout of the metabox, you'll have to work it out yourself in the custom view. And if you want to use the core custom fields, checkout the `_themosisCoreMetabox.scout.php` view file inside the framework to give a hint on how to set the html table to display the fields correctly: https://github.com/themosis/framework/blob/master/src/Themosis/Metabox/Views/_themosisCoreMetabox.scout.php

Check the bottom of the metabox documentation for details: http://framework.themosis.com/docs/metabox/

**Comment by heikobihlmaier** [comment]
And where I need this to build in?

I try it in the admin folder but when i need to check get_post_type('post') it's not working because I get always false.

**Comment by jlambe** [comment]
Yes inside the admin folder. The custom view of your metabox automatically receive the current post object within the variable `$__post`, so you can get the current post type from there. The get_post_type() is called too early if you receive false as a returned value, I suggest you to use a hook to call it later like on the custom post type edit page is requested: https://codex.wordpress.org/Plugin_API/Action_Reference/load-(page)

**Comment by heikobihlmaier** [comment]
Okay thanks. Can I add fields before the text editor from wordpress ?

**Comment by jlambe** [comment]
No you can't, there are no hooks to display metabox before the main editor. The only solution would be to remove it (do not support it) and build another metabox with the editor field to place below.

**Comment by heikobihlmaier** [comment]
Thanks. How Can i build a custom view ? For example first I want checkbox "Feature" after that field image and after that field color ?

**Comment by jlambe** [comment]
Read the section "Customize the metabox" in the documentation, you'll have an example to write your own custom views for a metabox: http://framework.themosis.com/docs/metabox/

**Comment by heikobihlmaier** [comment]
Okay thanks. I have the following code for the metabox view composer: 
`
View::composer('metabox.featured', function()
{
	Asset::add('colorpickerlib', 'js/libs/jquery.simplecolorpicker.js', false, '1.0.0', true)->to('admin');
	Asset::add('colorpickercss', 'css/jquery.simplecolorpicker.css', false, '1.0', 'all')->to('admin');
	Asset::add('colorpickercsstheme', 'css/jquery.simplecolorpicker-regularfont.css', false, '1.0', 'all')->to('admin');
});`

When I load my page new the assets are not available. can u help me why ?

**Comment by jlambe** [comment]
Can you post your full code for your custom metabox? Is this called before your metabox?

**Comment by heikobihlmaier** [comment]
Better solution: it is possible to set the available colors for the wpColorPicker ?

**Comment by heikobihlmaier** [comment]
This is the code who doesn't load my assets:

`<?php
if ( get_post_type(themosis_get_post_id()) == 'post' )
{
	$view = View::make('metabox.featured');

	Metabox::make('Top-Beitrag', 'post', [], $view)->set([
		Field::checkbox('featured', 'Beitrag ist Top-Beitrag'),
		Field::media('featured_image', [
			'title'     => 'Bild',
			'type'      => 'image'
		]),
		Field::select('featured_color', [
			[
				'#7bd148',
				'#5484ed'
			]
		], ['title' => 'Farbe wählen:'])
	]);
}

View::composer('metabox.featured', function()
{
	Asset::add('colorpickerlib', 'js/libs/jquery.simplecolorpicker.js', false, '1.0.0', true)->to('admin');
	Asset::add('colorpickercss', 'css/jquery.simplecolorpicker.css', false, '1.0', 'all')->to('admin');
	Asset::add('colorpickercsstheme', 'css/jquery.simplecolorpicker-regularfont.css', false, '1.0', 'all')->to('admin');
});
`

**Comment by jlambe** [comment]
Your first if statement is un-necessary, the metabox is only attached to post object and will only be displayed in post edit screens.

The framework has a `Field::color` available normally so your select field is not the best option. This removes the need for your view composer call which I suggest to put before creating your view.

**Comment by heikobihlmaier** [comment]
Field::color is not good for me, because the user can only select 8 colors.

**Comment by heikobihlmaier** [comment]
And my ViewComposer isnt' loaded correctly
