### ISSUE TITLE
Customize Wordpress Comment Form

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/themosis#110]
Hello,

normally I can customize the wordpress comment form with the function comment_form(). There I can set the default fields to another value with css classes and so on.

Have Themosis here a better way then that ?

Greetings.

**Comment by jlambe** [comment]
Nope, I actually use WordPress core functions for this.
But comment_form() returns a string with html form, you can still use a view, render it and return it.

**Comment by heikobihlmaier** [comment]
Okay, and I the normal wp-comments-post.php as form target ?

**Comment by jlambe** [comment]
Sure otherwise it won't work. Perhaps check the function source code in order to use one of its hook or filter to alter your comment form.

**Comment by heikobihlmaier** [comment]
Okay thanks. Currently I don't now, how I get for example the author in my single page.

I have a route like so

```
Route::get('single', [function($post)
{
    return View::make('pages.single_post', [
        'post' => $post
    ]);
}]);
```

In my view I can make `$post->content` for example. But the methods of wordpress like get_the_author() only work within a loop or so.

Can u help ?

**Comment by jlambe** [comment]
Add the statements `@loop` and `@endloop` around your view html.

**Comment by heikobihlmaier** [comment]
Okay thanks. Is that in the doc missing ?

**Comment by jlambe** [comment]
Not at all, it's in the Scout templates documentation: http://framework.themosis.com/docs/scout/
