### ISSUE TITLE
Htaccess fix to access /cms trough a route

### ISSUE THREAD

**Issue by dstollie** [themosis/themosis#111]
In our starter theme we have a route /cms but if the users hits this path the user is getting directed to the "cms" folder. With the following rule you let /cms also redirect to index.php cms/wp-login.php and cms/wp-admin are still working with this solution

``` xml
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^cms/$ /index.php [L]
</IfModule>
```

**Comment by jlambe** [comment]
This can be added in the documentation as a reference for those willing to use the `cms` slug for their project.

**Comment by DannyvanHolten** [comment]
On my local server this solution works fine. If I put it on production (Secure http) it still breaks. Haven't found a solution yet.
