### ISSUE TITLE
get_current_screen() for admin pages

### ISSUE THREAD

**Issue by bgatellier** [themosis/themosis#112]
Hi,

I'm currently trying to add custom fields for a user according to his role.
Currently, there are two different user roles, plus the super administrator.
I would like to know how I can display the correct group of custom fields according to the edited user in the _Wordpress_ administration.

I saw the codex about the _get_current_screen()_, but this function is not available in my code (which is located in the _/admin_ directory).

So I was wondering if there are any routing information available in the administration (I saw that _Themosis_ comes with an enhanced version of the Symfony _Request_ class; Am I missing something here?).

**Comment by jlambe** [comment]
The `get_current_screen()` is only available after the hook `current_screen` is called. Try to wrap your into it.

The request instance is not directly available inside the WordPress admin but you might create a new instance if needed.

**Comment by bgatellier** [comment]
Thx for the help, I will try these solutions.

**Comment by bgatellier** [comment]
The `current_screen` hook with the `WP_Screen` object was enough for my use case.

Thx again !
