### ISSUE TITLE
admin route

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [themosis/themosis#113]
hi,

i created a page for admin section : 
```php
// functions.php
Page::make('page-slug', 'Page title')->set();
```
the problem is that my route is not working : 
```php
// route.php
Route::get( 'front', function() {

	return 'hi admin page';
});
```
why? :(

**Comment by jlambe** [comment]
Routes are not working on the WordPress admin side. It is only for the front-end. Using the `Page` class is for building WordPress admin pages that are accessible through a query parameter. Normally your page should show in the admin left column with the title "Page title".

The route `front` is only for requests made on the front when a WordPress page is defined as the home/front page. Check this codex for more information regarding the front page: https://codex.wordpress.org/Creating_a_Static_Front_Page

**Comment by Saeed-Pooyanfar** [comment]
thanks for reply
i want create a table with some columns in db and manage it from wordpress admin ( insert, delete, update )
how can i do it ?

**Comment by jlambe** [comment]
With WordPress you have 2 options, write your own MySQL queries or use the `$wpdb` instance to run your queries. You still need to write RAW queries but it provides helper methods.
The next version of the framework will bootstrap the Illuminate Database package so it will be easier to create tables and custom mysql queries but now on, it's not possible, at least not rapidly.

**Comment by Saeed-Pooyanfar** [comment]
can i set a controller for a admin page?

**Comment by Saeed-Pooyanfar** [comment]
in another word how can i pass parameters to a admin page ?

**Comment by Saeed-Pooyanfar** [comment]
for example, pass my query result to admin page ...

**Comment by jlambe** [comment]
You can't set a controller as usual but there is a WordPress hook called on each admin page using the page slug where you could set some bootstrap code before rendering your view and then pass the data thanks to a View composer.

Here is the hook: `settings_page_.$pageslug`, with this hook you can assign a class method and manage your code in a "controller" class.
