### ISSUE TITLE
Load views from custom path

### ISSUE THREAD

**Issue by moise** [themosis/themosis#116]
Hello @jlambe it is possibile to load views from a custom path instead of resources/views?
In my case it would be perfect to load views from a custom mu-plugin folder.

thank you in advance.

**Comment by jlambe** [comment]
Yes it is possible, in version 1.2.3, there is a filter:

```php
add_filter('themosisViewPaths', function($paths)
{
    $paths[] = themosis_path('theme').'views'.DS;
    return $paths;
});
```

Add your custom directory full path to the array and return the array. Note that this code won't work on next version as there is now a better/shorter method to do it.
