### ISSUE TITLE
Get the page template slug in my singlePage

### ISSUE THREAD

**Issue by Neidra** [themosis/themosis#120]
Hey,

I'm trying to create a SinglePage Website for my client.
For helping my client to manage correctly the website i decide to create a top template singlePage.scout.php. This template manage the page included from the menu by a loop. 

So i'm really confused but I can't access to the specific page_template_slug (template set in the dashboard) of each pages (using the page_id). 

Did you know how can I access to this information?

Regards,

Neidra

**Comment by jlambe** [comment]
Adding multiple pages will create URIs using each page name. For example, a page with a title of "About" is accessible at the following URI `http://domain.com/about/` whether a page template is assigned or not.

To listen to these pages (which are assigned a page template), use the `Route::get('template', ['template-name', function () {}]);`. But those pages are accessible through their own URIs and simply render the same view.

If you want to build a single page website, perhaps another solution is to create a custom post type which is not queryable in the front-end.
