### ISSUE TITLE
Where I can find wp-blog-header.php?

### ISSUE THREAD

**Issue by faidz-ubpon** [themosis/themosis#122]
I got an error during installation.

Warning: require(D:\xampp\htdocs\themosis\htdocs\cms\wp-blog-header.php): failed to open stream: No such file or directory in D:\xampp\htdocs\themosis\htdocs\index.php on line 11

No file in that directory, wp-blog-header.php, what should I do?

**Comment by jlambe** [comment]
Don't you have a `cms` folder installed inside the `htdocs` directory? WordPress should be installed there. Try to run a `composer install` at your project root. Also, based on your path above, you can't put the project into your server public `htdocs` folder. You need to create a virtual host that points to the Themosis project own `htdocs` folder.

**Comment by faidz-ubpon** [comment]
There is a `cms` folder in my directory but I can't find wp-blog-header.php. I already run the `composer install` in my root directory but nothing changes. I've set also the virtual host to point to the `htdocs` of themosis.

**Comment by faidz-ubpon** [comment]
Btw, during `composer install`, I got also this message `Your configuration does not allow connections to http://wpackagist.org/packages.json.`

**Comment by jlambe** [comment]
Update the composer.json file and look after the line regarding `wpackagist` URL. Update the URL to use `https`. Save the file and run composer install again. This installation should grab the latest WordPress version and install it into the `cms` folder. Your error appears because the installation failed somehow with composer.

**Comment by faidz-ubpon** [comment]
Thanks, problem solved!

**Comment by jlambe** [comment]
Great! Just for your information, a new major release is coming in less than a month. Depending on your project needs for production, you can train with current version and then start your project with next release.

**Comment by faidz-ubpon** [comment]
Okay, I'll wait that release and I hope it will automatically solve the `wpackagist` problem :-).

**Comment by jlambe** [comment]
Yes it is solved ;)
