### ISSUE TITLE
How can I use Themosis on web hosting?

### ISSUE THREAD

**Issue by EchPay** [themosis/themosis#124]
I am going to use Themosis in my next project, but I don't know how to set it up on web hosting.
I read the document and deployed success on my local. But on the hosting, I cannot create a symlink for `public` folder and set up environment.

Please help me to set up Themosis on web hosting.
Thank you.

**Comment by jlambe** [comment]
Well, the best solution is to replace the default `htdocs` folder to `public` in your project.
1- rename the `htdocs` folder to `public`
2-update `$webroot_path` variable inside the `bootstrap/start.php` file to point to `public`
3-update the default `composer.json` paths. Replace all mentions of `htdocs` to `public`
4-(optional) If you use wp-cli, update the wp-cli.yml path to use the `public` folder
5-Run a `composer update`

Now your project use the `public` directory for its web root which is the same as your web hosting one. Simply deploy your project by keeping the same file structure and you should be good to go.

**Comment by EchPay** [comment]
Sorry I had a mistake. I don't want to rename the folder `htdocs` to `public`. I have a web hosting a domain linked to that hosting.

So I copy the source code in my local and tranfer to my hosting. But I cannot access to the site. So my questions are:
- How can I access to my site with URL `mydomain.com` instead of `mydomain.com/htdocs`?
- How can I set up production enviroment on that hosting?

**Comment by jlambe** [comment]
1. You can't. I mean your hosting public folder should be your project `htdocs` directory. Meaning that when you access your `mydomain.com` URL, your webserver (Apache or Nginx) is pointing to the `/var/www/mydomain/htdocs` folder on your server. If you can't have access to the parent folder of your public directory for your hosting, I suggest you to change of provider.
2. Like explained in the docs, you have to know your production server hostname. If you can't find it, another solution is to define a Closure (anonymous function) in your `config/environment.php` file that always return the `production` string (so it chooses the `env.production.php` file). Inside your function, you can check against your local hostname to return your local configuration and if it fails, return production one.

You can find examples in the environment documentation: http://framework.themosis.com/docs/environment/
