### ISSUE TITLE
Object of class Closure could not be converted to string -> WP 4.6.1 

### ISSUE THREAD

**Issue by mundgold** [themosis/themosis#125]
I've made an upgrade to WP 4.6.1 and use themosis 1.2.3 - now I get an error at routing -> is_single (Object of class Closure could not be converted to string)

htdocs/cms/wp-includes/query.php on line 4658

I var_dump it - and yes it's an Closure ...

the line after: 		$post = array_map( 'strval', (array) $post ); throws the Exeption

Unhandled Exception
Message:
Object of class Closure could not be converted to string
Location:
htdocs/cms/wp-includes/query.php on line 4658
Stack Trace:
#0 ../htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(4096, 'Object of class...', '/Users/roland/d...', 4658)
#1 [internal function]: THFWK_Themosis->{closure}(4096, 'Object of class...', '...', 4658, Array)
#2 [internal function]: strval(Object(Closure))

4655: var_dump( (array) $post);die();
`htdocs/cms/wp-includes/query.php:4655:
array (size=1)
  0 => 
    object(Closure)[2421]
      public 'static' => 
        array (size=2)
          'd' => 
            object(Themosis\Route\ControllerDispatcher)[2412]
              protected 'filterer' => 
                object(Themosis\Route\Router)[2408]
                  protected 'container' => 
                    object(Themosis\Core\Application)[1773]
                      ...
                  protected 'routes' => 
                    object(Themosis\Route\RouteCollection)[2410]
                      ...
                  protected 'current' => null
                  protected 'currentRequest' => 
                    object(Themosis\Core\Request)[1774]
                      ...
                  protected 'controllerDispatcher' => 
                    &object(Themosis\Route\ControllerDispatcher)[2412]
              protected 'container' => 
                object(Themosis\Core\Application)[1773]
                  protected 'serviceIgniters' => 
                    array (size=17)
                      ...
                  protected 'loadedIgniters' => 
                    array (size=16)
                      ...
                  protected 'deferredServices' => 
                    array (size=0)
                      ...
                  protected 'resolved' => 
                    array (size=15)
                      ...
                  protected 'bindings' => 
                    array (size=22)
                      ...
                  protected 'instances' => 
                    array (size=16)
                      ...
                  protected 'aliases' => 
                    array (size=22)
                      ...
                  protected 'reboundCallbacks' => 
                    array (size=0)
                      ...
                  protected 'resolvingCallbacks' => 
                    array (size=0)
                      ...
                  protected 'globalResolvingCallbacks' => 
                    array (size=0)
                      ...
          'controller' => string 'PostsController@single' (length=22)
      public 'this' => 
        object(Themosis\Route\Router)[2408]
          protected 'container' => 
            object(Themosis\Core\Application)[1773]
              protected 'serviceIgniters' => 
                array (size=17)
                  0 => 
                    object(Themosis\Route\RouteIgnite`

could you give me a hint what to do?

Thanks a lot
Roland

**Comment by jlambe** [comment]
Not sure as I've not tested your line of code but it seems there is an issue to the conversion of the `$post` variable as an array. What is the default type of `$post`?

**Comment by mundgold** [comment]
I have set up a new instance and drop in my theme - var_dump the post I get an empty string '' ... very strange ...

Thanks for your reply
Roland

**Comment by jlambe** [comment]
I'm glad it's working now but what are you trying to achieve? Is your method a controller's method? listening to requests made to a single post URI ?
Normally, if there is a hit, the `$post` variable should be a `WP_Post` instance. But I suppose you're trying to get the `WP_Query` instance which is the second argument on the controller's method.

**Comment by mundgold** [comment]
No it's not - and therefore should no $post value passed to method "is_single" - I have nothing changed in my theme-directory.

the only routes worked without exception where "search and 404"

that's my routes-file :

Route::any('404',function($post, $query){
    $searchpath = home_url().'/'.$query->query_vars['name'];
    return View::make('pages.404',['searchpath' => $searchpath]);
});

Route::any('page', ['buchinfo', 'uses' => 'PagesController@buchinfo']);



Route::any('home', 'PagesController@home');

Route::any('front', function ($post, $query)
{
    return View::make('pages.index');
});

// single Page
Route::any('page', function ($post, $query)
{
    return View::make('pages.page');
});

// single Post
Route::any('single', 'PostsController@single');

Route::any('category', ['Uncategorized', function($post, $query){
    wp_redirect(home_url());
}]);

Route::any('archive', function ($post, $query)
{
    return View::make('posts.archive', ['post' => $post, 'query' => $query]);
});

Route::any('search', function ($post, $query)
{
    return View::make('posts.search', ['post' => $post, 'query' => $query]);
});


Route::any('template', ['newsletter', function ($post, $query)
{
    return View::make('pages.newsletter');
}]);
Route::any('template', ['gewinnspiel', function ($post, $query)
{
    return View::make('pages.gewinnspiel');
}]);
Route::any('template', ['hotness-barometer', function ($post, $query)
{
    return View::make('pages.hotness-barometer');
}]);

**Comment by jlambe** [comment]
As a piece of advice, routes are listened from top to bottom. As a best practice, put routes by object type (posts, pages, cpt, ...) then from single to archive and finally search and 404.

**Comment by mundgold** [comment]
Thanks for advice - will change that.
Roland

**Comment by pckosmonaft** [comment]
@mundgold Did you solve your issue?
I do have similar one but related with $page.
