### ISSUE TITLE
Select Field errors

### ISSUE THREAD

**Issue by KevinBatdorf** [themosis/themosis#126]
It seems that the select field breaks when the array has duplicate values in separate sub groups.
I had to change the `organizeOptions` function to the following, although it might not be ideal for other use cases. Still, I imagine this is a typical use case so I'm reporting my fix here.

```
// Grab the converted values and return them.
foreach ($indexedOptions as $index => $option)
{
    if (array_key_exists($index, $subOptions))
    {
        $convertedOptions[$index] = $option;
    }
}
```

And for reference, my array is:
```
Array
(
    [0] => Array
        (
            [0] => Select a specialty
        )

    [Portland] => Array
        (
            [dept-170] => Audiology
            [dept-177] => Ear, Nose and Throat
            [dept-178] => Infectious Disease
            [dept-179] => Internal Medicine
            [dept-180] => Pediatrics
            [dept-181] => Surgery Center
            [dept-182] => Travel Medicine
            [dept-183] => Obstetrics and Gynecology
        )

    [South Portland] => Array
        (
            [dept-185] => Cardiology
            [dept-186] => Family Medicine
            [dept-187] => Imaging/Radiology
            [dept-188] => Laboratory
            [dept-189] => Pediatrics
            [dept-190] => Physical Therapy
            [dept-191] => Sports Medicine
            [dept-192] => Urgent Care
        )

    [Yarmouth] => Array
        (
            [dept-193] => Family Medicine
            [dept-195] => Pediatrics
            [dept-196] => Physical Therapy
        )

    [Other Locations] => Array
        (
            [dept-197] => Administration and Billing
            [dept-198] => Healthcare at Work
        )
)
```
Which would produce by default:
![screen shot 2016-11-26 at 11 10 42 pm](https://cloud.githubusercontent.com/assets/1478421/20641583/a34a5f8e-b42d-11e6-9286-1719668407be.png)

Also, I had to force the keys to strings (the post ID) to keep them from being reindexed. I noticed your comment to keep it from causing duplicates (the irony :) ).

Btw, thanks for everything!

**Comment by jlambe** [comment]
Hi, thanks for this report.
On current master branch, I've fixed the ID (integer) re-indexed issue normally.
I will take a look regarding duplicate array values as these should not interfere. Only the keys are used to fill the html `<option value="key">` tag so perhaps it's a used case I haven't taken into account.

**Comment by jlambe** [comment]
@KevinBatdorf Latest commit of themosis/framework fix this issue. Works with numeric or string keys ;)

**Comment by PierreLecigne** [comment]
Hello @jlambe ,

We still have an issue with numeric values in sub-select fields in the 1.3.1 version.
If a numeric key is smaller than the previous key, this key and all the following keys will not be displayed. Example : 

This code...
```php
$arr = [
            'studies' => [
                45 => 'My first study',
                46 => 'My second study',
                47 => 'My third study'
            ],
            'learnings' => [
                57 => 'My first learning',
                58 => 'My second learning'
            ]
        ];
```

... Render : 
<img width="209" alt="capture d ecran 2017-03-14 a 15 41 56" src="https://cloud.githubusercontent.com/assets/2725599/23905967/f97b6986-08cc-11e7-8ff7-b358cba788f0.png">

And this code...
```php
$arr = [
            'studies' => [
                82 => 'My first study',
                83 => 'My second study',
                56 => 'My third study'
            ],
            'learnings' => [
                57 => 'My first learning',
                58 => 'My second learning'
            ]
        ];
```

... Render : 
<img width="192" alt="capture d ecran 2017-03-14 a 15 42 23" src="https://cloud.githubusercontent.com/assets/2725599/23906005/0aef25d6-08cd-11e7-9865-648a36ff74d1.png">

Thanks !

**Comment by jlambe** [comment]
Thanks for finding this one @PierreLecigne. Could you open a new issue for this one so I can track it for a minor release?

**Comment by PierreLecigne** [comment]
Ok i opened the issue [#152](https://github.com/themosis/themosis/issues/152)

Thanks!
