### ISSUE TITLE
Preview buttons

### ISSUE THREAD

**Issue by red111** [themosis/themosis#127]
Dear friends,

Currently my route system manage preview of draft posts/pages as a not found route.

What is the correct route to intercept drafts/preview?

Thanks.

**Comment by jlambe** [comment]
Hi,
do you have any routes registered to view those posts or pages like:
```php
// SIngle post
Route::get('single', function () {
     return View::make('some.view');
});

// Single page
Route::get('page', function () {
    return View::make('some.page');
})
```
If there are no routes registered, then you'll get the message "Not Found Route", at least on current released version 1.2.3. The next version gracefully fallback to default WordPress templates and by default should return a blank page.

**Comment by red111** [comment]
Yes, we have a full routes defined...

`# define the route for home page
Route::get('home', 'PageController@index');

# define the route for pages
Route::get('page', 'PageController@index');

# define the route for posts
Route::get('single', 'PageController@singlePost');

# define the route for 404 not found page
Route::get('404', 'PageController@notFound');

# define the route for search results
Route::any('search', 'PageController@search');
`

And it works ok...

Our problem its only with Preview button when trying to see draft pages or post... if pages are published there is no problem...

I might be wrong, but I think its a routes problem because it falls into notfound route.

**Comment by jlambe** [comment]
Hmm strange. I haven't encountered an issue with preview before. What if you change the Route method to `any`, is there a difference ?
```php
Route::any('page', 'PageController@index');
```
Also, can you try to flush to rewrite rules ? The preview URL is using WordPress default permalink structure, there might be a need for a reset of the rules.

I've just tested on a fresh installation and preview work as expected on current released version 1.2.3 and master branch. Do you have any code that may alter the WordPress query?

**Comment by red111** [comment]
Our problem was with some wrong filters in WP not themosis...

thanks.

**Comment by jlambe** [comment]
👍  Glad it is solved.
