### ISSUE TITLE
Issue with custom route condition

### ISSUE THREAD

**Issue by Blair2004** [themosis/themosis#128]
Hi,
When i'm using custom route condition, any custom route matches the first Route definition.

Here is an example : 

admin/filters.php

```php
add_filter( 'themosisRouteConditions', function( $routes ) {
    $routes[ 'foo' ]        =   'is_foo';
    $routes[ 'bar' ]        =   'is_bar';
    return $routes;
});
```

admin/routing.php

```php
`function is_foo() {
    return true;
}


function is_bar(){
    return true;
}

```

Route.php

```php
`Route::get('home', function(){
    return View::make('welcome');
});

Route::get( 'bar', function(){
    return 'bar';
});

Route::get( 'foo', function(){
    return 'foo';
});

```

Any request which are'nt part of default WordPress route, trigger "bar" route. So if i try :

http://exemple.com/foo it ill run "bar" controller and "bar" text will be displayed
http://exemple.com/anything will run "bar" controller and "bar" text will also be displayed
http://exemple.com/bar obviously run "bar" and so on.

What's wrong ?

**Comment by jlambe** [comment]
That's because whatever custom condition you defined simply return true. And the first route you defined is the `bar` one. As the check only returns true, everything is attached to this route.

Inside your functions `is_foo` or `is_bar`, you need to add extra logic. Normally, you first need to define custom Rewrite Rules and Tags with the use of the WordPress Rewrite API and then write a condition function to match your custom rewrite rule and return true if there is a match, not just return true.

**Comment by Blair2004** [comment]
thank you. can you provide me an example ? I was close to give up but I'm
so in love with laravel and merging it to WordPress makes so much love.

also I'm thinking about something... how is the update managed ? can a
theme made with themosis be published on WordPress.org ? (due to the
concept, I have huge doubt about it, I also a theme reviewer, and building
something with themosis skips some important theme guidelines rules).

anyway it's awesome, I'll be looking how to contribute to the core.

**Comment by jlambe** [comment]
I could if you have something more concrete. Accessing something with an uri of `foo` or `bar` is like accessing WordPress pages.

So for that, you'll need to add a custom rewrite tag (query var) to default pages permalink structure. Then you function will check against this query var and if it's available, it's a "foo" route and not a classic page one.

Basically you'll use 2 functions: `add_rewrite_tag()` and `add_rewrite_rule()` into your project. Check the codex Rewrite API for those.

On a side note, the next version handle custom routing like Laravel, so you could just do something like this:
```php
Route::get('foo', function (){
    return "Anything from foo";
});
```
If you want to test this out, clone the `themosis/themosis` repository. There are no documentation yet but it's coming very soon.

**Comment by Blair2004** [comment]
d'accord je le ferai quand j'aurai le temps. merci encore pour votre
disponibilité. cependant qu'en est-il de l'exportabilite des projets ?

**Comment by jlambe** [comment]
Je ne comprends pas la question. Qu'entendez-vous par "exportabilité" ?

**Comment by Blair2004** [comment]
supposons que je souhaite commercialiser un produit  fait avec themosis...
comment le rendre distribuable ? ce que je voudrai savoir c'est si une
application fait avec themosis est aussi facile à partager qu'un plug-ins
ou thème WordPress et est ce que une personne peut utiliser cette
application dans une installation existante de WordPress ?
pour le moment, j'imagine assez difficilement de voir des utilisateurs de
WordPress qui ne sont pas forcément expert adapter leur installation pour
fonctionner avec une application themosis... je le dis parce que je voudrai
créer un point de vente woocommerce et je souhaite le commercialiser sur
code canyon,  donc à ce niveau... comment zipper le projet pour uploader
et comment feront-ils l'installation, ensuite si on doit apporter une mise
à jour à une app themosis (qui est en fait un theme) sa se passe comment ?

j'espère ne pas être incompréhensible  avec mes questions.

merci.

**Comment by jlambe** [comment]
A vous de choisir la commercialisation. Mais un thème ou plugin nécessitant le framework ne seront probablement pas admis sur les dépôts officiels de WordPress. Pour ce qui est de Code Canyon ou autre service, vous devriez les contacter directement.
La version actuelle du framework ne supporte que le développement pour un thème mais la prochaine supporte le développement de plugins également donc vous aurez le choix.
