### ISSUE TITLE
Invalid argument for custom taxonomy terms

### ISSUE THREAD

**Issue by APEWAW** [themosis/themosis#129]
Hello, 

I get the error "Invalid argument supplied for foreach()" when I use the fonction to get the custom taxonomy terms of current post : 

```
@loop
    <ul>
        @foreach(Loop::terms('custom-slug') as $term)
            <li>{{ $term->name }}</li>
        @endforeach
    </ul>
@endloop
```

Any idea? 

Thank you,

**Comment by jlambe** [comment]
Not sure why but what is the returned value of `Loop::terms('custom-slug')` ? You can simply make a var_dump or use any of the debug helper functions like `tp()` or `td()`.
Possibly the current post has no terms so you can't loop. Make sure to check there is an array returned before processing the foreach statement.

**Comment by APEWAW** [comment]
Thank you for your reply. In fact, it works well in a classic loop, but not in a loop with query arguments. Do I have to adjust something?

**Comment by jlambe** [comment]
I do not understand the difference between your classic loop and a loop with query arguments. Perhaps give me more details or code?

**Comment by APEWAW** [comment]
I try to return the category name of my custom posts « resource ». The slug for the taxonomy is « category-resource ». On my single page « resource-single.scout », the category name appears. But not on my archive page « page-resource.scout » with this query loop: 

```
@query(array('post_type' => 'resource', 'posts_per_page' => 6))
<div class="col-md-4">
<article {{ Loop::postClass('card') }} role="article">
<div class="card-image">
<a href="{{ Loop::link() }}">{{ Loop::thumbnail('card', array('class' => 'img-responsive')) }}</a>
<ul>
@foreach(Loop::terms(‘category-resource’) as $term)
<li>{{ $term->name }}</li>
@endforeach
 </ul>
</div>
<div class="card-content">
<h2 class="card-title"><a href="{{ Loop::link() }}">{{ Loop::title() }}</a></h2>
<p>{{ Loop::excerpt() }}</p>
</div>
<div class="card-footer">
<span class="pull-left">Released in {{ Meta::get(Loop::id(), 'date') }}</span>
<span class="pull-right"><a href="{{ Loop::link() }}" class="btn btn-primary btn-sm">Download <i class="fa fa-download" aria-hidden="true"></i></a></span>
</div>
</article>
</div>
@endquery
```
Thank you for your help!

**Comment by jlambe** [comment]
The `Loop::terms('slug', $postID)` accepts a post ID as a second parameter, perhaps try to pass the `Loop::id()` as the second argument to it. Cheers!
