### ISSUE TITLE
Composer returns [Composer\Downloader\TransportException]

### ISSUE THREAD

**Issue by adampatterson** [themosis/themosis#130]
Running `composer create-project themosis/themosis themosis` gives me the following error.

```
[Composer\Downloader\TransportException]
  Your configuration does not allow connections to http://wpackagist.org/packages.json. See https://getcomposer.org/doc/06-config.md#secure-http for details.
```

I checked and https://wpackagist.org/packages.json is valid. I can change my config to allow this to pass but I don't think I should have to.

**Comment by jlambe** [comment]
Yes that's the way to go for current release 1.2.3. This is fixed on coming release though.

**Comment by adampatterson** [comment]
Thanks, looking forward to trying this out.
