### ISSUE TITLE
Translation files getting overwritten

### ISSUE THREAD

**Issue by maciejslawik** [themosis/themosis#131]
Hello.
I have a website running Themosis 1.2.3 with Wordpress 4.7. I use Loco Translate and qTranslateX and W3 Cache plugins. 

I have an issue with translation files. They seem to get overwritten automatically and translations that I have added disappear breaking the site. Both .po and .mo files are overwritten. I think I have added all the constant that should stop automatic updated but it didn't help.
Right now I'm forced to run a cron each minute to checkout the .mo files.

Do you have any idea what might the problem be?
I haven't experienced this problem on just-Wordpress sites. 

Regards.

**Comment by jlambe** [comment]
Hi @maciekslawik,
that's a strange behavior indeed.
The Themosis framework do not handle translation files, meaning there is not a line of code that try to manage anything related to translations. It uses some core `i18n` or `l10n` functions like `__()` for its own use but nothing fancy.

Are you talking about your theme translation files ? or a custom plugin translation files? normally, WordPress auto-update only update the core language packs for the admin so nothing should change except if your theme or plugin is registered into WordPress.org but I assume not if you're using the theme coming from the framework. The only way to loose your theme files would be to run a composer update command with your theme still named `themosis-theme`. In any other cases the framework don't modify any files.

I don't know the Loco Translate plugin so I can't be of any help with this. Normally you should have provided a theme `.po` file yourself. But if it's not the case, is one of your translation plugin generates such file? if so, I would dig into that plugin.

**Comment by szepeviktor** [comment]
@jlambe Themosis could include something like https://github.com/Dhii/wp-i18n

**Comment by jlambe** [comment]
@szepeviktor We can open an issue to discuss translations inside the framework. Currently it's not a priority but if this is pain point for many developers, we could tackle it at some point. Open to suggestions ;)
