### ISSUE TITLE
WordPress database error on new installation

### ISSUE THREAD

**Issue by LittleHamster** [themosis/themosis#132]
Hi, 
When setting up the newest version `1.3` during the WordPress installation I get this error: 
```
WordPress database error: [Table 'themosis.wp_options' doesn't exist]
```
I installed WordPress but this error message just shows up during installation, is that normal?

**Comment by jlambe** [comment]
Have you defined nonces keys within the `config/shared.php` file?

**Comment by LittleHamster** [comment]
@jlambe no I didn't, isn't that automatically set when installing WP?

**Comment by jlambe** [comment]
Nope you have to define them before to protect your website.

**Comment by LittleHamster** [comment]
@jlambe thanks.
