### ISSUE TITLE
Multisite wp-admin redirect loop

### ISSUE THREAD

**Issue by Rhinni** [themosis/themosis#133]
Hello,

Thanks for this amazing framework. After developing my site for a while I decided I had to turn it into a multisite network to fulfil my needs.

I transformed my current themosis wp site into a multisite one by following http://framework.themosis.com/docs/1.3/multisite/ 

It went pretty flawless for the main site http://scode.nl/themosis/htdocs/
However, after adding a second site I ran into a problem. I can't get into the wp-admin part of the second site. 

The second site is: http://scode.nl/themosis/htdocs/pets/
I can get to the login screen at http://scode.nl/themosis/htdocs/pets/wp-login.php and login. 
However, I get redirected to the homepage http://scode.nl/themosis/htdocs/pets/ instead of the expected scode.nl/themosis/htdocs/pets/wp-admin. Whenever I try to navigate to scode.nl/themosis/htdocs/pets/wp-admin I get redirected to the homepage. 

I suspect it's a wp-config (local.php) or htaccess problem, but I can't figure it out. Any directions are appreciated!

local.php:
```
// Database
define('DB_NAME', getenv('DB_NAME'));
define('DB_USER', getenv('DB_USER'));
define('DB_PASSWORD', getenv('DB_PASSWORD'));
define('DB_HOST', getenv('DB_HOST') ? getenv('DB_HOST') : 'localhost');

// WordPress URLs
define('WP_HOME', getenv('WP_HOME'));
define('WP_SITEURL', getenv('WP_SITEURL'));

// Development
    define('WP_DEBUG', true);
    define('SCRIPT_DEBUG', true);

    // Themosis framework
    define('THEMOSIS_ERROR_DISPLAY', true);
    define('THEMOSIS_ERROR_SHUTDOWN', true);
    define('THEMOSIS_ERROR_REPORT', 0);

define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'scode.nl');
define('PATH_CURRENT_SITE', '/themosis/htdocs/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
```

htaccess:
```
# BEGIN WordPress
RewriteEngine On
RewriteBase /themosis/htdocs/
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) cms/$2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ cms/$2 [L]
RewriteRule . index.php [L]
# END WordPress
```

**Comment by jlambe** [comment]
Hi,
I think there is an issue regarding your project structure as `themosis/htdocs` should never be public. Normally your server should point to the `htdocs` folder and be the public root.

Also do you use a custom role? if so, you need to add it into your `theme.config.php` access property to avoid redirection.

**Comment by Rhinni** [comment]
Hello,
I don't use a custom role, and getting into the wp-admin section of the main site of the multisite network is not a problem. I understand that I would normally set themosis/htdocs as my public root, but this is my development server where I run multiple projects, so I cannot set that as my themosis/htdocs and it has not been a problem (been developing this sites over the course of a few months) until I enabled the multisite network and added a second site. The first site still works well, but I cannot visit the wp-admin pages on the added site.

**Comment by Rhinni** [comment]
I see that wp-admin works when I don't have the Themosis theme activated, so I suspect the access property is causing the redirect due to the superadmin role, however when I add super (which seems to be the slug) to the access list, the problem does not get solved

**Comment by jlambe** [comment]
Hmm I will test this. There is no "super-admin" role in fact. It is a site options under `site_admins` site meta which stores an array of users usernames to grant access as super admin. So in theory, if your user role is an "administrator" with granted access as "super-admin" and you're registered as a user of the second site, it should work but it's not.

So the issue here is that you can't access the administration of all sites except the default one?

**Comment by jlambe** [comment]
@Rhinni Can you try to comment out the line 155 of your theme `functions.php` file? Look after this line: 
```php
$theme['action']->add('init', 'themosis_theme_restrict');
```
Comment this line above and let me know how it works against your issue.

**Comment by Rhinni** [comment]
Thanks for your response. I think I'm using an older version of the framework, I can't find that line of code in functions.php. I ran a search on the project in general and can't find that line of code.

**Comment by jlambe** [comment]
Version 1.3.0 has now been released, please consider updating before doing more development. Check the upgrade guide: http://framework.themosis.com/docs/1.3/upgrade/ for more information.

**Comment by Rhinni** [comment]
Thanks, I followed the upgrade steps.

I now get the following Exception:
`Use of undefined constant THEMOSIS_THEME_TEXTDOMAIN - assumed 'THEMOSIS_THEME_TEXTDOMAIN'`

```
/var/www/themosis/htdocs/content/themes/scode-theme/resources/config/menus.config.php

    <?php
     
    return [
     
        /*
        * Edit this file to add navigation menus. 
        * Insert as many locations as you want.
        * Key is menu location slug and its value is its description.
        * http://codex.wordpress.org/Function_Reference/register_nav_menus
        * 
        */
        'header-nav'    => __('Header navigation', THEMOSIS_THEME_TEXTDOMAIN),
        'footer-nav'    => __('Footer navigation', THEMOSIS_THEME_TEXTDOMAIN),
        'mobile-nav'    => __('Mobile navigation', THEMOSIS_THEME_TEXTDOMAIN),
     
    ];
```

**Comment by jlambe** [comment]
@Rhinni Thanks for pointing this. It's an error from my part. It's `THEME_TEXTDOMAIN` the constant theme to use. I'll update the docs asap. Let me know how it goes.

**Comment by Rhinni** [comment]
I had made a folder called lib in the assets folder which could not be found after the upgrade. Perhaps it's an idea to suggest that all custom folders/files in the assets folder also have to be moved/copies into the dist folder after the upgrade.

Now there's no more fatal exceptions, but just a white screen. I have to go for a bit, but will investigate a bit by myself later. Thanks for the help so far!

**Comment by jlambe** [comment]
Yes, normally you have to move the old `resources/assets` to `dist`. Ok keep me in touch against your upgrade.

**Comment by Rhinni** [comment]
It currently crashed on do_action( 'init' ); in wp-settings.php row 449

Somehow I don't see any errors, just a blank white page. As far as I can see no errors are logged either (apache, mysql or php errors). All error displaying is enabled in local.php.

Do you have any pointers for me where to look further?

**Comment by jlambe** [comment]
If you have followed the upgrade guide, the theme now uses PHP namespaces. So your current home route is looking after a `Theme\Controllers\HomeController` class.

In your controllers, simply add a namespace like so: `namespace Theme\Controllers;` at the top of your file just after the opening php tag.

**Comment by Rhinni** [comment]
My HomeController:
```
<?php

namespace Theme\Controllers;

use Themosis\Route\BaseController;

class HomeController extends BaseController {

    protected $layout = 'pages.home';

    public function __construct() {
        exit('working');
        //add variable
        //$this->layout->with('key', 'hello');
    }

    protected function index() {
        // My index stuff
    }
}
```

It does not reach the exit statement in the construct

**Comment by jlambe** [comment]
Do you have the RoutingService provider setup in your theme?

**Comment by Rhinni** [comment]
providers.config.php:
```
<?php

/**
 * Define a list of service providers to use in your theme.
 */
return [
    Theme\Providers\RoutingService::class
];
```

RoutingService.php:
```
<?php

namespace Theme\Providers;

use Themosis\Facades\Route;
use Themosis\Foundation\ServiceProvider;

class RoutingService extends ServiceProvider
{
    /**
     * Define theme routes namespace.
     */
    public function register()
    {
        Route::group([
            'namespace' => 'Theme\Controllers'
        ], function () {
            require themosis_path('theme.resources').'routes.php';
        });
    }
}
```

**Comment by jlambe** [comment]
Did you update the `loading.config.php` file to take care of the namespace?
Perhaps you can share your project code somewhere to better see what might be the issue?

**Comment by Rhinni** [comment]
I have uploaded my theme as a zip file, does this work for you?
http://www.filedropper.com/scode-theme

I believe I followed all steps of the upgrade guide. My `loading.config.php`:
```
<?php

return [

    /*
    * Edit this file in order to configure your theme's
    * classes autoloading. Classes are loaded using PSR-4.
    *
    * The key is the namespace and key's value contains one or more paths to your classes.
    */
    'Theme\\Controllers\\' => themosis_path('theme.resources').'controllers',
    'Theme\\Models\\' => themosis_path('theme.resources').'models',
    'Theme\\Providers\\' => themosis_path('theme.resources').'providers'

];
```

**Comment by Rhinni** [comment]
Hello jlambe,

Have you had time to take a look at the files?

Thanks in advance!

**Comment by jlambe** [comment]
Hi @Rhinni, no not yet but you can remind me ;) Normally next week i'll be able to take some time to look at your code.

**Comment by Rhinni** [comment]
Hello @jlambe ,

I don't mean to bug you but I would love if it you could have a look at it soon. This project is at a halt until this problem is solved and I would really like to continue.

Thanks in advance!

**Comment by jlambe** [comment]
Hello @Rhinni,

I've tested a fresh multisite installation and added multiple websites (in subdomains) and I haven't yet encountered your redirect issue.

I would suggest you to make a new installation and convert your theme and install it on your new WordPress installation without any other plugins in order to check your themes do not make "evil" things causing that redirect.

**Comment by Rhinni** [comment]
Thanks for the update.
The redirect issue was fixed a while ago, the issue since the upgrade to 1.3 has been a 500 server error.

I have created a fresh install on a clean vps just for this project. Everything goes fine, setting up the multisite and everything, until I place back my old project's files. 

More has changed in the new version than the upgrade guide shows. You now need to use a use statement to include a Model into a Controller or anywhere else basically and use it. Maybe you could add this to the upgrade guide?
`use Theme\Models\PostModel;`
Otherwise you get the error:
`Class Theme\Controllers\PostModel does not exist`

Anyway, putting back my homecontroller, models and home views went fine after the updated use statements. However when  I put back my admin/actions.php file I get a 500 server error.
I've traced it down to the function `PostType::make()` that I have in a model.

I even removed my own version and replaced it with the one in the documentation:
```
PostType::make('books', 'Books', 'Book')->set([
    'public' => true
]);
```
But I still get a blank screen (status 500). If I place a return statement above this line, my site loads fine. 
Somehow if I place an echo in actions.php, it does show the echo on screen, but the rest of the screen is blank (dev tools show status 500 headers).

In actions.php I load a class CustomPostTypes that creates the custom post types by passing parameters to a model CustomPostTypeModel. In the CustomPostTypeModel I make the custom post type according to http://framework.themosis.com/docs/1.3/posttype/. Even the stripped version shown above returns in the 500 server error.

**If I place PostType::make directly in the admin/CustomPostTypes class it works fine, so I traced the issue to calling PostType::make in a model**

**Comment by jlambe** [comment]
Yes, php namespace is heavily used now so each time you use namespaced classes, make sure to import the others ones with the `use` keyword. Same with WordPress classes that don't have namespace like `\WP_Query`. (note the backslash in front).

**Comment by Rhinni** [comment]
So what is the use statement I have to use for PostType?

**Comment by jlambe** [comment]
the facade one: `use Themosis\Facades\PostType;`

**Comment by jlambe** [comment]
same for other classes, check the plugin guide, there is a list of facades to import in order to use the APIs: http://framework.themosis.com/docs/1.3/plugin/#themosis-facades

**Comment by Rhinni** [comment]
Thanks! I will try it out in a bit. Any idea why I don't get a fancy exception when it can't find this namespace (get a 500), but I do get a fancy exception if I miss the namespace for a model in a controller. It's tough debugging without feedback.

**Comment by jlambe** [comment]
I haven't had this issue before. Anytime I haven't import a class, I did get a "not found class" error. I suppose you do have another error in your code. Check your php or server logs for more details.

**Comment by Rhinni** [comment]
Thanks for your help with the issue. Fixed the white screens of death with a custom errorhandler to catch the errors the framework does not (there's no logs in either the apache2 error log or php error log, even after forcing them in php.ini). But this will do!

**Comment by jlambe** [comment]
Great to hear that. Can you perhaps share your error handler ? it might enhance the current one loaded in the framework. Cheers,

**Comment by Rhinni** [comment]
It's nothing fancy, just a snippet I found online that did the trick. It's especially lacking a useful trace and you can't see where the file is located where the error occurs. Example output of the error handler (you saw it in the exit twig topic):

`E_WARNING Error in file �ThemosisTwigExtension.php� at line 57: call_user_func_array() expects parameter 1 to be a valid callback, function 'die' not found or invalid function name`

I removed the output of `E_USER_DEPRECATED` and `E_USER_NOTICE` because they show some notices about the themosis theme that are not relevant for me.

```
ini_set('display_errors', 'On');
ini_set('html_errors', 0);
error_reporting(-1);

// ----------------------------------------------------------------------------------------------------
// - Shutdown Handler
// ----------------------------------------------------------------------------------------------------
function ShutdownHandler()
{
    if(@is_array($error = @error_get_last()))
    {
        return(@call_user_func_array('ErrorHandler', $error));
    };

    return(TRUE);
};

register_shutdown_function('ShutdownHandler');

// ----------------------------------------------------------------------------------------------------
// - Error Handler
// ----------------------------------------------------------------------------------------------------
function ErrorHandler($type, $message, $file, $line)
{
    $_ERRORS = Array(
        0x0001 => 'E_ERROR',
        0x0002 => 'E_WARNING',
        0x0004 => 'E_PARSE',
        0x0008 => 'E_NOTICE',
        0x0010 => 'E_CORE_ERROR',
        0x0020 => 'E_CORE_WARNING',
        0x0040 => 'E_COMPILE_ERROR',
        0x0080 => 'E_COMPILE_WARNING',
        0x0100 => 'E_USER_ERROR',
        0x0200 => 'E_USER_WARNING',
        0x0400 => 'E_USER_NOTICE',
        0x0800 => 'E_STRICT',
        0x1000 => 'E_RECOVERABLE_ERROR',
        0x2000 => 'E_DEPRECATED',
        0x4000 => 'E_USER_DEPRECATED'
    );

    if(!@is_string($name = @array_search($type, @array_flip($_ERRORS))))
    {
        $name = 'E_UNKNOWN';
    };
    
    if ($name == 'E_USER_DEPRECATED') {
        return;
    }
    if ($name == 'E_USER_NOTICE') {
        return;
    }
    
    return(print(@sprintf("%s Error in file \xBB%s\xAB at line %d: %s\n", $name, @basename($file), $line, $message)));
};

$old_error_handler = set_error_handler("ErrorHandler");
```
