### ISSUE TITLE
Register taxonomy

### ISSUE THREAD

**Issue by moise** [themosis/themosis#134]
Hello @jlambe 
from version 1.3 I have an issue when registering custom taxonomies and making taxonomy queries.

I have this code in theme.php (resources->admin folder)

```PHP
Taxonomy::make('authors', 'post', 'Authors', 'Author')->set([
	'public' => true
]);
```

any query with this taxonomy it fail because of this WP function taxonomy_exists($taxonomy) that return always false. Even if my WP_Query is called after this code the function return false...any idea?

thank you in advance
Moise

**Comment by jlambe** [comment]
What happens if you chain the `bind()` method?
```php
Taxonomy::make('authors', 'post', 'Authors', 'Author')->set([
	'public' => true
])->bind();
```

So any query to `domain.com/authors/some-name-term` fail? Core has also a defined permalink to `domain.com/author/some-name`, perhaps it conflicts with your taxonomy.

Also I think that calling the `taxonomy_exists()` function always return `false` if not run after a `init` hook at least. If you're using it inside your `theme.php` file as a condition before registering your taxonomy, it is expected to always have `false` as a returned value.

**Comment by moise** [comment]
The `bind()` method doesn't solve the issue.

Putting all the code (the WP_Query too) in a init hooks, works well but my query is in a Posts.php model class and the `Taxonomy::make()` is in a file called taxonomies.php in the resources/admin folder.
When I'm calling the the query from a controller class or directly from a view file (with a static method) it return an empty array caused by the `taxonomy_exist()` return.

My code was an example only but the problem coming with any taxonomy.
It seems like when I'm calling the query the `Taxonomy` is not registered yet...

**Comment by jlambe** [comment]
So you have:

1. A custom taxonomy defined in the `resources/admin/theme.php` file (Do not wrap it with an `init` hook).
2. A `Theme\Models\Posts` model class.

From your model class, there is a method where you check for your taxonomy using the `taxonomy_exist()` function. You call that method from a controller method or directly from a view file and it returns false, is that right?

Is your `taxonomy_exist()` call done inside the model method or model constructor? Do you have any results when calling the function `get_terms()` for your taxonomy ?

**Comment by moise** [comment]
In fact I have:

1. A custom taxonomy defined in the `resources/admin/taxonomies.php` and not wrapper in hooks.
2. As you said `Theme\Models\Posts` model class.

From my model class I just have a method where I made a normal `WP_Query()` with a `tax_query` argument. The `taxonomy_exist()` function is made by the `WordPress` Core while parsing the `WP_Query()` arguments. Exactly in the `/htdocs/cms/wp-includes/class-wp-tax-query.php` at line `563` in the private method called `clean_query`

> Is your taxonomy_exist() call done inside the model method or model constructor? Do you have any results when calling the function `get_terms()` for your taxonomy ?

The same issue when I just want to retrive the terms in taxonomies...WordPress before doing anything it check if the `taxonomy_exist()` and the `get_terms()` return an empty `array()` and I'm absolute sure there isn't mistakes about terms because with a custom `get_terms()` function, where I just deleted the `taxonomy_exist()`check, it works.

**Comment by jlambe** [comment]
Ok I've probably have a guess and your issue.

Your taxonomy is defined from a file inside the `admin` directory. By default, those files are read after the `routes.php` (and attached controller), so the result is expected as you create the taxonomy after it.

The easiest solution, is to write a ServiceProvider in your theme, and load it before the RoutingService using the `config/providers.config.php` file of your theme.

The best solution, write a custom plugin where you define your Taxonomy, its model, ... and then only call the API in your theme.

Let me know how it goes.

**Comment by moise** [comment]
Ok @jlambe 
first of all thank you very much for your support and work. The framework (I'm working with it since the version 1.0) is super and the support too.

Tomorrow I'll try the "best solution" and let you know.
Thanks

**Comment by jlambe** [comment]
@moise Ok, follow the [plugin guide](http://framework.themosis.com/docs/1.3/plugin/) in order to get started with plugin development.

Let me know if you encounter any issues during the process so I might update the documentation as well based on feedback.

**Comment by moise** [comment]
hello @jlambe 
I tried in different ways by every time I'm encountered this error:
`Call to undefined function Themosis\User\wp_get_current_user()`

First I tried with a mu-plugin, and next with a "normal" plugin with the same error result.

After the plugin setup I just added those line of code in the end of plugin main file, just below the comment: 

```PHP
/*
 * Add extra features below.
 */
$service = PostType::make( 'service', 'Services', 'Service' )->set();
$category = Taxonomy::make( 'service_category', [ $service->get( 'name' ) ], 'Categories', 'Category' )->set( [
	'hierarchical' => true,
] );```

**Comment by moise** [comment]
UPDATE:
solved the error putting the code with an `init` hook but the bug about `taxonomy_exist()` is still there. In fact the function `get_terms()` still return a `WP_Error()`

**Comment by jlambe** [comment]
@moise You should put your code into the plugin `resources/admin` directory.

You don't have access to class alias in plugin. You need to import the classes by adding `use` statements like:

```php
use Themosis\Facades\PostType;
use Themosis\Facades\Taxonomy;

$service = PostType::make( 'service', 'Services', 'Service' )->set();
$category = Taxonomy::make( 'service_category', [ $service->get( 'name' ) ], 'Categories', 'Category' )->set( [
	'hierarchical' => true,
] );
```

**Comment by moise** [comment]
yeah sorry I forgot to paste the `use` but it was there...

putting the code in the admin folder doesn't solve the `taxonomy_exist()` issue. As you said, It seems like admin files are loaded too earlier...

this code solved my issue but it seem too much to a workaround...
```PHP
add_action('init', function() {
	View::share( [
		'nav' => with( new \Theme\Controllers\Navigation() ),
	] );
}, 99);```

**Comment by jlambe** [comment]
And when you put your `View::share` code inside the theme `routes.php` file, you still get a taxonomy error? Yes, adding an init hook is overwhelming.

**Comment by moise** [comment]
Yes putting the `View::share ` in routes.php gave Error, like `routes.php` is loaded before `register_taxonomy`

**Comment by jlambe** [comment]
Yes, and putting your `View::share` code from a theme `resources/admin` file? Does it still throw an error? Normally it shouldn't.

**Comment by moise** [comment]
This code in my `resources/admin/theme.php` throw taxonomy error:
```PHP
View::share( [
		'nav' => with( new \Theme\Controllers\Navigation() ),
	] );
```

and this it doesn't:
```PHP
add_action('init', function() {
	View::share( [
		'nav' => with( new \Theme\Controllers\Navigation() ),
	] );
}, 99);
```

**Comment by jlambe** [comment]
Can you put in a repository your classes so perhaps I can test what you're trying to achieve exactly? I'm working on project now with custom taxonomies and haven't encountered any issues. This is weird.

**Comment by moise** [comment]
I made a test with a fresh themosis project installation and with just those line of code in `themosis-teme/resources/admin/theme.php `

```PHP
PostType::make('books', 'Books', 'Book')->set([
	'public' => true
]);
Taxonomy::make('authors', 'books', 'Authors', 'Author')->set([
	'public' => true
]);
echo '<pre>'; var_dump(taxonomy_exists('authors')); echo '</pre>';die();
```
...and the result was `false`

I don't know if the test is a right test, but I thinks that there will be the same result putting the code in a plugin.

Hope it can help, when I find a little bit of time I'll put the code on Github...

**Comment by jlambe** [comment]
Thanks for posting this. I'll investigate this, I have a `1.3.1` release in progress so it might get added to the list.

**Comment by moise** [comment]
Thanks to you for your great work...I'll try something more in the next few days and I will let you know if I found something more

**Comment by moise** [comment]
Hello @jlambe I didn't tried in the 1.3.1 version because I have an issue with storage views (maybe I will open another Issue) but it seems that too much functions doesn't works on custom folders...for example I made a `theme/resources` folder called "services" and loaded by the `load.config.php` file. In this Class there is a method with an `apply_filter` function that return a fatal: `Call to undefined function Theme\Services\apply_filter() ` I think it's an issue related to my previous report.

In addition, any `define` from `constants.config.php` does not work in Controllers Class methods called from Route.php...

this code in my `Theme\Controller` class not return a fatal: 
`[ $title  => __( 'Doctors', THEME_TEXTDOMAIN ) ]`

this code is in a method called from `Route.php` 

thank you in advance

PS in the version 1.2.* there wasn't similar problems...
