### ISSUE TITLE
Unexpected string when displaying sidebar

### ISSUE THREAD

**Issue by romainhe** [themosis/themosis#136]
Hi,

When I use the following function `{{ fn.dynamic_sidebar('footer_1') }}` (with twig engine) it return the correct sidebar html + a "1" string 

![image](https://cloud.githubusercontent.com/assets/1837829/22256348/b91387b8-e25a-11e6-908f-f5cb4689d855.png)

Any Idea ? :o  Something I'm doing wrong..? 

thx for your help !

**Comment by jlambe** [comment]
Well `dynamic_sidebar` is calling an action hook to display your widget but also return `true` if found. So I suspect that Twig just echo the returned boolean as `1`.

Perhaps try with this `{% fn.dynamic_sidebar('footer_1') %}`

**Comment by romainhe** [comment]
That's what I thought :/ 
I already try with {% but twig return an error for this... :(

**Comment by jlambe** [comment]
A way to fix this is to add a `dynamic_sidebar` twig function. You'll need to extend Twig. For this I encourage you to read the Twig official documentation but in order to extend the loaded Twig engine from your application, check the Twig documentation on the framework website, in the section "Extending Twig":
- http://framework.themosis.com/docs/1.3/twig/#extending-twig

Here is a link to official documentation page in order to extend Twig and add your own functions and more:
- http://twig.sensiolabs.org/doc/2.x/advanced.html

**Comment by romainhe** [comment]
I will try this, thx for help :) !

**Comment by Bartiff** [comment]
Hi, I have the same problem but I don't understand how I can extend Twig to create a Twig function. @romainhe: Have you found a solution?
And why link the Twig documentation for version 2.x while Themosis seems to use version 1.x?

**Comment by jlambe** [comment]
@Bartiff or a more flexible function:
```php
container('twig')->addFunction(new Twig_SimpleFunction('dynamic_sidebar', function ($id) {
    dynamic_sidebar($id);
}));
```

so you can use the function in your view like so:
```php
{% dynamic_sidebar('index') %}
```

**Comment by mclaurent** [comment]
Hi @jlambe Many thanks for this. Would you be able to advise where to best put this code? I have tried putting it in the themosis' theme functions.php but it isn't registering... does it need to be registered as part of a plugin?

**Comment by jlambe** [comment]
@mclaurent It is best to set this code into a service provider. It can be a provider from your theme or from a plugin for re-use.

**Comment by mclaurent** [comment]
Thanks @jlambe for the quick response. I will give this a try as soon as possible and let you know

**Comment by mclaurent** [comment]
UPDATE - Yeap, all fixed.

For anybody else that is looking for this fix, I created the below class under the 'providers' folder, and then registered it in my providers.config.php.

resources/providers/TwigService.php (new file)
```php
<?php

namespace Theme\Providers;

use Themosis\Foundation\ServiceProvider;
use \Twig_SimpleFunction;
class TwigService extends ServiceProvider
{
    /**
     * Define theme routes namespace.
     */
    public function register()
    {
		container('twig')->addFunction(
				new Twig_SimpleFunction('dynamic_sidebar', function ($id) {
					dynamic_sidebar($id);
				}
			)
		);
    }
}
```


resources/config/providers.config.php (Added the TwigService::class line)
```php
<?php

/**
 * Define a list of service providers to use in your theme.
 */
return [
    Theme\Providers\TwigService::class,
    Theme\Providers\RoutingService::class,
];
```

In my twig templates, I can then render sidebars using the following

```twig
            {{ dynamic_sidebar('my-custom-sidebar') }}
```

**Comment by baryaz** [comment]
here is a way to do it with css you don't have to create enny extanssion:
```
<div id="closelink">
  <a href="">Close</a>
  Click to close
</div>
```
CSS:

```
#closelink {
    visibility:collapse;
}

#closelink a{
    visibility:visible;
}
```
