### ISSUE TITLE
Extends twig layout in an ajax call

### ISSUE THREAD

**Issue by romainhe** [themosis/themosis#138]
Hi, 

Is it possible to play with twig layout and themosis ajax call ? 

I'm trying to extends a specific layout in an ajax call. 

I get this error 
`Twig_Error_Loader
Unable to find template "layouts/overlay.layout.twig"`

my path :

views
- elements
- - ajax
- - - block-recall.twig
- layouts
- - overlay-layout.twig

I render the view block-recall.twig with ajax, and I extend the layout in this block with following : 
{% extends 'layouts/overlay.layout.twig' %}

Big thx for help !

**Comment by jlambe** [comment]
Hi,
is it perhaps your path that is wrong... I see in error message:
- `layouts/overlay.layout.twig`

which is looking after a file named `overlay.layout.twig` and not `overlay-layout.twig` (note the **-**)

**Comment by romainhe** [comment]
ow... I do not understand how I could miss that..... I'm so sorry for the inconvenience 

Thx !
