### ISSUE TITLE
WP_Query in model throwing error

### ISSUE THREAD

**Issue by Cobrarosa** [themosis/themosis#140]
Hi, I'm somewhat new to Laravel/Themosis in general, so pardon me if I'm missing something obvious.

I'm trying to use a basic model for posts in order to fetch posts on the front page. However, using WP_Query inside the model throws a fatal error.

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Theme\Models\WP_Query' not found <siteroot>\htdocs\content\themes\site-theme\resources\models\Post.php:7 Stack trace: <siteroot>\htdocs\content\themes\site-theme\resources\controllers\PagesController.php(12): Theme\Models\Post::all() #1 [internal function]: Theme\Controllers\PagesController->home(Object(WP_Post), Object(WP_Query)) <siteroot>\vendor\illuminate\routing\Controller.php(55): call_user_func_array(Array, Array) <siteroot>\vendor\illuminate\routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('home', Array) <siteroot>\vendor\illuminate\routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Themosis\Route\Route), Object(Theme\Controllers\PagesController), 'home') <siteroot>\vendor\illuminate\routing\Route.php(160): Illuminate\Routing\Route->runController() #6 C:\MAMP\ht <siteroot>\htdocs\content\themes\site-theme\resources\models\Post.php on line 7`

The model looks as follows

`
namespace Theme\Models;
class Post
{
    public static function all()
    {
        $query = new WP_Query([
            'post_type' => 'post',
            'posts_per_page' => -1,
            'post_status' => 'publish'
        ]);

     	return $query->get_posts();
    }
} 
`

Any tips would be much appreciated.

Sincerely
Tomas

**Comment by jlambe** [comment]
Hi,
the error is because we're working with namespace.

In your file, you're on the `Theme\Models` namespace. So if you call a class like so:
```php
namespace Theme\Models;

$query = new WP_Query();
```

The above code would trigger the same error as yours as it will be looking after a class `Theme\Models\WP_Query()` which do not exists.

WordPress classes do not have namespaces. So in order to work, you have to import it into your file like so:

```php
namespace Theme\Models;

use \WP_Query;

$query = new WP_Query();
```

and you're good to go ;)

**Comment by Cobrarosa** [comment]
Thank you, it works! 

I considered a solution like that; just didn't know how to implement it practically. Also, the documentation showing WP_Query being used does not include this solution, so I got a bit confused.

Thanks again for the swift reply!
/Tomas

**Comment by jlambe** [comment]
👍
