### ISSUE TITLE
Exit twig

### ISSUE THREAD

**Issue by Rhinni** [themosis/themosis#142]
I'm trying to exit the execution of a twig template. There's no native twig function for this as far as I can see.

The functions `fn('exit', 'message')` or `fn.die()`, etc.. result in the following error: 
`E_WARNING Error in file �ThemosisTwigExtension.php� at line 57: call_user_func_array() expects parameter 1 to be a valid callback, function 'die' not found or invalid function name`

What do you suggest?

**Comment by jlambe** [comment]
At the moment I have no idea. I can only suggest you to check the official Twig documentation for this case:
- [Twig](http://twig.sensiolabs.org/)

I quickly found this post that suggests you to extend Twig and add the "native" die function to it:
- http://stackoverflow.com/questions/29984378/how-to-kill-execution-in-twig-after-dump

**Comment by Rhinni** [comment]
Thanks,

Can you post a snippet of a service provider example so I can create my own twig extension?
Since http://framework.themosis.com/docs/1.3/service/ and http://framework.themosis.com/docs/1.3/providers/ and http://framework.themosis.com/docs/1.3/container/ are still in development.

Btw I really like how rapidly this framework is expanding and all the cool features that get added.
I love the twig addition since I mainly use Symfony when not working with WP

**Comment by jlambe** [comment]
Here is a Service Provider boilerplate stored into a plugin or theme `resources/providers` directory:

```php
<?php

namespace Theme\Providers;

use Themosis\Foundation\ServiceProvider;

class AssetService extends ServiceProvider
{
    /**
     * Register stuff below.
     */
    public function register()
    {
        // Get Twig environment and register any extension to it.
    }
}
```

After that, open the plugin or theme `providers.config.php` and add your Service Provider to the list. Usually there is already one for routing so I suggest to add yours before the Routing one.

**Comment by Rhinni** [comment]
Thanks, go it working!
