### ISSUE TITLE
.env file and Forge

### ISSUE THREAD

**Issue by Benjaminsson** [themosis/themosis#144]
Hi,

I'm trying to figure out how the .env files is supposed to work. I'm using Digital Ocean with Forge. With Forge you can create an `.env` file but you can't name it. It's just called `.env`. This works by not defining a environment for production/staging in environment.php but when going from staging to production i need to be able to switch of errors and stuff. 

Are you supposed to SSH in and create the variable? Feels wrong when there is an easy way to create the `.env` file in Forge.

Is there a reason why not all variables are created in the `.env`? Wouldn't the files in `\htdocs\my-site\config\environments` be reduntant (in a good way) if you could specify everything in the `.env` file?

The .env documentation says 
>We strongly recommend against having a "main" .env file and an "environment" .env file like .env.test.

Off topic.
Everything else have worked really well with Deploying my first Themosis project on Forge. Really awesome job with the framework @jlambe !

**Comment by jlambe** [comment]
I'm not using Forge but the use of `.env` file is possible. You could pass any or all variables inside the `.env` file and then open the `environments/local.php` or `shared.php` to write any logic for the use of those environment variables.

I'm curious about your project. Is it public?

**Comment by Benjaminsson** [comment]
Perfect! My `local.php` looks like this now.
```
...
// Development
define('SAVEQUERIES', getenv('SAVEQUERIES') ? true : false);
define('WP_DEBUG', getenv('WP_DEBUG') ? true : false);
define('WP_DEBUG_DISPLAY', getenv('WP_DEBUG_DISPLAY') ? true : false);
define('SCRIPT_DEBUG', getenv('SCRIPT_DEBUG') ? true : false);

// Themosis framework
define('THEMOSIS_ERROR', getenv('THEMOSIS_ERROR') ? true : false);
define('BS', false);

```
(i'm rolling my own gulpfile so browser-sync is always of :P )
And my `.env` like this
```
...
THEMOSIS_ERROR = true
SCRIPT_DEBUG #= false
WP_DEBUG_DISPLAY = true
WP_DEBUG #= false
SAVEQUERIES = true
```

It's a bit of a workaround for the boolean values due to the fact that `.env` files can't handle boolean values (maybe that is why you have these environment php files?). 

The project is not public yet. If you want i can mail you the staging site (it's pretty static atm).

**Comment by jlambe** [comment]
If you want or I can wait till the public release ;) Thx
