### ISSUE TITLE
Cannot use Input class

### ISSUE THREAD

**Issue by Cobrarosa** [themosis/themosis#145]
I'm trying to capture query-vars submitted through GET by a search form through my controller using Inputt::all() as stated in the documentation.

However, Input::all() can be used in routes.php, but not in the actual controller to capture the values. I'm probably missing something obvious, but can't figure out what. 

`routes.php
Route::get('lawyers/search', ['uses'=>'MembersController@filterLawyers' ]);
`

Controller method 
`public function filterLawyers()
    {
      $data = Input::all(); 
    }
`

// throws error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Themosis\Input' not found

Not sure on how to add the Input class to my controller. Please advice. 

Best regards
Tomas

**Comment by jlambe** [comment]
Hi,
you have an error at the class import statement probably as the input class full name is: `Themosis\Facade\Input` and not just `Themosis\Input`.

Let me know how it goes! ;)

**Comment by Cobrarosa** [comment]
Still error I'm afraid; I'm probably structuring the file wrong.

This is the start of my MembersController.php:

```
namespace Theme\Controllers;
use Themosis\Facade\Input;
use Theme\Models;
use Themosis\Route\BaseController;
use Theme\Models\Lawyer;

class MembersController extends BaseController
{ 
....
}
```

My error again: 
`Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Themosis\Facade\Input' not found in <local folders>\MembersController.php:`

**Comment by Cobrarosa** [comment]
Nevermind! Spelling error, now it works!

Thanks for the quick reply!

Regards
Tomas
