### ISSUE TITLE
themosis core style css and javascript not loaded in server

### ISSUE THREAD

**Issue by bumbella** [themosis/themosis#147]
Dear Gurus!
I have a problem but I don't see what is the problem with my server config.
local use xampp apache php7.0 and work fine
But I uploaded to my Digitalocean droplet in nginx and php chrooted I give an magic error.

local admin try loading: http://domainname.com/content/mu-plugins/themosis-framework/src/Themosis/_assets/css/_themosisCore.css?ver=1.0
But on the server try:
https://domainname.com/content/plugins/htdocs/content/mu-plugins/themosis-framework/src/Themosis/_assets/css/_themosisCore.css?ver=1.0

What is the extra "content/plugins/htdocs" string in server? I find in php but I don't see.
Please help me. Please
Have a nice work Bumbella

**Comment by jlambe** [comment]
It can be a server misconfiguration or a wrong default path for your project in the `.env` file.
