### ISSUE TITLE
MemberPress Routing

### ISSUE THREAD

**Issue by Benjaminsson** [themosis/themosis#148]
I'm trying to set up a MemberPress section on a site. Out of the box when trying to login i get this message. 

> Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
> No message

I added this to the `routes.php`. 
`Route::post('/login', 'PagesController@page');`
But when trying to log in i just get a blank page (and don't get logged in). I'm supposed to get logged in and redirected (to /account in my case)

I guess the post data get lost somewhere?

**Comment by jlambe** [comment]
WordPress handles a `login` URI redirection already that might conflict. Did you put your route on top of WordPress default routes and run a rewrite rules flush?

**Comment by Benjaminsson** [comment]
Oops, forgot to flush 😊. So, still got the same error message even after adding that line to routes. Renaming the login page to `/my-login` made no difference either.

I found a thread about Woocommerce routes (#51) and added this instead in the top of `routes.php`
```php
 Route::any('page', function() {
   return View::make('layouts.page');
 });
```
Not sure if this will mess up something else but works for now :)
