### ISSUE TITLE
Class Theme\Controllers\ProjectsModel does not exist

### ISSUE THREAD

**Issue by DillonBaren** [themosis/themosis#150]
I am attempting to grab posts from a custom post type called "Projects". In my Controller, the namespace is not working correctly and looking for the ProjectsModel class in Models, but instead looking in Controllers. Can you assist me with this?

`<?php

namespace Theme\Controllers;
use Theme\Models;
use Themosis\Route\BaseController;

class ProjectsController extends BaseController
{

    /**
     * A projects model instance.
     */
    protected $projects;

    /*
     * Auto-instantiate a Theme\Models\ProjectsModel class.
     */

    public function __construct(ProjectsModel $projects)
    {
        $this->projects = $projects;
    }

    public function projects($projects) {

        return view('projects.projects');

    }

    public function single($projects) {

        return view('projects.single');
    }
}`

**Comment by jlambe** [comment]
Simply update your import statement:
use Theme\Models\ProjectsModel;

You're importing your classes for use. The import statement you had looked like a namespace definition. Always define use statements with a full class name.

Hope this helps

**Comment by DillonBaren** [comment]
Ahh, perfect. Thanks!
