### ISSUE TITLE
Settings & sections on a page with a view

### ISSUE THREAD

**Issue by Rhinni** [themosis/themosis#151]
How can I add the settings and save the settings on a Page when I use a custom view? And how do I access the sections in the view? 

At the moment I have the following:
```
$email_templates_view = View::make('admin.email.templates.main');
$email_templates_page = Page::make('email-templates', 'Email templates', $parent = null, $email_templates_view)->set([
    'capability' => 'manage_options',
    'icon' => 'dashicons-email',
    'position' => 20,
    'tabs' => true,
    'menu' => __("Email templates")
]);
$settings['section-slug-name'] = [
    Field::text('street-address'),
    Field::text('phone'),
    Field::media('theme-logo')
];
$email_templates_page->addSettings($settings);
```

The view renders fine, I just don't know how to place the sections and settings in it.
I am using Twig.

Thanks in advance!

**Comment by Rhinni** [comment]
@jlambe do you have some advice for me?

**Comment by jlambe** [comment]
@Rhinni I would suggest you to look after the core page view. Basically the Page instance is passed to your custom view. All you have to do is call the instance methods to handle the display of your sections and settings (still using core section and field views): https://github.com/themosis/framework/blob/master/src/Themosis/Page/Views/pages/_themosisCorePage.scout.php

This should give hints. Let me know how it goes!

**Comment by Rhinni** [comment]
Thanks, I got that working.
Now I want to display data depending on which tab is active.
I see pageBuilder has a method getActiveTab(), it is protected however.
How can I get the active tab (preferable without reading the get parameters).

And how can I build the sections myself? $this->sections is also a protected parameter.

**Comment by Rhinni** [comment]
For now I've just injected the sections by building them before adding the view to the page, so I add the sections as a parameter to the view.

```
$sections[] = Section::make('dashboard', 'Dashboard');
$sections[] = Section::make('add-template', 'Add template');
$email_templates_view = View::make('admin.email.templates.main')->with(['sections' => $sections]);
$email_templates_page = Page::make('email-templates', 'Email templates', $parent = null, $email_templates_view)->set([
    ... settings here ...
]);
$email_templates_page->addSections($sections);
```

 It feels a bit weird to have to do this. I would expect there to be a way to retrieve the sections from the __page variable or pageBuilder class

**Comment by jlambe** [comment]
@Rhinni You'll have to define your own tabs on your page view. The `getActiveTab()` method is very specific to the core view and the api was not yet meant to be extended. Nonetheless, a bit of javascript and a custom html structure for your tabs will do it.

The sections are available in your page view under the `$__sections` variable.

**Comment by Rhinni** [comment]
`$__sections`, makes sense 😃 thanks

I will continue my journey, it still all feels a bit vague when you want to do more than basics. But I'm sure it will get more clear the more I use it.
