### ISSUE TITLE
Move Default Metaboxes like categories

### ISSUE THREAD

**Issue by swaraasolutions** [themosis/themosis#153]
I am trying to move the metabox of categories from right side to above post title
I tried adding remove_meta_box in resources\admin\theme.php but it gives me error remove_meta_box is not a function.

Is there any way i can remove and re-add the categories option in the middle section.

Help is much appreciated.

Thanks

**Comment by swaraasolutions** [comment]
Hi,
To update on this scenario i would like to move the metaboxes below title i have set the priority to high for the metaboxes and have tried changing the context to advanced too however i am unable to get it below title

Any help will be appreciated.

Thanks

**Comment by jlambe** [comment]
@swaraasolutions This is a WordPress issue which do not relate to the framework.

By default there are no metabox context available for you to insert a metabox under the title.

Nonetheless, it is possible. All you have to do is to take the appropriate hook, register a custom metabox context there and then assign it to your metabox. Here is an example as I had to do it as well recently:

```php
Action::add('edit_form_after_editor', function (\WP_Post $post) {
    if ($post->post_type === 'yourCustomPostType') {
        echo sprintf('<div class="%s" style="%s">', 'aftereditordiv', 'margin-top: 10px;');
            do_meta_boxes('yourCustomPostType', 'after_editor', $post);
        echo sprintf('</div>');
    }
});
```

Then when creating your metabox, do the following:

```php
Metabox::make('Title', 'yourCustomPostType', ['context' => 'after_editor'])->set();
```

In the above example, we use our custom `after_editor` context.

**Comment by swaraasolutions** [comment]
Great thanks for your response.

 

Much appreciated.

 

Regards

 

Varun Varde

COO – Swaraa Solutions LLP

Contact: +91 – (0) 84606 13654

Email:  <mailto:varun@swaraasolutions.com> varun@swaraasolutions.com
