### ISSUE TITLE
[1.3] Retrieve the current environment name

### ISSUE THREAD

**Issue by bgatellier** [themosis/themosis#156]
Hi, 

I there a way to retrieve the current environment name (dev, staging, prod) ?

The name used when creating the .env.* file

**Comment by jlambe** [comment]
Actually there is no constant for this but you can add your own into each environment files using same key. Then you'll be able to check into what environment you are.

You can define a key variable into your .env files or define a constant into each config/environments files.

**Comment by bgatellier** [comment]
Okay, thx for the answer !
