### ISSUE TITLE
What to add to version control

### ISSUE THREAD

**Issue by matt3224** [themosis/themosis#159]
Hey,

I have started working with themosis and my main question is how best to version control it. I work with a small team of devs and would like to use the `local -> staging ->  production` flow.

I imagine you would add the entire project to the repo and ignore the vendor and cms folders. However if i do that how can a collegue pull the repo and reinstall the cms or is it done with composer update?

Thanks

**Comment by matt3224** [comment]
Ah, somehow didnt think to look in the provided gitignore 😶

**Comment by jlambe** [comment]
Exactly. WordPress and any dependencies (WordPress plugins and PHP packages) are installed automatically through Composer. 😄
