### ISSUE TITLE
How to install Themosis in a subfolder

### ISSUE THREAD

**Issue by Blair2004** [themosis/themosis#160]
Hi, 
i really like this Framework, but i'm encountring some issue. Actually, i would like to install themosis in a subfolder like this : 
`public_html/themosis/`

instead of installing themosis at the root, i don't want to merge it with system folder so that when i'll will (maybe) want to delete it, i won't delete system folder.

I would also like to make a kind of URL rewriting (i've yet tried, but it doesn't work) Here is the desired URL

`http://example.com`

Which should point to "http://example.com/themosis/htdocs" Do you have any idea ?

Also currently http://example.com/themosis/htdocs/cms/wp-admin is perfectly working, but everytime i'm trying to install a plugin/theme, i have a prompt which request FTP/SFTP connexion....  i would like to fix that also.

Thank you a lot.

**Comment by Blair2004** [comment]
FTP/SFTP issue fixed. I was using SSH to install WordPress.

**Comment by jlambe** [comment]
It won't work. I suggest you to modify your server configuration. Your `public_html` should be the `htdocs` of the framework.

You can install themosis on sub-folder but the url will be `example.com/themosis/htdocs`. For what you're trying to achieve, you need access to the Apache vhost configuration on your server and set the server path to `public_html/themosis/htdocs` for the server name `example.com`. If you don't have access to your server configuration, there is nothing you can do.

**Comment by Blair2004** [comment]
I have access to that, i have a dedicated server Centos 6.9, but i've made a search for httpd-vhost.conf or any related file with ".conf", but i'ven't found anything. So it's not possible to do it from htaccess ?

**Comment by Blair2004** [comment]
if it's not possible, i'll move it to the root... even if i ain't like this method.

**Comment by Rhinni** [comment]
Perhaps your dedicated server is not yet configured for virtual hosts. 
You can follow a guide to set it up:
https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-centos-6

**Comment by Blair2004** [comment]
@Rhinni i've already read that tutorial. Anyway, i'll move everything to the root. I was just wondering, about update how is it going to work, i mean Themosis update. Will i extract files to the root manually, or github can do it ?

**Comment by jlambe** [comment]
The application is handled by Composer so at project root, you'll only need to run a `composer update`.

Updating your Apache or SQL or any other related tools won't affect the projects. The structure of the framework is made so in order to avoid to put credentials at server root (public access).

**Comment by Blair2004** [comment]
Ok thank you
