### ISSUE TITLE
Class 'Tld\Domain\Plugin\Controller' not found

### ISSUE THREAD

**Issue by yamilelias** [themosis/themosis#162]
Right now I have a Controller that will handle all the logic that I need for my `View::Composer()`. Right now I have a php file: `resources/admin/plugin.php` that creates a metabox and have its own view composer. For this I need to call the controller, so I'm calling it right after the View is created. 

I'm having issues locating the Controller. When I try to call it (as will be shown in the following code) using three different options, I always get ` Error
Class 'Tld\Domain\Plugin\Controller' not found`. It seems is not finding my Controller. The code is the following:

```
use Tld\Domain\Plugin\Controller;

//...
// More code here
//...

Metabox::make('Providers', 'product', [
    'context' => 'side',
    'priority' => 'low',
    'id' => 'providers-metabox'
], View::make('metabox.providers'))->set();

// Tried each one of them separately, I didn't run them all together
Controller::init(); // Option #1: Created a static function that will run all View::Composer()
new Controller(); // Option #2: In the __construct() I run all the View::Composer()
Tld\Domain\Plugin\Controller::init(); // Option #3: Call it with the whole namespace
// None of them didn't work...
```

The controller code is the following:

```
namespace Tld\Domain\Plugin;

use Illuminate\View\View;
use Themosis\Route\BaseController;

class Controller extends BaseController
{
    __construct(){
        // Run View::Composer()
    }

    public static function init(){
        // Run View::Composer()
    }

    // More functions
}
```

The funny thing is that my IDE (I'm using PhpStorm) detects the controller! It autocomplete everything and make references through files. I already changed the paths as the plugin boilerplate says so. I did the following:

1. Set properties in plugin root file
2. Update the file names of the given default configuration files
3. Update PSR-4 loading rules in just renamed loading.config.php file
4. Update service providers in just renamed providers.config.php file
5. Refactor the defaults files

I don't know if I missed something, I already checked again each one of that files for errors but everything is ok there. Right now I'm having this issue in a localhost with no domain configured (is just a localhost). My `.env.local` looks like this:

```
DB_NAME = "wordpress"
DB_USER = "wordpressuser"
DB_PASSWORD = "password"
DB_HOST = "localhost"
WP_HOME = "http://localhost"
WP_SITEURL = "http://localhost/"
```

Any suggestions are welcome with this issue. Thanks by the way for reading it all.

**Comment by jlambe** [comment]
Hi,
when you rename your plugin configuration files, make sure to prefix them like so `tld_domain_plugin_loading.config.php`. The default prefix is a placeholder. Let's say for the example that you're working for the Example Corp. and create a forum plugin, your files and namespaces would be like so:

```php
namespace Com\Example\Forum\Controllers;

// Plugin file names and paths.
com_example_forum_loading.config.php
```

It sounds like you haven't correctly rename your files and that the plugin autoloading config is not called (only the one setup in the theme which do not hold your plugin loading rules).

For more information, please read the [plugin guide.](http://framework.themosis.com/docs/1.3/plugin/)

**Comment by jlambe** [comment]
@yamilelias Please keep in mind that the namespace `Tld\Domain\Plugin` part is a placeholder and should be replaced in every plugin you create.

Tld = your company domain extension. Ex.: `Com`, `Org`, `Io`, ...
Domain = your company domain name. Ex.: `Apple`, `WordPress`, `YourCompany`, ...
Plugin = the plugin name. Ex.: `JetPack`, `PdfCreator`, ...

If you write multiple plugins and keep the placeholder namespace from the boilerplate, you might get conflicts names issues with your classes.

**Comment by yamilelias** [comment]
I'm sorry if I wasn't clear in my first comment, but the namespace has already been changed to suit my work, but I didn't wanted to post it here as I have it in the original code. Thank you for the advice and the attention to this issue. You can close it now.

Thanks!
