### ISSUE TITLE
wp_nav_menu walker paramter

### ISSUE THREAD

**Issue by AMarwen** [themosis/themosis#164]
**I want to convert this php code to a twig code :**

wp_nav_menu(array(
                    "theme_location"=>"navigation_principale",
                    'container' => '',
                    'items_wrap' => '<ul>%3$s</ul>',
                    "walker" => new Walker_Nav_Primary()
   ));

**this work perfect :**
{{fn('wp_nav_menu',{
    "theme_location" : "navigation_principale",
    'container' :  '',
    'items_wrap' : '<ul>%3$s</ul>'
}) }}

**but when I tried to create an instance of the walker in wordpress I get an error :**
{{ fn('wp_nav_menu',{
    "theme_location" : "navigation_principale",
    'container' :  '',
    'items_wrap' : '<ul>%3$s</ul>',
    **"walker" : instance of(Walker_Nav_Primary)**
}) }}

**Comment by jlambe** [comment]
You should instantiate your walker class from your controller or route callback and pass it to the view.

If it is common to multiple pages, you might do it using a `View::share()` call and then pass the instance reference to your `wp_nav_menu` function call.

Another solution might be to add a custom Twig function that return a class instance.

See how to extent Twig: http://framework.themosis.com/docs/1.3/twig/#extending-twig
