### ISSUE TITLE
Error establishing database connection on install

### ISSUE THREAD

**Issue by jackie-s** [themosis/themosis#165]
I'm getting the 'Error establishing a database connection' while trying to install. It says it cannot connect to the database server. I have triple checked everything and it all looks good.
```
This either means that the username and password information in your wp-config.php file is incorrect or we can’t contact the database server at 127.0.0.1. This could mean your host’s database server is down.

Are you sure you have the correct username and password?
Are you sure that you have typed the correct hostname?
Are you sure that the database server is running?
If you’re unsure what these terms mean you should probably contact your host. If you still need help you can always visit the WordPress Support Forums.
```

**Comment by jlambe** [comment]
Have you assign a user to your database?
Then verify your `.env.local` file as well as the `config/environments.php` file where you can define the used environments for your project. If using an array, make sure to add your hostname.

Also, take a look in your php log, perhaps there is a hint regarding the issue as well if something is missing from a configuration file.
