### ISSUE TITLE
How do you deal with woocommerce account enpoints?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/themosis#167]
Hi! I am having some problems linking the route to woocommerce account endpoints.

I was only successful in linking the account page but when i click the other links from the account page. I get a blank page instead.

here is the route that i did. I am trying to create a route for the orders, download under myaccount. even the dashboard ain't working.

```
add_filter('themosisRouteConditions', function($conds)
{
    // Add the product condition.
    $conds['shop'] = 'is_shop';
    $conds['product'] = 'is_product'; <-- also having problem with this
    $conds['cart'] = 'is_cart';
    $conds['checkout'] = 'is_checkout';
    $conds['account'] = 'is_account_page';
    $conds['product_cat'] = 'is_product_category';
    $conds['product_tag'] = 'is_product_tag';
    $conds['orders'] = 'is_wc_endpoint_url';
    return $conds;
});
```

with the product. i am able to link the route to a single product but its weird that if i try to access /product only i still get a page instead of being redirected to the shop page.

**Comment by jlambe** [comment]
@rovillesarate Did you register the filter from a service provider? call it on the RoutingService register method, just before the route group call so there are available from the `routes.php` file.
