### ISSUE TITLE
Multisite on Nginx, Re-writes, "cms" fragment-path in  admin

### ISSUE THREAD

**Issue by Cobrarosa** [themosis/themosis#168]
We're using forge and Digital Ocean as hosting for one of our current projects, which is to be a multisite.

Locally, everything works as expected (after following the documentation's description).

However, in production, which uses nginx, certain parts of the network admin does not work.

When on my main site, the "cms"  fragment is present. When switching to network admin views in admin, the "cms"-fragment is removed in the URL, yet the admin still works (I use a LAMP-env locally, with a .htaccess file).

In production, on our nginx-env, this does not work. The main page work, but when clicking on network-admin areas, the "cms" fragment disappears from the URL, resulting in a white page. Adding "cms" to the url manually resolves it. 

I suspect I need to translate something from the htaccess file to the nginx conf, but since I'm unfamiliar with nginx, I'm a bit stumped. 

What approach should I try? 

1) Keep trying to translate the local htaccess rules into nginx-rules. I'm not that good with redirects as it were, so this is mostly like shooting in the dark.
2) Remove the "cms" fragment overall. Is there a downfall in this approach?

Sincerely
Tomas

**Comment by jlambe** [comment]
@Cobrarosa have you read the multisite documentation regarding the `/cms` URI fragment issue?
- http://framework.themosis.com/docs/1.3/multisite/#cleanup-default-url

If it doesn't solve your issue, please let me know!

**Comment by Cobrarosa** [comment]
Yes, I've changed the value for the "home" entry in the table, both locally and in production.

**Comment by jlambe** [comment]
Create a new file inside the `content/mu-plugins` and paste the following content in it:

```php
<?php

/*
Plugin Name: Network Admin URL Fix
Description: Fix the URL to the network admin pages when using a custom WordPress path.
Author: Julien Lambé
Version: 1.0
Author URI: http://www.themosis.com/
Date: 4/06/17
Time: 14:52
*/

/**
 * Parse and fix network admin url.
 *
 * @param string $url The full default URL to parse.
 * @param string $delimiter The delimiter string to use in order to fragment URL.
 *
 * @return string
 */
function themosis_admin_url($url, $delimiter = 'wp-admin')
{
    /*
     * If there is already a "cms" fragment in the URI,
     * just return the URL.
     */
    if (strrpos($url, 'cms') !== false) {
        return $url;
    }

    /*
     * The network admin URL is missing the "cms" fragment.
     * Let's add it.
     */
    $fragments = explode($delimiter, $url);

    /*
     * Insert in the middle the cms fragment appended with the wp-admin delimiter.
     */
    array_splice($fragments, 1, 0, "cms/{$delimiter}");

    /*
     * Build the URL by reducing (concatenating) all fragments.
     * This appends each fragment to the previous one.
     */
    $url = array_reduce($fragments, function ($carry, $item) {
        return $carry.=$item;
    });

    return $url;
}

/*
 * Filter the network URL.
 */
add_filter('network_admin_url', function ($url) {
    return themosis_admin_url($url);
});

/*
 * Filter the default admin URL.
 */
add_filter('admin_url', function ($url, $path, $blog_id) {
    return themosis_admin_url($url);
}, 10, 3);

/*
 * Filter the includes URL.
 */
add_filter('includes_url', function ($url) {
    return themosis_admin_url($url, WPINC);
});
```

Let me know it it has fixed your issue.

**Comment by Cobrarosa** [comment]
Wow, awesome, it works on my local machine. Will try it in production now.

Thanks a lot for your swift reply!

**Comment by jlambe** [comment]
@Cobrarosa How is it going on your production server?

**Comment by toborinojg** [comment]
Hi,

Hope it finds you well.

I followed your instructions and installed this new plugin.
It worked and I can use the Network Admin now.

But I created a new site (a subdirectory) and now I couldn`t use this new website admin, it show a 404 error or a No input file specified message.

Please, how can I fix it?

Thanks in advance.

**Comment by jlambe** [comment]
@toborinojg Please open your own issue. The above code has not been tested on a subdirectory installation (which we generally avoid). You probably have to inspect the filtered url by the plugin above and change to handle your case.

**Comment by toborinojg** [comment]
Hi,

Sorry for wrong place, I`ll open my own issue.
