### ISSUE TITLE
Custom Wordpress Plugin by 3rd Party

### ISSUE THREAD

**Issue by keenojingco** [themosis/themosis#169]
Hi,

I have a problem when activating a custom plugin that was created for a client by a 3rd party provider. The plugin works and runs perfectly well with a default wordpress installation. Activating it on the wordpress-themosis instance raises errors and fixing those errors only bring up more errors. 

I hope this make sense but I was wondering if there was a different way to put and activate plugins on themosis where it activates it the way a default wordpress installation would?

**Comment by jlambe** [comment]
@keenojingco Sounds like your plugin is full of errors.
Themosis shows all errors on local development where WordPress don't. If you want the same "experience", turn off Themosis error reporting from the `config/environments/local.php` file and set the `THEMOSIS_ERROR` constant to false as well as `WP_DEBUG_DISPLAY`.

**Comment by keenojingco** [comment]
@jlambe I got the plugin to work by copying over the config/environments/production.php over to local.php.

Is there a way to change the themosis error log level so that I can still debug should any errors come up? For instance themosis displayed an error screen for an undefined variable when activating the plugin and regular wordpress did not.

**Comment by jlambe** [comment]
@keenojingco nope. Regular WordPress has its `WP_DEBUG_DISPLAY` set to `false`. This is why it doesn't show warning by default but there are still in the php log.

There is no parameters to show let's say Fatal errors only with the framework. It's all or nothing and I'm not sure there is an option in the middle that exists.
