### ISSUE TITLE
Infinite field with more than 10 rows - keys not stored correctly

### ISSUE THREAD

**Issue by CodeBrauer** [themosis/themosis#170]
Pretty easy to reproduce:

- Create 20 empty rows:<br>`for(i=0;i<20;i++) { jQuery('#themosis-infinite-main-add').trigger('click') }`
- Look at the `name` attribute of the infinite text fields:
`jQuery('.themosis-infinite-inner input').each(function() {jQuery(this).val(jQuery(this).attr('name'))});`

So the IDs are not saved in "correct" order and if I reload the settings can't be loaded correctly from wp_options

![bildschirmfoto 2017-06-14 um 10 16 38](https://user-images.githubusercontent.com/2059754/27122406-e565905a-50ea-11e7-9a8b-b7bb17985c9f.png)

Because I need to fix this asap I'm looking into this, maybe there is time for a PR.

**Comment by jlambe** [comment]
@CodeBrauer Sure. Check the `themosis/framework` repository, install the dependencies `npm install`. It's currently setup to work with web pack 1.

There is a `npm run watch` command for development and the `npm run build` command for release. Js files are stored into the `src/Themosis/_assets/js`  directory, it's Backbone based. This is clearly an issue on the rename input name attributes. Probably a regex.

I don't have more time this week to check after this but you can send a PR on the `themosis/framework` repository (not this one). Thanks for reporting this.

**Comment by CodeBrauer** [comment]
Hi @jlambe 

I found the bug! https://github.com/themosis/framework/blob/333b45f42d1a498ba9cac3aa9b04f33942d78e1e/src/Themosis/_assets/components/fields/infinite/InfiniteView.js#L305

In my current version the `+` is missing in the RegExp.

However it seems it has been already fixed - my themosis installation isn't up2date.
