### ISSUE TITLE
Error while trying to read a model

### ISSUE THREAD

**Issue by ruunup** [themosis/themosis#171]
I can not display a model inside the controller.

**Themosis: 1.3 Code:**

models/PostModel.php

`<?php

namespace Theme\Models;

class PostModel extends Model
{
    /**
     * Return a list of all published posts.
     * (not recommended)
     * 
     * @return array
     */
    public static function all()
    {
        $query = new WP_Query([
            'post_type' => 'post',
            'posts_per_page' => -1,
            'post_status' => 'publish'
        ]);

        return $query->get_posts();
    }
}`

controllers/PublicPageController.php

`<?php

  namespace Theme\Controllers;

  use Theme\Models;
  use Themosis\Route\BaseController;

  class PublicPageController extends BaseController
  {
    public function index( PostModel $post )
   {
      ...   
   }
}`

Error: **Class Theme\Controllers\PostModel does not exist**

Please, help me.

**Comment by jlambe** [comment]
You just have an error with your `use` statement.

It should be `use Theme\Models\PostModel;` This statement will import your model correctly.

Please check the [PHP Namespace](http://php.net/manual/en/language.namespaces.php) documentation for details.

**Comment by ruunup** [comment]
Thanks you! =)
