### ISSUE TITLE
Problem when using pagination with woocommerce routes

### ISSUE THREAD

**Issue by rovillesarate** [themosis/themosis#172]
Hi! I was finally able to have the shop and product page of woocommerce work with themosis. but i am having a bit of difficulty when trying to use the next page of the pagination. Having errors about the archive-product.php themosis_start_app()

Here is the exact error.
`Fatal error: Uncaught Error: Call to undefined function themosis_start_app() in /srv/users/serverpilot/apps/momentsdreamwp/htdocs/content/themes/themosis-theme/archive-product.php:2 Stack trace: #0 /srv/users/serverpilot/apps/momentsdreamwp/htdocs/cms/wp-includes/template-loader.php(74): include() #1 /srv/users/serverpilot/apps/momentsdreamwp/htdocs/cms/wp-blog-header.php(19): require_once('/srv/users/serv...') #2 /srv/users/serverpilot/apps/momentsdreamwp/htdocs/index.php(11): require('/srv/users/serv...') #3 {main} thrown in /srv/users/serverpilot/apps/momentsdreamwp/htdocs/content/themes/themosis-theme/archive-product.php on line 2`
you can view the dev site that is having the error here
`http://dev.momentsdreamed.com/shop/page/2/`

Here is what i used in the routes
`Route::any('shop', function()
{
	return view('product-listing');
});`

The shop and product single page seems to be working fine.

by the way only the next link is currently working on the dev site. clicking on the actual pagination buttons wont work yet.

Do i need to create a custom route for the paged archive?

**Comment by rovillesarate** [comment]
Finally got it working using this code.
Placed this on the archive-product.php
`<?php
$route = Route::any('shop', function()
{
    // This is calling the view stored inside app/views/shop/product.scout.php
    return view('product-listing');

});

// Output the route response content...
echo($route->run());
?>`

had to remove the themosis_start_app();

**Comment by jlambe** [comment]
You currently using a version 1.1 or 1.2 of the framework. You should definitely update to latest version. There is no more `themosis_start_app()` function in latest release 1.3.2.

But keep in mind you'll have to refactor your woo commerce integration if you intend to update to latest version.
