### ISSUE TITLE
How can I add a new class?

### ISSUE THREAD

**Issue by ruunup** [themosis/themosis#174]
I tried to do it this way, but it does not work.

config/loading.config.php

```php
'Theme\\Controllers\\' => themosis_path('theme.resources').'controllers',
'Theme\\Models\\' => themosis_path('theme.resources').'models',
'Theme\\Providers\\' => themosis_path('theme.resources').'providers',
'Theme\\Classes\\' => themosis_path('theme.resources').'classes',
```

classes/GalleryClass.php

```php
namespace Theme\Classes;
class GalleryClass{
  public function gallery( $post_id )
  {
    return true;
  }
}
```
models/LocationModel.php

```php
namespace Theme\Models;
use Theme\Classes\GalleryClass;
use \WP_Query;

class LocationModel
{
    public function __construct( GalleryClass $gallery ) 
    {
    }
}
```
**Error: Class Theme\Classes\GalleryClass does not exist**

help me, please. :(

**Comment by noxify** [comment]
Did you run `composer dump-autoload`?

**Comment by jlambe** [comment]
@ruunup This is quite strange for issue. We haven't encountered this yet. Did you try the solution from @noxify ?

**Comment by noxify** [comment]
I got messages like this so often in laravel.

Not Site if it solves the problem, but in 90% it was the solution. And since we have an autoloader here, we should ensure that's not something like an forgotten command :)
