### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by naknak12** [themosis/themosis#175]
We have a problem with multiple themosis installations. After the weekend all admin sections of wordpress are inaccessible.

Error:
**# Service Unavailable**
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

Do you know what the reason for this is?

Thanks,

**Comment by jlambe** [comment]
We haven't encountered a similar issue. If no changes were made during the weekend, looks like something else has changed from the server instead of the application.
