### ISSUE TITLE
Custom post status

### ISSUE THREAD

**Issue by KevinBatdorf** [themosis/themosis#176]
This works:
```php
$workshops = PostType::make('workshops', 'Workshops', 'Workshop')->set([
    'public'    => true,
    'supports'  => ['title', 'editor', 'thumbnail'],
    'menu_icon' => 'dashicons-carrot',
    'show_in_rest' => true,
]);
$workshops->status([
  'available', 'archived'
]);
```
This doesn't:
```php
Action::add('init', function() {
    $workshops = PostType::make('workshops', 'Workshops', 'Workshop')->set([
        'public'    => true,
        'supports'  => ['title', 'editor', 'thumbnail'],
        'menu_icon' => 'dashicons-carrot',
        'show_in_rest' => true,
    ]);
    $workshops->status([
      'available', 'archived'
    ]);
], 9);
```

I need to register it in that hook though so that it works properly with a page builder plugin I use ([BS3 Grid Builder](https://wordpress.org/plugins/bs3-grid-builder/))

**Comment by KevinBatdorf** [comment]
What happens when it's broke it that the entire "Publish section" doesn't appear. No errors otherwise

**Comment by jlambe** [comment]
@KevinBatdorf Why would you need to wrap the call into an action `init` hook as it's already done by the PostType builder class ?

What is the error triggered by your BS3 Grid Builder plugin?

**Comment by KevinBatdorf** [comment]
If it's outside that hook then it doesn't let me assign on this screen (it wont even show the "workshops" option at all actually)

![screen shot 2017-07-06 at 1 14 56 am](https://user-images.githubusercontent.com/1478421/27878509-a623199e-61e8-11e7-85ad-511ba0c5491a.png)

**Comment by jlambe** [comment]
Have you tried this for example:

```php
$workshops = PostType::make('workshops', 'Workshops', 'Workshop');
$workshops->status([
    'available', 'archived'
]);

Action::add('init', function() use ($workshops) {
    // Register the post type.
    $workshops->set([
        'public'    => true,
        'supports'  => ['title', 'editor', 'thumbnail'],
        'menu_icon' => 'dashicons-carrot',
        'show_in_rest' => true,
    ]);
], 9);
```

**Comment by KevinBatdorf** [comment]
That works well as far as I can tell, thanks!
