### ISSUE TITLE
Request object & Validation builder

### ISSUE THREAD

**Issue by RavivCohen-BWEBI** [themosis/themosis#177]
We have been developing upon the Themosis Worpress-Laravel Framework for a few days.
Two important issues that we encountered:

- Laravel Request object is not accessible via the Controller.
Instead, we used the Input object to receive the Form Parameters (using Json Ajax).
Note: when we accessed the Container the Request object was accessible like >>
`
$t1 = themosis();
$t2 = $t1->container;
$t3 = $t2->request->request;
$t4 = $t3->all();
`

- Laravel Validator is not accessible via the Controller.
Using the Themosis Validation Builder is OK but has some problems >>
The validation_num method fails on zero values ($data = 0 || $data = "0").
There is no use of The MessageBag Class so we had to create our own messages matching the validation rules.

**Comment by jlambe** [comment]
We're aware of those issues. Not all illuminate packages have been implemented into the project yet.

For release 1.4, a form/request/field/validation refactoring is planned but no release date to confirm. You can still install the Laravel Validator into your project and configure it.

Regarding the Request object, a `Request` facade is normally available so you don't have to use the `Input` one.

**Comment by RavivCohen-BWEBI** [comment]
We have tried several ways of using Request Facade 
and the 
`$request->method()`
output, each time printed out a GET method and not the POST as was expected.
and the Request attributes where empty.
The only way to access the Request parameters was through the Input Object.
Again, using Ajax of data type JSON (maybe related).

Thanks for the Reply

**Comment by jlambe** [comment]
Indeed we have an issue here then. Can you please open an issue in the [themosis/framework](https://github.com/themosis/framework) repository regarding the Request Facade and provide details of your expected use of the class.

I'll take a look at this. I'm closing this one. For future issues met, always open them on the [themosis/framework](https://github.com/themosis/framework) repository.

Thanks.

**Comment by jlambe** [comment]
@rumur this is not handled. But in your case, you could level up your data by doing this:
```php
$data = Validator::multiple(Input::get('plans'), [
    'product' => ['required', 'num'],
    ...
]);
```

**Comment by rumur** [comment]
@jlambe Thanks!

I assume if we follow that logic and I have nested inputs more than `plans` e.g. plus `campaigns` in this case I need to divide them and validate separately.

`$plans = Validator::multiple(Input::get('plans'), [
    'product' => ['required', 'num'],
    ...
]);`

`$campaigns = Validator::multiple(Input::get('campaigns'), [
    'title' => ['required', 'textfield'],
    ...
]);`

**Comment by jlambe** [comment]
@rumur yes. Next release is implementing the `illuminate/validation` package. Not sure if nested data is handled but it will streamline development.

**Comment by rumur** [comment]
@jlambe It'd be great.

Yes, `illuminate/validation` package is supported nested rules.

Some part of the package.

```
// Illuminate\Validation\Validator
/**
     * Get the explicit keys from an attribute flattened with dot notation.
     *
     * E.g. 'foo.1.bar.spark.baz' -> [1, 'spark'] for 'foo.*.bar.*.baz'
     *
     * @param  string  $attribute
     * @return array
     */
    protected function getExplicitKeys($attribute)
    {
        $pattern = str_replace('\*', '([^\.]+)', preg_quote($this->getPrimaryAttribute($attribute), '/'));

        if (preg_match('/^'.$pattern.'/', $attribute, $keys)) {
            array_shift($keys);

            return $keys;
        }

        return [];
    }
```

**Comment by jlambe** [comment]
Well this is finally coming on the next version ;)
