### ISSUE TITLE
Cannot route two separate post types if they share the same custom re-write slug

### ISSUE THREAD

**Issue by lougreenwood** [themosis/themosis#179]
I'm using Pods (https://pods.io) to manage my custom posts and taxonomies.

I have 2 entities I need to route to, one post and one taxonomy.

The Post and Taxonomy both share the same 'custom re-write slug': `/my-slug/...` e.g:

* Post
    * `/my-slug/some-post`
* Taxonomy
    * `/my-slug/some-term`

However, it seems that I can't route to these using Themosis. Im using these route directives:

`Route::get('tax', [ 'my-custom-taxo', 'uses' => 'MyTaxoController@actionViewSingle' ]);
Route::get('singular', [ 'my-custom-post', 'uses' => 'MyTaxoController@actionViewSingle' ]);
`

The goal is that if a user visits either the post or the taxo, the same controller action manages displaying the same page and the URL slug is identical.

The problem is that when the taxo and post (or any 2 routes pointing to different WP entities) share the same slug, any additional route directives is ignored.

If I change the taxo slug to some unique value, the post works - etc.

**Comment by jlambe** [comment]
I won't provide anymore WordPress support on issues. It seems you have the answer regarding the conflict name btw.

This is not related to the framework but a WordPress permalink conflict.
