### ISSUE TITLE
Localize asset

### ISSUE THREAD

**Issue by Benjaminsson** [themosis/themosis#182]
I'm not getting this to work properly. In resources/admin/enqueue.php (is this the right place?) i have this.

```
$asset = Asset::add( 'my-scripts', 'js/main.js', ['jquery'], '1.0', true );
$asset->localize( 'translationStrings', [ 'noReviews' => __( 'No reviews yet', THEME_TEXTDOMAIN ) ] );
```
That always outputs the english string. Even on the swedish version. If i do the non character saving version it works as expected.
```
function register_my_scripts() {
    wp_register_script( 'my-scripts', 'js/main.js' );
    $translation_array = array(
        'noReviews' => __( 'No reviews yet', THEME_TEXTDOMAIN )
    );
    wp_localize_script( 'my-scripts', 'translationStrings', $translation_array );
    wp_enqueue_script( 'my-scripts' );
}
add_action('wp_enqueue_scripts', 'register_my_scripts');
```
I'm using WPML, Themosis 1.3.2 and Wordpress 4.8.1.

**Comment by jlambe** [comment]
Indeed that's weird, it should normally work. This will need more tests.

**Comment by jlambe** [comment]
Can you also move your issue on the `themosis/framework` repository so we can look at it? Thanks.

**Comment by Benjaminsson** [comment]
Sure! [Moved here](https://github.com/themosis/framework/issues/449)!
