### ISSUE TITLE
Add MetaBox on Post ID

### ISSUE THREAD

**Issue by tr0yka** [themosis/themosis#183]
Need add MetaBox on Page or Post ID only

My variant:

htdocs/content/mu-plugins/themosis-framework/src/Themosis/Metabox/MetaboxBuilder.php

[pastebin.com](https://pastebin.com/bzQKv98M)

**Comment by jlambe** [comment]
You can do this to render a metabox for a specific post/page ID:

```php
if (themosis_is_post(2)) {
    Metabox::make('Title', 'page')->set();
}
```

The above code will create a metabox on a page with an ID of `2`.
