### ISSUE TITLE
Creating custom pages with settings

### ISSUE THREAD

**Issue by yamilelias** [themosis/themosis#184]
I was reading the [page docs](https://framework.themosis.com/docs/1.3/page/) and I saw that there are two ways of creating a page with Themosis: Custom and with Settings. The issue, is when I try to do both. For example, I want to add a text before the settings or an extra tab just with a button and an image there, but I'm not able to do it.

For example, with this code:
```php
$page = Page::make('configuration', 'Configuration')->set([
       'capability' => 'manage_options',
       'icon'       => 'custom/url/to/icon',
       'position'   => 2,
       'tabs'       => true,
       'menu'       => __("Administrator")
]);

/*
* Create the homepage banner administrator section
*/
$sections[] = Section::make('homepage-banner', 'Homepage Banner');
$settings['homepage-banner'] = [
       Field::infinite('banner-media',[
            Field::media('image-banner-brand',[
                'title'=>'Image Brand',
                'type'=>'image'
            ]),
            Field::media('image-banner-brand-mobile',[
                'title'=>'Mobile Image Brand',
                'type'=>'image'
            ]),
                Field::text('banner-text-line-1',['title'=>'Banner text line 1']),
                Field::text('banner-text-line-2',['title'=>'Banner text line 2']),
                Field::text('banner-text-line-3',['title'=>'Banner text line 3']),
        ],['title'=>'Banner','limit'=>4])
];

// Add the created section.
$page->addSections($sections);

// Add the created settings.
$page->addSettings($settings);
```

This code is working and display everything correctly without any problem. But, for example, if I add a view at the creation of the page:

```php
$view = View::make('admin.main');
$page = Page::make('configuration', 'Configuration',null, $view)->set([
       'capability' => 'manage_options',
       'icon'       => 'custom/url/to/icon',
       'position'   => 2,
       'tabs'       => true,
       'menu'       => __("Administrator")
]);
```

Then, the view completely overrides the section and settings. There is a way where both can coexist in the view? That I could pass the section as a parameter for example, and then insert it on the view? Is not clear if this is even possible in the docs. Thanks by the way for the time.

**Comment by jlambe** [comment]
One solution is to copy over the core page view defined into the framework into your custom one and then add your custom html or any code into it. That way, it will behave as the default one with extra.

Next version will digg a little more on admin pages in order to provide a CRUB mechanism.
