### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by iameronmosele** [themosis/themosis#185]
![screenshot from 2017-09-17 21-12-19](https://user-images.githubusercontent.com/8146143/30524523-460fe39a-9bed-11e7-95b8-0dd299a34268.png)
Wordpress installation seems to fail because of translation file

**Comment by jlambe** [comment]
Not an issue from the framework. WordPress issue. If you can't complete the installation process because WordPress is failing, turn off error report from your `config/environments/local.php` and set `THEMOSIS_ERROR` to `false`. Install again and turn error report on right after.
