### ISSUE TITLE
Call to undefined function media_handle_sideload()

### ISSUE THREAD

**Issue by lougreenwood** [themosis/themosis#187]
I have a controller action which is triggered on POST, it looks like this:

```
Route::post( SOME_URL_CONST . '/{id?}', function( ?string $id = null ){
	$controller = new \Theme\Controllers\SomeController();
	$controller->actionSaveSomeThing( $id, $_POST );
});
```

It seems that methods triggered by this controller can't access some WP methods, for example, `get_term()` works fine, but trying to use `media_handle_upload()` returns the following error:

```
Call to undefined function media_handle_sideload()
```

Seems I also get the same error from other media methods, such as `media_handle_upload()`

I'm not even sure if this is a Themosis issue or WP, any pointers or help to debug this would be greatly appreciated. 👍

**Comment by jlambe** [comment]
Try to look where the function is defined in WordPress. It's possible that the file containing the function is simply not included in the process in the front-end as it is mainly an admin utility. You will have to include/require the file before going further.

Also any reason why not using this syntax for your controller ?
```php
Route::post(SOME_URL_CONST.'/{id?}', ['uses' => 'SomeController@actionSaveSomething']);
```
