### ISSUE TITLE
Model class: Getting Using $this when not in object context

### ISSUE THREAD

**Issue by AMO-MGTSYS** [themosis/themosis#188]
Hi and thank you for this grat framework.

I've defined a model class like provided in the Books.php class found in the plugin example Book-store.

I'm trying to call it : Som::find(['posts_per_page' => -1])->select()->get(); I get Getting Using $this when not in object context.

 public function find(array $query)
    {
        $query = wp_parse_args($query, [
            'post_type' => $this->name,
        ]);
        $this->items = $this->query->query($query);
        return $this;
    }

I'm using PHP7. Can you help me please

**Comment by jlambe** [comment]
You can't call your model method like so because you haven't defined a `facade` for it. Based on your code, you'll have to call your model like so:
```php
$model = new Som();
$model->find(['posts_per_page' => -1]);
```
Hope this help.

**Comment by AMO-MGTSYS** [comment]
Thank you Julien.

Tried adding 
use \WP_Query;
$test = new Som(new \WP_Query());
$select = $test->find(['posts_per_page' => -1])->select()->get();
tp($test->find(['posts_per_page' => -1])->get());

No Fatal Errors or Exceptions.

Now iwould want to go deep defining a Facade as used in the plugin Books-Manager Example.

Do i have to add also a Model Provider?

**Comment by AMO-MGTSYS** [comment]
Just a precision i'm trying to make it work in a plugin. No interaction neaded with the theme.
