### ISSUE TITLE
Simple theme supports ignored

### ISSUE THREAD

**Issue by Yokann** [themosis/themosis#189]
Hi,

In the  `Config\Support` class, `add_theme_support` is wrapped.

When you add some supports which don't need args like `title-tag`,  `add_theme_support` is called this way

```
add_theme_support('title-tag', [])
``` 

So Wordpress refuse to add the support because the empty array

I don't think wrapping add_theme_support is a good idea in this case.

**Comment by jlambe** [comment]
From our latest project, the `title-tag` is by default enabled without any arguments and WordPress is correctly supporting it.

Can you provide more information and context on your application and why the `title-tag` support might not work in your case even with an empty array ?

**Comment by Yokann** [comment]
I said `title-tag` as an example. 

In my case,  i add `woocommerce` in  `support.config.php`, and
