### ISSUE TITLE
Issue when migrating severs

### ISSUE THREAD

**Issue by jepsonrob** [themosis/themosis#192]
I'm getting this error when migrating a theme from one server to another. This is the error that comes up on the local MAMP install - it is almost identical to the error on the server. 

The .env files have been updated to reflect the new locations, but I'm struggling to get this to work. Any ideas?

> Unhandled Exception  Message:

> include(): Failed opening '.:/Applications/MAMP/bin/php/php7.1.8/lib/php' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.1.8/lib/php')

> Location: /Users/Admin/Documents/MAMP/alnwickFix/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/PhpEngine.php` on line 36

**Comment by jlambe** [comment]
Not sure. Is the `storage/views` directory defined in your project?
