### ISSUE TITLE
"tailor" page builder plugin not working

### ISSUE THREAD

**Issue by manniR** [themosis/themosis#193]
hi - i have the full themosis stack installed - v 1.3.2 -

we want to use a wordpress pagebuilder plugin called tailor :  https://wordpress.org/plugins/tailor/
its a pagebuilder plugin - it adds a button above the wysiwyg editor 'tailor this' - normally when its clicked the plugins launches a custom preview with elements to drag and drop but its not working - its hard to describe - has anyone worked with this plugin and themosis before? 

javascript console error: 
```js
The canvas does not exist in the page.  This could be caused by a plugin or theme conflict.
```

route settings
```php
Route::get('page', function ($post){
	return view('page', ['entry' => $post]);
});

// in page.twig the content of the wysiwyg editor gets outputted like this
// {{entry.post_content | raw | nl2br }} 

```
thx for any help ;)manni

**Comment by jlambe** [comment]
Sorry never worked with it. Routes are not linked with WordPress admin files. So if it adds features on a post edit screen, the framework is not modifying core behavior.
