### ISSUE TITLE
Object of class Closure could not be converted to string in \cms\wp-includes\class-wp-query.php on line 3726

### ISSUE THREAD

**Issue by pckosmonaft** [themosis/themosis#194]
Hi,

I just installed a new plugin called: "Viral Quiz".

Every single page except the home page (is working fine) and custom urls (are completely broken) are getting the following error
"_Object of class Closure could not be converted to string_" 
in
\cms\wp-includes\class-wp-query.php on line 3726

this is how the line getting the error look like: 
**$page = array_map( 'strval', (array) $page );**

Any idea what is wrong?

After short investigation I was able to fix the custom urls.
I changed in routes.php the following from 
`Route::get('customUrl', array('the-magazine', 'uses' => 'PageController@customPage'));`
to
`Route::get('customUrl', 'PageController@customPage');`

However the scout.templates are still returning the error.
Here is example of the default scout.template:
`Route::get('template', array('default-template', 'uses' => 'PageController@page'));`

I'm using Themosis 1.1.3

**Comment by jlambe** [comment]
Sounds like a php error from the plugin. Set the error reporting to false on the configuration to avoid the messages or you can also signal the issue to the plugin author.
