### ISSUE TITLE
Pagination links in eloquent query

### ISSUE THREAD

**Issue by iameronmosele** [themosis/themosis#195]
Hello, can someone help i am trying to call $pagination->links() method in my view file but it seems not to work at all spitting out a consistent error even when i installed corcel in themosis to test.

![screenshot from 2017-12-14 15-27-10](https://user-images.githubusercontent.com/8146143/33997059-745907a0-e0e3-11e7-9125-2e19df0f75b4.png)

**Comment by kmligue** [comment]
@iameronmosele have you found a solution? i'm having the same error.
