### ISSUE TITLE
"This site can’t be reached" on windows after setting up the enviornment

### ISSUE THREAD

**Issue by DhaduBum** [themosis/themosis#199]
I did try the answered you gave here 
https://stackoverflow.com/questions/35314640/themosis-doesnt-run-on-localhost

In the root file .env.local I've set:

return [
    DB_NAME = "vivonslagrasse"
DB_USER = "root"
DB_PASSWORD = ""
DB_HOST = "localhost"
WP_HOME = "http://vivonslagrass.dev"
WP_SITEURL = "http://vivonslagrass.dev/cms"
];

For defining enviornment.php
/*----------------------------------------------------*/
// Define your environments
/*----------------------------------------------------*/
return [
    'local'         => 'CBT',
    'staging'       => ''
];

**Comment by jlambe** [comment]
@DhaduBum Are you working on Google Chrome ?

**Comment by DhaduBum** [comment]
Yes I am. I have started using MAMP for windows and I have successfully set up the environment.

**Comment by DhaduBum** [comment]
Thanks julien for the quick response :)

**Comment by jlambe** [comment]
@DhaduBum I'm not sure but it might due to Chrome limitations regarding  `.dev` tld. It forces you to the `https` version while when working under other browsers, it might work as expected. If that's your issue, try to work with `.test` tld for local development.

**Comment by DhaduBum** [comment]
I changed the host to .deve and it did work.
I guess you are right. Although I did try to force it through hosts file. I could not understand. Since its working now with MAMP.  Kudos to MAMP :)
