### ISSUE TITLE
Guidelines for working with woocommerce with Themosis version 1.3

### ISSUE THREAD

**Issue by DhaduBum** [themosis/themosis#200]
I have been reading this thread 
https://github.com/themosis/themosis/issues/36
Can you guide me how to integrate woocommerce plugin with the latest changes ?

**Comment by DhaduBum** [comment]
Hi Julien, 
I have integrated with placing the single-product.php file in the root folder along with archive-product.php.
I want to route the to be in shop.product. And I dont want to rely on the default template. How can I make custom controller to call woocommerce functions and to call WP_QUERY to display the products there. I tried through making the model just like you have made for posts but that doesnt works.

**Comment by jordangidoin** [comment]
Hello, I'm in the same situation.
I wish to integrate woocomerce into themosis, but the woocommerce templates are not executed.
How to do ?

Thank you for your advice

**Comment by mediaboost** [comment]
Hello
Please, do you have any solution ?

**Comment by jlambe** [comment]
@mediaboost @jordangidoin @DhaduBum Can you provide a detailed description of your issues? What kind of errors do you get on screen? Which version of the framework are you using ? Thanks.

**Comment by mediaboost** [comment]
Bonjour 
je suis en version 1.3.1
j'ai installé woocommerce avec composer
celui -ci se trouve dans le dossier plugin

j'ai copié single-product dans le dossier view du theme themosis
j'ai ajouté dans routes.php

```
add_filter('themosisRouteConditions', function($conds)
{
    $conds['product'] = 'is_product';
    return $conds;
});
Route::any('product', function()
{
    return View::make('single-product');
});
```

l'erreur est qu'il demande un header & sidebar & footer ...
j'ai remplacé 

get_header( 'shop' );  par wp_head();
get_footer( 'shop' ); par wp_footer();

il me manque le sidebar ....

est ce que c'est la bonne méthode ??

**Comment by mediaboost** [comment]
@jlambe merci de votre réponse ...  

1 - Vous me parlez de mise à jour de woocommerce mais j'ai déplacé le dossier template dans le dossier content/plugins/woocommerce vers themes/themosis-theme/resources/views afin de me laisser toute liberté de coder façon Laravel ... est ce que cela est bon ou faut'il tout recoder (panier etc ...) ?

2 - il y a bcp de fichiers dans le template woocommerce, est ce qu'il y a une nomenclature définie pour toutes les routes ?
exemple is_cart ...

```
`Route::any('cart', function()
{
    return View::make('shop.cart ???? ');
});`
```

**Comment by mediaboost** [comment]
@jlambe  désolé ....
est ce que je suis obligé de déplacé le template de base woocommerce dans le dossier view de themesis pour que cela fonctionne ? 
et si non (ce serait parfait pour les mises à jour de woo) comment mettre les bonnes routes vers le dossier de woocommerce ?

**Comment by jlambe** [comment]
WordPress n'a aucun mécanisme pour gérer des templates depuis un plugin. Il faut comprendre que WooCommerce a créé son propre système pour charger des templates manquantes au sein d'un thème. De manière générale, il faut regarder le code source de WooCommerce pour les détails de leur mécanisme.

Par expérience, il n'est pas nécessaire de déplacer les templates de woocommerce. Et si vous souhaitez le faire pour personnaliser leur sortie (affichage), il faut suivre les règles de WooCommerce => donc les déplacer à la racine du thème (et non à la racine du dossier `resources/views`.

Pour les routes, il n'y a rien de pré-défini. Dans le cas où vous définissez des routes WooCommerce, celles-ci ne peuvent pas correspondre à l'un de leur template. Mais vous pouvez retourner une vue qui pourrait l'inclure. Où si vous avez déplacez les templates de WooCommerce dans votre thème, vous pouvez depuis chaque template, inclure vos vues.

**Comment by mediaboost** [comment]
Bonjour @jlambe et merci pour les réponses

J'ai effectivement déplacé (dans un premier temps pour tester)  tout le template woocommerce à la racine du dossier themosis
je n'ai défini aucune route ... seul la page single-product.php fonctionne, tout ce qui est cart, rubrique etc les routes ne fonctionnent pas automatiquement ...

est ce normal ? merci

**Comment by jlambe** [comment]
I'm going to provide a WooCommerce guide on the documentation website for the framework 2.0 release. Thank you for patience and stay tuned.

**Comment by rajogit** [comment]
Merci beaucoup @jlambe , on attends avec impatience la sortie de la **version 2** de **themosis** et la documentation complet pour l'implémentation de **Woocommerce** qui est très important.
Aussi, je viens de tester **Wordpress 5** et **Gutenberg** ne fonctionne pas sur themosis 1.3, j'ai une page blanche dans le Backoffice des posts et des pages. Ce n'est pas prise en charge ou c'est un bug ?

A bientôt,

**Comment by rajogit** [comment]
Hello @jlambe 
Maintenant que la version 2 est sortie, j'aimerai savoir comment peut on customiser les **templates part** de woocommerce avec Themosis ?
J'ai un exemple de code comme ceci : 

```
Filter::add('wc_get_template', function ($located, $template_name, $args = [], $template_path = '', $default_path = '') {

	$shop_tmp = null;
	$view = View::make('shop.rendered-view');

	/**
	 * Listing product template
	 */
	if ('loop/loop-start.php' === $template_name) {
		$shop_tmp = 'shop.loop.loop-start';
	}
        if (!empty($shop_tmp)) {
		$GLOBALS['shop_account_tmp'] = $shop_tmp;
		$located = $view->getPath();
	}

	return $located;
});

```
Et dans le view "'shop.rendered-view'" on a le code suivant pour essayer de compiler blade : 


```
<?php

use Illuminate\Support\Facades\View;

global $product, $post, $current_user;


echo View::make($GLOBALS['shop_account_tmp'])->render();
?>
```


Blade fonctionne, mais les variables de woocommerce ne sont pas transmis avec le **View::make($GLOBALS['shop_account_tmp'])->render()** 

Sachant que si j'utilise directement le path **$GLOBALS['shop_account_tmp']** dans le hook **wc_get_template**, les variables woocommerce fonctionne mais les syntaxes blade ne sont pas interpreté 

Comment peut on faire pour résoudre ce problème ? 

Merci

**Comment by jlambe** [comment]
@rajogit Le framework désactive le gestionnaire de templates de WooCommerce par défaut afin de pouvoir utiliser le système de routing pour cibler les templates `shop`, `product`, ...

Concernant les "sous-templates" de WooCommerce, je n'ai pas le code devant les yeux mais ce que j'ai fait pour personnaliser les éléments est de regarder soit les "actions et/ou filtres" individuels soit le nom de la fonction utilisée pour retourner le template et la remplacer. Si la fonction existe en premier au niveau de ton thème, celle-ci n'est pas reprise au niveau du plugin si je ne me trompe pas.
