### ISSUE TITLE
Password protected page

### ISSUE THREAD

**Issue by Kosmonaft** [themosis/themosis#203]
I'm using Themosis and the page which I created is set to be "Password protected".
Unfortunately all the content is visible and is not asking at all for password.

From what I read to enable the password protecting every template need to have the default wordpress function for content "the_content()"
However with Themosis we are having completely different structure of the template.

How we can use the Password protected feature of Wordpress with Themosis?

**Comment by jlambe** [comment]
Yes you can use them. Indeed you have to call the core `the_content()` function but as well wrap it with the WordPress loop.
