### ISSUE TITLE
Themosis routes break with Laravel 5.6 core

### ISSUE THREAD

**Issue by mpemburn** [themosis/themosis#204]
We recently upgraded the Laravel components to 5.6, and discovered all Themosis routing stopped working.  The issue came to light when we began seeing "preg_match(): Unknown modifier '#'" Exceptions in the WP->parse_request() method (class_wp.php line 219).  When rolled back to 5.5, the issue went away.  Has anyone else experienced this and found a workaround?  We're going to hold at 5.5 as long as we can, but it would be great there was a real fix.

**Comment by jlambe** [comment]
Hello @mpemburn,
we haven't encountered an issue yet but could you provide the full stack error message regarding the error as well as more information regarding your installation (WordPress version, Themosis framework version 1.3.2 ?, plugins loaded, php version, ...) ?

In your message, it looks like we capture an error from WordPress directly and not the routing.

Thanks for reporting this.

**Comment by mpemburn** [comment]
Hi Julien,

Thanks for getting back to me.  The WordPress version is 4.9.4, and we're using Themosis 1.3.2.  We run our dev environments on Laravel valet using nginx and PHP 7.1.12, and our staging environment is similar (we're not in production yet).  We employ several dozen plugins, and I can compile a list if you think it's really relevant.

I think you're right that this appears to be an interaction directly between Laravel and WordPress, but since that's kind of the bargain we strike in using Themosis (which is frankly a miraculous product, and we thank you!) we're always going have to depend on their being able to play nice together.  When I get a chance, I will do a clean install of Themosis with Laravel 5.6 and see if I can replicate the problem.

The stack trace from Sentry.io on our staging environment is below.

Thanks,
Mark

`ErrorException: preg_match(): Unknown modifier '#'
#6 wp/wp-includes/class-wp.php(219): handleError
#5 /srv/www/staging-refactor.laruta.io/releases/20180215181807/vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): preg_match
#4 wp/wp-includes/class-wp.php(219): parse_request
#3 wp/wp-includes/class-wp.php(713): main
#2 wp/wp-includes/functions.php(960): wp
#1 wp/wp-blog-header.php(16): require
#0 index.php(11): null
`

**Comment by firhatsungkar** [comment]
I have the same problem, after updating Permalink Setting to a custom structure:
```http://site.domain/sample-post/``` 
Is there any way to solve it?

**Comment by gonzunigad** [comment]
It is happending to us too...

![captura de pantalla 2018-03-06 a las 12 26 25](https://user-images.githubusercontent.com/1103494/37042649-a36288d8-213d-11e8-9b62-4b05157fc547.png)

**Comment by iwillhappy1314** [comment]
happened to us too...

**Comment by jlambe** [comment]
[A fix is on the way](https://github.com/themosis/framework/issues/482) :)

**Comment by jlambe** [comment]
Fixed. Update to version `1.3.3` of the framework.
