### ISSUE TITLE
Best option to schedule tasks in Themosis

### ISSUE THREAD

**Issue by AMO-MGTSYS** [themosis/themosis#206]
Hello,
What is the best option available in themosis to schedule a task (save data in a db every hour)? 
1) wp-cron 
2) laravel Task Scheduling (does this work with Themosis?)

**Comment by jlambe** [comment]
WP-Cron is based on front-end request done on your site so it's not a real cron job.
You can setup a cron job and run any script, that will make it.
Regarding the Laravel Task Scheduling, we haven't used it but you can definitely write your own PHP worker that executes some commands every hour.

**Comment by AMO-MGTSYS** [comment]
Thank you. Appreciate your advice.
