### ISSUE TITLE
The Events Calendar and Themosis

### ISSUE THREAD

**Issue by akabuda050** [themosis/themosis#207]
HI team,

There is an issue when we try to use The Events Calendar(https://theeventscalendar.com/) plugin.
The issue is - when I try to request page by slug(provided by the plugin), for example, **https://www.site.com/events** then I get a white screen.
Plugins URLs are registered by default WordPress Rewrite API.

Is there someone who can help or have any ideas?

**Comment by jlambe** [comment]
You need to specify a route for the default events post type archive permalink. Something like this should work:
```php
Route::any('postTypeArchive', 'tribe_events', function () {
     return 'Events';
});

> Perhaps check their custom post type slug just to be sure.
```

**Comment by akabuda050** [comment]
Hi @jlambe 

Thanks for quick response.

Could you please clarify what should happen when we return string "return 'Events';". We can return any strings here. Am I right?

**Comment by akabuda050** [comment]
Additional question: 
What is the cause of this behavior?

**Comment by jlambe** [comment]
This is not traditional WordPress development. If a route is missing for a specific content, you'll always get a blank page or if you have at least defined a `404` route, then that 404 content will be displayed instead.

You have to return a string and it can be any string. This is a short sample. Generally you want to return a view with your agenda/archive custom design.

See the docs for more informations regarding routing: https://framework.themosis.com/docs/1.3/routing/

**Comment by akabuda050** [comment]
Hmm. I see :)

However, I don't need custom templates. I want the plugin functionality from the box. Without any customization.

**Comment by jlambe** [comment]
Then you need to define a default template on the index.php file of your theme or return a view based on the defined above route which uses a shared template code. Your template still have to provide excepected tags and php functions calls in order to make it work with the events calendar plugin (WordPress loop, ...).

**Comment by akabuda050** [comment]
So if I understand correctly the plugin templates won't work without creating templates in my theme?

**Comment by jlambe** [comment]
Yes because the provided theme is empty by default. There are no WordPress loops pre-defined, so the plugin is not able to hook on anything to render its stuff.

**Comment by akabuda050** [comment]
Seems working!
Thank you!
