### ISSUE TITLE
Mu-plugins autoloader

### ISSUE THREAD

**Issue by jlambe** [themosis/themosis#209]
Component responsible of autoloading any plugins installed into the `mu-plugins` directory.

The component always load the framework first and add to the stack other plugins.
We also want to verify the support for the composer installers type of `wordpress-muplugin` under the main `composer.json` file.

- [x] Mu-plugins loader
- [x] composer.json support for `wordpress-muplugin`

**Comment by guicara** [comment]
I'm very interested in this new feature!
I hope it will be released soon.
