### ISSUE TITLE
Best Webpack Workflow

### ISSUE THREAD

**Issue by ben182** [themosis/themosis#212]
Hey,
first of all, really nice framework. Thats what I was looking for. It is like Wordpress + Laravel <3
Okay so my question is what is the best practise for compiling theme or plugin assets?
I really like Laravel Mix. What is your opinion on that?

Cheers Ben

**Comment by jlambe** [comment]
@ben182 we recently used Laravel Mix directly into the theme and plugin development. You can definitely use it for your projects ;)
