### ISSUE TITLE
How to define route, belongs to admin

### ISSUE THREAD

**Issue by Aletz-Arce** [themosis/themosis#214]
Hi,
 Thanks for really awesome framework. I have a question, about to define route belongs to "wp-admin" path. 
IE "http://127.0.0.1:8080/cms/wp-admin/amazing-stuff/"

Can help me?
Thanks a lot

**Comment by jlambe** [comment]
hi,
unfortunately, there is no routing for the admin side as WordPress admin does not follow a front controller pattern. If you need to create custom pages, there is the `Page` helper class: https://framework.themosis.com/docs/1.3/page/

**Comment by Aletz-Arce** [comment]
@jlambe Thanks a lot for you quick reply!
