### ISSUE TITLE
It's possible integrate artisan CLI command

### ISSUE THREAD

**Issue by Aletz-Arce** [themosis/themosis#216]
Hi @jlambe 
It's possible integrate artisan CLI command from lavarel ?. 
This wtih finality to create models and migrations inside Themosis framework.

Thanks.

**Comment by jlambe** [comment]
No not yet but a CLI tool will come on next version. Scaffolding commands are planned but if you need some cli utilities, you can already implement the Symfony Console package which [artisan](https://symfony.com/doc/current/components/console.html) is based on.
