### ISSUE TITLE
How to use the paginate helper?

### ISSUE THREAD

**Issue by 411x** [themosis/themosis#217]
Hello,

Thank you for this framework. I was looking a clean way to code with wordpress. This is perfect but I have a lot to learn.

I have a custom post type "News" and I have a page where I list the last articles.
I'm using this query

```
                @query(['post_type' => 'news', 'posts_per_page' => 1])

                    <div class="single-news-post">
                        <div class="post-title">
                            <h2>{{ Loop::title() }}</h2>
                        </div>
                        <div class="date">
                            <p>Publié par <span>{{ Loop::author() }}</span>, le <span>{{ get_post_time('j F Y', true, Loop::ID()) }}</span></p>
                        </div>
                            <p>{!! wp_trim_words(Loop::content(), 20) !!}</p>
                        <a href="{{ Loop::link() }}" class="read-more">Lire la suite</a>
                    </div>

                @endquery
````
It works well but I can't figure how to have a pagination. I tried Loop::paginate() or nextPage(), inside or outside the loop and got no return, it's empty. I think I'm missing something but I don't find any ressource to help me.

Any idea?

**Comment by jlambe** [comment]
You can use [paginate_links()](https://developer.wordpress.org/reference/functions/paginate_links/) function from WordPress to get a pagination set.
