### ISSUE TITLE
Is this guy taking a wee?

### ISSUE THREAD

**Issue by garygreen** [themosis/themosis#220]
On the homepage you have a picture of a person apparently weeing on Belgium. Now I know they pay the highest amount of tax in Europe but that's no reason to be uncivilized 🤣 maybe another image would give a better impression?

![image](https://user-images.githubusercontent.com/1702638/40112832-37a677b8-58ff-11e8-9fd7-53e0633573fb.png)

**Comment by kristjankoppel** [comment]
@garygreen This is no ordinary illustration :) [https://en.wikipedia.org/wiki/Manneken_Pis](https://en.wikipedia.org/wiki/Manneken_Pis)

**Comment by jlambe** [comment]
@garygreen We juste have a large "sense of humour" 😆
