### ISSUE TITLE
Moving themosis to another server

### ISSUE THREAD

**Issue by jeroenrosendaal** [themosis/themosis#222]
Hello,

i'm having currently some trouble with my themosis project. We have moved our website to another server, but our domain stayed the same.

Know we getting this error / notification in the browser:

**ERR_TOO_MANY_REDIRECTS**

We have changed the hostname in de environments.php file.

Does somebody know why this is happening?

Thanks in advance.
Jeroen Rosendaal

**Comment by jlambe** [comment]
Not sure about this. It's a default behaviour. It might be a server issue, a plugin issue or a custom code one.
