### ISSUE TITLE
Adding Themosis Fields to existing forms/pages.

### ISSUE THREAD

**Issue by johnveeuminga** [themosis/themosis#223]
Say, in WooCommerce add and edit product category forms, is there a way where we can leverage Themosis' Field facade to add fields here?

**Comment by jlambe** [comment]
Well yes, it is do-able. You can instantiate a `Field` class and in order to retrieve its html output, you need to call its `metabox()` method like so:
```php
$field = Field::text('name');
echo $field->metabox();
```

**Comment by johnveeuminga** [comment]
Thank you very much. Achievable with the Form `Form` class too. Just for anybody's reference, I hooked up this with the `{taxonomy_name}_add_form_fields` and the `{taxonomy_name}_edit_form_fields` actions. So it's like `Action::add('product_cat_add_form_fields', array($this, 'func_name');`
