### ISSUE TITLE
Allow changing button text for media field

### ISSUE THREAD

**Issue by twosg** [themosis/themosis#224]
At first: Congratulations for this awesome work! Themosis should go core :)

I have a little suggestion for the next release:

Allow changing the Button text when adding media fields:

```
$manufacturers = Taxonomy::make('manufacturers', [$customPostType->get('name')], 'Manufacturers', 'Manufacturer')->set([
	'public'             => true,
	'show_in_nav_menus'  => false,
	'hierarchical'       => false,
	'show_tagcloud'      => false
])->addFields([
	Field::text('website'),
	Field::media('logo', [
		'title' => 'Manufacturer Logo',
		'button' => 'Choose Logo',
		'type'  => 'image'
	]),
]);
```

Currently the text is "Add" which somehow was translated to "OK" in my installation. I was confused and thought the field would not render, because the button appeared just before the save button for the tax.

**Comment by jlambe** [comment]
@twosg Excellent idea! Can I just ask to close this issue and re-open it into the [themosis/framework](https://github.com/themosis/framework/issues) repository instead so I can track it for next release.

Thanks.
