### ISSUE TITLE
Integrating wordpress with themosis

### ISSUE THREAD

**Issue by maryam21** [themosis/themosis#225]
I have followed all the steps in the docs https://framework.themosis.com/docs/1.3/environment/ to install themosis and then installed wordpress and put the generated files inside `htdocs/cms/`, but it does not seem to work properly as I am not getting the themosis-theme activated upon installation, here's my code along with the steps I followed in the `Readme` file https://github.com/maryam21/app/. 

I would like some guidelines if possible or if someone could help me pinpoint what I am doing wrong.

**Comment by maryam21** [comment]
Thanks for the quick reply. The problem is that when I go to `url/cms/wp-admin/themes.php` the `themosis-theme`(or app) doesn't exist only the default themes that come with wordpress. I have also tried the installation without renaming the theme but the same result the theme is not detected.

**Comment by maryam21** [comment]
Hi @jlambe my web server is using `htdocs/cms/wp-config.php` to connect to the database, and I guess it should be using `htdocs/wp-config.php` instead for that right? could you also please answer my previous question, was my question not clear enough or maybe there's something I am missing?

**Comment by jlambe** [comment]
Indeed, the server must point to the `htdocs` directory and not `htdocs/cms`. So as you found, the configuration file that should be used is the one from `htdocs/wp-config.php`, same directory where `index.php` is defined and what your server should target (not the /cms one).

This should explain why your `app` theme is not available in the list.

**Comment by jlambe** [comment]
I'm not a server expert but perhaps this thread might help you: https://stackoverflow.com/questions/35314640/themosis-doesnt-run-on-localhost

**Comment by maryam21** [comment]
Thanks @jlambe , I have gone through that thread before and I followed the same described steps for my configuration.

**Comment by maryam21** [comment]
It turns out the problem was because `htdocs/cms/wp-load.php` was pointing to `htdocs/cms/wp-config.php` instead of `htdocs/wp-config.php`. I think it's an important detail worth mentioning in the documentation.

**Comment by jlambe** [comment]
WordPress handles by default a directory up its root files. If you had to edit a file located in the `cms` directory, then your issue is still there because everytime you'll run an update, you will lose your changes. Have you tried to start a new project by using Laravel Homestead or just a Xampp sort of LAMP stack made out of the box?

**Comment by maryam21** [comment]
Actually I didn't have to modify `htdocs/cms/wp-load.php` file, I just renamed the `htdocs/cms/wp-config.php` so that wordpress doesn't use it by default and instead uses `htdocs/wp-config.php`. 
I haven't used any of those.

**Comment by maryam21** [comment]
Hi @jlambe , thank you for your answers. I think you can close this issue.
