### ISSUE TITLE
Blade template system on themosis

### ISSUE THREAD

**Issue by insaneFreak** [themosis/themosis#226]
Hello,

having problem with blade template system. wonder why i have error like this: https://prnt.sc/k0rirc

it doesnt recognise  symbol "@" and DIV elements.  and showing error.

**Comment by ericgruby01** [comment]
You don't need to open a php tag on blade templates. Remove the <?php and it should work.

**Comment by jlambe** [comment]
@insaneFreak As @ericgruby01 said, remove the `<?php` tag.

**Comment by insaneFreak** [comment]
OK i removed php tags.. but new problem happened https://prnt.sc/k0surv
not found header.blade.php.. how ?

**Comment by jlambe** [comment]
Paths are relative to the `views` directory. If your `header.blade.php` file in in the `layouts` folder, even if you work on the same directory, you need to prepend the directory name for the path.

So it should look like this: `@include('layouts.header')`, same for the footer. Blade only knows about the root view path. Then everything should be relative to it.

**Comment by insaneFreak** [comment]
Thanks !
