### ISSUE TITLE
How to display featured image on themosis 

### ISSUE THREAD

**Issue by insaneFreak** [themosis/themosis#227]
Hi again

which method to use ? to get featured image of  post.
I tryed:
https://prnt.sc/k13z69
https://prnt.sc/k13y7h

**Comment by ericgruby01** [comment]
Try ``{!! $image !!}``. Reference [here](https://laravel.com/docs/5.6/blade)

**Comment by insaneFreak** [comment]
i get an error Undefined variable: image

**Comment by insaneFreak** [comment]
How i can check it ?

**Comment by insaneFreak** [comment]
@jlambe 
    $imageData = get_the_post_thumbnail ($id, 'full');
    var_dump ($imageData); return string(0)
still didnt find out why.. https://www.dropbox.com/s/c2m052tye4fubcd/Screenshot%202018-07-01%2013.31.21.png?dl=0

**Comment by insaneFreak** [comment]
@jlambe  Didnt helped.. i am confused
still drowing string(0) 
`      <?php $count = 0; ?>
            @foreach($posts as $post)
                <?php $count++; ?>
                <?php if ($count % 2 == 0) :  ?>

                <div class="row even no-gutters">
                    <?php
                    var_dump ($image);
                    ?>
                    <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                        <h2 class="title"> {{ $post->post_title }}</h2>

                        <p class="lead mb-0">{{ $post->post_content }}</p>
                    </div>
                    <div class="col-lg-6 order-lg-2 text-white showcase-img">
                        <img src="{!! $image !!}">
                    </div>
                </div>`

**Comment by jlambe** [comment]
The WordPress function get_the_post_thumbnail returns a html string representing the `<img>` tag. So you can't output the result on the `src` attribute. Just echo it like this:
```php
<div class="col-lg-6 order-lg-2 text-white showcase-img">
    {!! $image !!}
</div>
```

**Comment by insaneFreak** [comment]
@jlambe 
https://www.dropbox.com/s/j5ni5kcte9qzgcz/Screenshot%202018-07-01%2023.58.20.png?dl=0
https://www.dropbox.com/s/4unb4m11truc7q0/Screenshot%202018-07-01%2023.55.47.png?dl=0
didnt pass and this one.. strange ..

**Comment by jlambe** [comment]
Your issue is that you're working with the wrong route. Your URI `movies`, what does it represent? Is it a WordPress single page? Or is it an archive of custom post types movies?

A route like `Route::get('page', ['movies', ...])` only refers to a single WordPress page that has a slug of `movies`. While a route like `Route::get('postTypeArchive', ['movies', ...])` refers to the archives page of a custom post type with a slug of `movies`.

On a page route, the `$post` variable is the WP_Post instance representing the page but on an archive route, `$post` holds the data of last queried WP_Post instance -> by default, WordPress is fetching the last 10 posts for an archive. -> So you need to loop through the list of posts using the second parameter `$query` which is the current WP_Query instance populated by WordPress holding all the posts.

Check the [WordPress routes documentation](https://framework.themosis.com/docs/1.3/routing/#wordpress-routes) for more information.

**Comment by insaneFreak** [comment]
@jlambe  It represents **page** so?  should use `Route::get('postTypeArchive', ['movies', ...])` ?

**Comment by jlambe** [comment]
What is the value of the first parameter of your route callback? The `$post` variable. Can you make a var_dump of it and inspect what it is please?

Also, have you defined a featured image on your page/post in the WordPress administration?

**Comment by insaneFreak** [comment]
Yes i have defined. o admin panel. 
ar_dump ($post); shows this:
https://www.dropbox.com/s/qa38br272bv2qa8/Screenshot%202018-07-02%2012.52.29.png?dl=0

**Comment by jlambe** [comment]
Can you post your route code as well now?

**Comment by insaneFreak** [comment]
Yes sure here it is:  https://www.dropbox.com/s/4ic1x5o8sg85t4a/Screenshot%202018-07-02%2013.14.06.png?dl=0

**Comment by jlambe** [comment]
Did you have support for featured image on the page post type? Did you update the `supports.config.php` file and add `page` value to the 'post-thumbnails'  key ?

Check this [line](https://github.com/themosis/theme/blob/master/resources/config/supports.config.php#L15)

**Comment by insaneFreak** [comment]
like this ?   'post-thumbnails' => ['post', 'page']
no but i just added nothing happened

**Comment by jlambe** [comment]
If you haven't added it, then you were not able to attach a featured image to your page. Your code is correct and the result of `get_the_post_thumbnail()` is an empty string.

If you call the [has_post_thumbnail($post_id)](https://developer.wordpress.org/reference/functions/has_post_thumbnail/) function, the result should be false. Add a featured image to your page.

**Comment by insaneFreak** [comment]
Ok. i figured out some thing.. first of all... pages "movies" looks like this when i attached thumbnail
https://prnt.sc/k1kx6o
https://prnt.sc/k1kwaw
But i i wanna that images go from posts not from page.. From here https://prnt.sc/k1ky6z
Must be i realy dont understood

**Comment by jlambe** [comment]
Page and Post are two different objects types and they don't communicate to each other.

For what you're trying to do, you need to loop through all posts (array) and then for each one of them, call the `get_the_post_thumbnail()` function by passing the ID of each post. When WordPress is referencing the name "post", it's not just an article anymore, it's the `WP_Post` instance which can be a post (article), page, custom post type, attachment, menu, ...

From your route, the `$post` variable is referencing the `movies` page and you don't have any information related to your list of posts. Not sure what your `$model` is doing but if it holds the list of posts, then from your view, you have to loop through them and then call the appropriate functions.

**Comment by insaneFreak** [comment]
i have list_all() function in my model. Is this right way? there is WP_QUERY which gets all posts
https://prnt.sc/k1lc5t

**Comment by jlambe** [comment]
Yes it looks right. Your method returns an array, then you just have to loop through your items in your view. That's it.

**Comment by insaneFreak** [comment]
How the loop should look like ?  And where to put to the routes ?

**Comment by insaneFreak** [comment]
Solved ! 
just added:
`  $image_array = get_the_post_thumbnail_url (($post->ID), 'large');`
and
`   <img src="{!!$image_array!!}">`
