### ISSUE TITLE
hey guys any news ?? 

### ISSUE THREAD

**Issue by almokhtarbr** [themosis/themosis#229]
Hi , is there any new news about this amazing work . 
thank u

**Comment by craigiswayne** [comment]
Hi @almokhtarbr , not sure what you are referring to but if you're looking to get in touch with developers or would like updates on the progress of this project, you have the following options:

1. [Watch this Repo by this link](https://github.com/themosis/themosis/subscription)
1. [Follow themosis on twitter](https://www.twitter.com/Themosis)
1. [Sign up for the newsletter](https://framework.themosis.com/#newsletter)

**Comment by jlambe** [comment]
@almokhtarbr A release is targeted for this year. I suggest you to follow our [Twitter account](https://twitter.com/Themosis) for project updates. Thanks.
