### ISSUE TITLE
[metabox] add fields to an existing metabox.

### ISSUE THREAD

**Issue by SiddhyN** [themosis/themosis#231]
Hello,

I would like to know if there is a way to add fields to an existing metabox.

The goal is to have a generic module that creates the content type with some basic fields in a metabox and a "child" module that overloads the metabox by adding or removing fields.

I did not see if we could recover a particular metabox to play with his fields

Thank you !

PS: great job in any case!

**Comment by jlambe** [comment]
Such logic has not been implemented as the only to attach fields to a metabox is by using the `set()` method, which displays directly the fields.

I haven't tested this on the next release yet, but the new version of the framework is using an `add()` method to attach fields to the metabox so, in theory, this might be possible with the next release.

**Comment by SiddhyN** [comment]
Yes I understand. Thank you for your answer and thank you for your good job!
