### ISSUE TITLE
Cannot create pages 

### ISSUE THREAD

**Issue by touatily** [themosis/themosis#232]
Hello,

I recently installed wordpress/themosis following the steps detailed [here](https://framework.themosis.com/docs/1.3/installation/)

But, I got blank pages and I caanot create pages. Indeed, I add some test to the welcome page (for example), but I get alwayes blak page when I display it !

Is it due to a configuration issue?

**Comment by jlambe** [comment]
Hello,

after the installation, you have to directly login into the administration and make the theme is activated. By default, you should get a "welcome" message on screen.

**Comment by touatily** [comment]
Yes I activated the theme, and I got this welcome page. However, all other pages I create are not displayed, I got only blank pages even if the page actually contains text.

 ![image](https://user-images.githubusercontent.com/27826148/46524933-907db680-c88a-11e8-8fd6-99b2b3ef54e1.png)

**Comment by jlambe** [comment]
Can you share your `routes.php` file ?

**Comment by touatily** [comment]
`<?php
Route::get('home', function()
{
    return view('welcome');
});`

**Comment by jlambe** [comment]
Sure but this one is the welcome/default one that works. Can you show what code did you add for your pages and provide the steps for creating your expected pages ?

By default, there are no routes defined for "WordPress Pages". So you need to add this for example in the `routes.php` file:
```php
Route::any('page', function () {
    return 'Page content';
});
```

**Comment by touatily** [comment]
Ok thank you for your answer.

I would like to know if there an easy way to export/import a website developed using Themosis framework? I mean without recreating all php pages manually.

I tried to export/import it using the wordpress option, but I got many errors and I didn't get any page.

**Comment by jlambe** [comment]
Export/Import is for WordPress data only. If you have a WordPress theme, you can just copy the theme to your stack and activate the theme. You don't need to use the provided theme and write routes.

**Comment by touatily** [comment]
I have already tried to just copy the themosis directory but I got composer error!
What do you mean by stack here?

**Comment by touatily** [comment]
Hi again,
Is there a procedure to follow in order to export/import a themosis website safely from one machine to another one?
I tried to just copy the theme directory and I got composer error, and the website doesn't work.

**Comment by touatily** [comment]
I copied the application files and the database. However, I get nothing! Even the welcome page doesn't return anything.
Any idea what is the problem?

**Comment by touatily** [comment]
I got these errors in the apache2 `error.log` file

```
[Wed Oct 17 17:15:33.716719 2018] [php7:warn] [pid 12755] [client 10.254.42.98:53875] PHP Warning:  require(/var/www/html/entrepose/vendor/composer/../../htdocs/content/mu-plugins/themosis-framework/src/Themosis/helpers.php): failed to open stream: No such file or directory in /var/www/html/entrepose/vendor/composer/autoload_real.php on line 66
[Wed Oct 17 17:15:33.716816 2018] [php7:error] [pid 12755] [client 10.254.42.98:53875] PHP Fatal error:  require(): Failed opening required '/var/www/html/entrepose/vendor/composer/../../htdocs/content/mu-plugins/themosis-framework/src/Themosis/helpers.php' (include_path='.:/usr/share/php') in /var/www/html/entrepose/vendor/composer/autoload_real.php on line 66
```

In the screen there is an `HTTP ERROR 500`

Actually the application is somehow working in the other machine, but we got some problems activiating `https`. So I'm trying to export/import the whole into another mahcine with new and clean Themosis installation, and then work on it.
