### ISSUE TITLE
Translation Wordpress

### ISSUE THREAD

**Issue by alcir-junior-caju** [themosis/themosis#233]
Hello, when I go to do the first installation, does not appear the option to install with the language I want.

Is this normal or is it a problem?

In the settings only the option in English appears, how could I translate manually?

Or even already install in the correct language.

Thank you all.

**Comment by jlambe** [comment]
Not normal. You should by default get the usual WordPress installation screen with all languages to select from. Not sure why this is happening to you, perhaps a connection issue to wordpress.org.

Is this still happening ?

In case you still have the english installation only, after logging in to the administration, you should be able to install another language pack fron the General settings page.

**Comment by jlambe** [comment]
Not sure. Can you try perhaps on a Homestead virtual machine or other environment? I've personnaly worked on custom docker configuration for a project and I haven't met this issue.

If you're working on version 1.3, do you have turned on the `THEMOSIS_ERROR` constant to `true` inside your `config/environments/local.php` file?

**Comment by alcir-junior-caju** [comment]
Today I made a new installation, with version 2.0 and the same happens, the installation screen already starts for user registration.

And the option of other languages ​​does not appear.

I will test install in another environment to see if it resolves.

**Comment by alcir-junior-caju** [comment]
I really was not successful.

I tested in another environment, and every time the wordpress installation already starts at the user's definition and password.

I even went to br.wordpress downloaded the translated cms and threw the languages ​​folder but it also did not translate.

Has anyone ever experienced this?

**Comment by Jaspervv** [comment]
You could also change your language manually. 
### Download
Download the `.mo` language files for the language you want [here](https://translate.wordpress.org/projects/wp) and place them in your project's `./htdocs/content/languages/` directory. Now all you need to do is activate the language in the database.

### Set language
You can update the database field in your project's `./htdocs/wp-config.php` file with the following line of code:
```php
define('WPLANG', 'nl_NL');
```
Where `nl_NL` is the country code of the language you downloaded. You can find a list of all country codes [here](https://translate.wordpress.org/).

**Comment by Jaspervv** [comment]
Maybe this like could be of help as well: https://wordpress.stackexchange.com/a/270819 .

> Maybe WordPress doesn't have permissions to save the new language files. I had the same problem, and I solved it by adding the following to `wp-config.php`
> ```php
> define('FS_METHOD', 'direct');
> ```
> You might also want to check that your `wp-content/`-directory is writable for the web server user.

**Comment by alcir-junior-caju** [comment]
> You could also change your language manually.
> 
> ### Download
> Download the `.mo` language files for the language you want [here](https://translate.wordpress.org/projects/wp) and place them in your project's `./htdocs/content/languages/` directory. Now all you need to do is activate the language in the database.
> 
> ### Set language
> You can update the database field in your project's `./htdocs/wp-config.php` file with the following line of code:
> 
> ```
> define('WPLANG', 'nl_NL');
> ```
> 
> Where `nl_NL` is the country code of the language you downloaded. You can find a list of all country codes [here](https://translate.wordpress.org/).

Okay, in themosmos in the `. / Htdocs / wp-config.php` file there is no such parameter ```define ('WPLANG', 'nl_NL');```

I found in `./config/app.php` the `locale` parameter, but I changed it, and it did not change anything.

**Comment by alcir-junior-caju** [comment]
> You could also change your language manually.
> 
> ### Download
> Download the `.mo` language files for the language you want [here](https://translate.wordpress.org/projects/wp) and place them in your project's `./htdocs/content/languages/` directory. Now all you need to do is activate the language in the database.
> 
> ### Set language
> You can update the database field in your project's `./htdocs/wp-config.php` file with the following line of code:
> 
> ```
> define('WPLANG', 'nl_NL');
> ```
> 
> Where `nl_NL` is the country code of the language you downloaded. You can find a list of all country codes [here](https://translate.wordpress.org/).

I have tried this but to no avail, when I enter the dashboard to change the language, only English is available

**Comment by alcir-junior-caju** [comment]
> Maybe this like could be of help as well: https://wordpress.stackexchange.com/a/270819 .
> 
> > Maybe WordPress doesn't have permissions to save the new language files. I had the same problem, and I solved it by adding the following to `wp-config.php`
> > ```
> > define('FS_METHOD', 'direct');
> > ```
> > 
> > 
> > You might also want to check that your `wp-content/`-directory is writable for the web server user.

I'll try this solution
