### ISSUE TITLE
problem routing

### ISSUE THREAD

**Issue by Cedric-locchi** [themosis/themosis#234]
Hello, i have many problem with the routing system. Indeed, i define the roads as I need them, they redirect me to the homepage systematically. I have a permalink rule applied, but nothing helps.

Sorry for my bad english, i'm french ^^

**Comment by jlambe** [comment]
Le support peut se faire également en français.

Pouvez-vous nous donner plus de détails sur votre environnement de développement, la configuration du stack, la version du framework et votre fichier `routes.php` ?

**Comment by Cedric-locchi** [comment]
bien entendu (cool!!!)

alors version 1.3, install propre sans import de donnée datant d'il y a 2h, stack LAMP de base sur la prod (ubuntu apache mysql) et en local pour le dev mamp pro 

fichier route:

```
// route principal
Route::get('home', 'Home@index');

// blogs routes
Route::get('/articles/', 'Articles@index');
Route::get('/articles/{category}/{slug}', 'Articles@one');

// contact route
Route::get('/nous-contacter', 'Contact@index');

// tags route
Route::get('/{slug}','Pages@render');
```

fichier .env

```
DB_NAME = "qu2ay0oa"
DB_USER = "qu2ay0oa"
DB_PASSWORD = "****"
DB_HOST = "localhost"
WP_HOME = "https://****.com"
WP_SITEURL = "https://****.com/cms"
```

**Comment by Cedric-locchi** [comment]
Petite info supplémentaire, lors de l'utilisation de mon url, la premiere est appelé avec un code
 __301 Moved Permanently__ sous la forme __/url_send__ et de type __text/html__ pour être redirigé vers une url de se type __/url_send/__ avec un code 200 de type __document__ et me retourne sur la home page avec l'url bien ecrite dans la barre d'url

**Comment by Cedric-locchi** [comment]
Info supplémentaire aussi, j'ai désactiver le cache au cas si il gardait en cache la redirection ver la home page.

**Comment by jlambe** [comment]
@Cedric-locchi Que se passe t'il lorsque vous déplacez la route `home` en dessous de toutes les autres ?

La première route est une route "WordPress" et correspond à l'uri `/ `. Les autres routes sont personnalisées et ne correspondent pas à une route WordPress/template et en règle générale il est préférable de les placer avant les routes "WordPress".

**Comment by Cedric-locchi** [comment]
Ca marche, c'est une bonne chose ca!! j'ai pas lu dans ca dans la doc, mais maintenant ca marche :-) cool!! Merci beaucoup
