### ISSUE TITLE
Backend Translation Problem

### ISSUE THREAD

**Issue by 9585999** [themosis/themosis#235]
Hi, my problem is this:

I use `PoEdit.app` to translate strings, and it does its job well, but the fact is that the translated strings only work in **FrontEnd**, and in the **Backend** they remain not translated ...

Here is a small piece of code for example:

```php
$books = PostType::make('books', __('Books', THEME_TEXTDOMAIN), __('Book', THEME_TEXTDOMAIN))->set();

$books->status([
    __('Rent', THEME_TEXTDOMAIN),
    __('Rented', THEME_TEXTDOMAIN),
    __('Sell', THEME_TEXTDOMAIN),
    __('Sold', THEME_TEXTDOMAIN),
]);
```

In **FrontEnd**, any of these strings when called `__ ($string, THEME_TEXTDOMAIN)` translates as expected, but the original string remains in **BackEnd** ...

![img 2018-11-28 12 29 39](https://user-images.githubusercontent.com/16165904/49142233-5d472900-f309-11e8-931e-80455f0ee65f.png)
![img 2018-11-28 12 29 46](https://user-images.githubusercontent.com/16165904/49142234-5d472900-f309-11e8-944a-549acf4c2463.png)

What could be the cause of this problem?

**Comment by mundgold** [comment]
I have the same issue!

**Comment by jlambe** [comment]
Not sure about this but seems like `load_theme_textdomain` is only triggered on the front-end.

You probably have to move your custom post type to a plugin and then use the `load_plugin_textdomain` instead to translate these.

**Comment by 9585999** [comment]
@jlambe 

In version 2-beta3 of the framework, there is also a problem with translations, at least with translations of config files.

The problem is that `$theme->config($key)` gets an untranslated array ...

Here are a few screenshots for clarity.

![img 2019-02-09 1 36 47](https://user-images.githubusercontent.com/16165904/52510106-c1407480-2c0b-11e9-8f09-f13bb3039f14.png)
![img 2019-02-09 1 37 39](https://user-images.githubusercontent.com/16165904/52510109-c4d3fb80-2c0b-11e9-8607-c263ba3ab263.png)
![img 2019-02-09 1 38 01](https://user-images.githubusercontent.com/16165904/52510133-d74e3500-2c0b-11e9-8790-4930bf6b94c9.png)
![img 2019-02-09 1 37 53](https://user-images.githubusercontent.com/16165904/52510116-c9001900-2c0b-11e9-802b-c7fb0ba62a8d.png)
![img 2019-02-09 1 38 50](https://user-images.githubusercontent.com/16165904/52510143-dfa67000-2c0b-11e9-90a5-a3f51d54c9d6.png)
