### ISSUE TITLE
File Sessions: directory not found error

### ISSUE THREAD

**Issue by Jaspervv** [themosis/themosis#236]
**Error:**
```
file_put_contents(/home/jasper/Projects/wp-soup/storage/framework/sessions/ooj97eMoyN2FKeN9gz3x0Zwv8Sn7nb0uRzhCzQa2): failed to open stream: No such file or directory
```

**Why:**
The default sessions path for the session driver is set to `framework/sessions`, but this folder doesn't exist by default.
File_put_contents doesn't create the folder structure, just the file, and throws an error when the folder doesn't exist.

**Fix:**
Most easy way to fix it is adding a folder called `sessions` under `./storage/framework`.
With a `.gitignore` inside:
```
*
!.gitignore
```

**Comment by jlambe** [comment]
Thanks for catching this one. I'll add the missing directory to the project.
