### ISSUE TITLE
404 on installation

### ISSUE THREAD

**Issue by seahunter** [themosis/themosis#238]
Hello, I am using Open Server as web server on my local machine and try to install themosis. After downloading project by composer and change config in .env i tried to install by going on http://mysite.loc/cms but there was 404 page. What i am doing wrong? Thanks.

**Comment by jlambe** [comment]
You have to visite the `http://mysite.loc/` URL to launch the WordPress installation. The `cms` URI is then the base URI for accessing the administration of WordPress.

I personnaly don't know the Open server. Perhaps there is also a misconfiguration. Note that the `Homestead` VM is by default defined as a dev dependency if you want to run a virtual machine with all requirements.

**Comment by seahunter** [comment]
If i visit http://mysite.loc/ I see the folders and files in this directory http://joxi.ru/J2banPlcXQ0Qwm. Open Server is analogue of xampp.  
This is my config .env:
```APP_ENV = "locdal"
APP_DEBUG = true
DATABASE_NAME = "mysite"
DATABASE_USER = "root"
DATABASE_PASSWORD = ""
DATABASE_HOST = "localhost"
WP_HOME = "http://mysite.loc"
WP_SITEURL = "http://mysite.loc/cms"``` 
Is it right?

**Comment by jlambe** [comment]
If you see those folders, then your Open Server public directory for the web server is wrong. You have defined the project root as the public directory where it must be the `htdocs` folder instead.

**Comment by seahunter** [comment]
Thanks. I didn't find this in docs. After adding `thdocs` as a root folder of http://mysite.loc, everything works well.

**Comment by jlambe** [comment]
Great, glad it is soved. I'll review the doc and see if I haven't miss to add this information.
