### ISSUE TITLE
Is Themosis framework "theme independent"?

### ISSUE THREAD

**Issue by distributev** [themosis/themosis#239]
Because I tried to get Themosis working with the latest roots.io Sage 9 theme and I got the following error.

![image](https://user-images.githubusercontent.com/19224635/50559057-791c6100-0cf3-11e9-857f-a0f64a6ad96c.png)

**Comment by jlambe** [comment]
Not really but you have to add those lines in your theme `index.php` file:
```php
<?php

use App\Http\Kernel;
use Themosis\Core\Application;

$app = Application::getInstance();
$app->manage(Kernel::class, $app['request']);

```

Then, based on your error, it seems that you have an instance of our core Application class where `Sage` is expecting another kind of class.

**Comment by distributev** [comment]
This is the first time I see a theme breaking because of the backend wordpress - It is themosis framework which changes the way in which WordPress works, or it is the Sage theme doing something which is not quite right?

**Comment by jlambe** [comment]
The framework does not change the behavior of WordPress. I suspect a conflict in the dependency injection container between Themosis and Roots. I do not know Sage so I can't help you more.
