### ISSUE TITLE
Taxonomy Facade set() args are being ignored

### ISSUE THREAD

**Issue by boxybird** [themosis/themosis#241]
I'm able to create a taxonomy with the code below, but the additional $args I'm passing have no effect. Take 'hierarchical' => true for example. No errors are throw, but in WP admin the actor taxonomy is behaving like 'tags' and not 'categories'. Any thoughts?

`
namespace App\Hooks;

use Themosis\Hook\Hookable;
use Themosis\Support\Facades\Taxonomy;

class ActorTaxonomy extends Hookable
{
    /**
     * Extend WordPress.
     */
    public function register()
    {
        Taxonomy::make('actor', 'movie', 'Actors', 'Actor')->set([
            **'public'       => true,**
            **'rewrite'      => false,**
            **'query_var'    => false,**
            **'hierarchical' => true**
        ]);
    }
}

/*
    |--------------------------------------------------------------------------
    | Application hooks
    |--------------------------------------------------------------------------
    |
    | This array of hookable classes will be triggered when the WordPress
    | hook API is loaded. Feel free to register as many hookable classes
    | as you wish in order to organize your code.
    |
    */
    'hooks' => [
        App\Hooks\Application::class,
        App\Hooks\Compat::class,
        App\Hooks\Mail::class,
        App\Hooks\Widgets::class,
        App\Hooks\Movie::class,
        **App\Hooks\ActorTaxonomy::class,**
    ],
`

**Comment by Jaspervv** [comment]
The way Taxonomies are created has been changed in Themosis 2.
 You still run the `set()` method to register the taxonomy, but you must use a new method called `setArguments()` to set the args.

So in your case it would look like this:

```
Taxonomy::make('actor', 'movie', 'Actors', 'Actor')->setArguments(
[
    'public' => true,
    'rewrite' => false,
    'query_var' => false,
    'hierarchical' => true
])->set();
```

**Comment by boxybird** [comment]
Works perfectly. Thanks a ton.
