### ISSUE TITLE
Adding Page with sections and settings - Themosis 2.0

### ISSUE THREAD

**Issue by AdrianKielbasa** [themosis/themosis#244]
How to add Page with sections and settings in Themosis 2.0?
This code from documentation is not working:
`$sections[] = Section::make('section-slug-name', 'Section Title');`
`$page = Page::make('page-slug', 'Page Title')->set();`

`// Add the previously created section(s).`
`$page->addSections($sections);`
`$settings['section-slug-name'] = [
    Field::text('street-address'),
    Field::text('phone'),
    Field::media('theme-logo')
];`
`$page->addSettings($settings);`

**Comment by jlambe** [comment]
The documentation has not yet been updated but here is a code snippet that might help you:

```php
use Themosis\Support\Facades\Field;
use Themosis\Support\Facades\Page;
use Themosis\Support\Section;

Page::make('page-slug', 'Page Title')
    ->addSections([
        new Section('section-slug', 'Section Title')
    ])
    ->addSettings([
        'section-slug' => [
            Field::text('street-address'),
            Field::text('phone'),
            Field::media('theme-logo')
        ]
    ])
    ->set();
```

The main change is how we handle the sections by creating a new instance directly. Also, note that the `infinite` field is no longer available on current 2.0 release.

Both page and field documentation have not been updated yet but you can check the metabox documentation on adding fields for some details on how to validate your page settings, ...: https://framework.themosis.com/docs/2.0/metabox/#add-custom-fields

**Comment by Jaspervv** [comment]
In 1.3 page settings were set by passing an array to the `->set()` command.
In 2.0 you have to use individual methods to set page settings.

For example to set the page capability in **1.3** you would write it like this:
```php
Page::make('my-custom-page', 'A custom page')->set([
    'capability' => 'edit_posts'
]);
```

However in **2.0** you would write it like so:
```php
Page::make('my-custom-page', 'A custom page')
    ->setCapability('edit_posts')
    ->set();
```

To see a list of all available methods, take a look at the [Page.php class](https://github.com/themosis/framework/blob/master/src/Page/Page.php).

As far as I know these are all the available methods:
```php
Page::make('my-custom-page', 'A custom page')
    // The slug name to refer to this menu by. Should be unique for this menu page
    // and only include lowercase alphanumeric, dashes, and underscores characters
    ->setSlug('my-custom-page')
    // The text to be displayed in the title tags of the page when the menu is selected
    ->setTitle('A custom page')
    // The text to be used for the menu
    ->setMenu('A custom page')
    //  The capability required for this menu to be displayed to the user
    ->setCapability('edit_posts')
    // The URL to the icon to be used for this menu,
    // or one of wordpress's Dashicons helper classes.
    ->setIcon('dashicons-admin-generic')
    //  The position in the menu order this one should appear.
    ->setPosition(20)
    // Another page's slug, this page will then be placed as a submenu under the specified one.
    ->setParent('another-page-slug');
```
```

**Comment by AdrianKielbasa** [comment]
Thank you for your answers.

**Comment by baryaz** [comment]
I used this : 
use Themosis\Support\Facades\Field;
use Themosis\Support\Facades\Page;
use Themosis\Support\Section;

Page::make('page-slug', 'Page Title')
    ->addSections([
        new Section('section-slug', 'Section Title')
    ])
    ->addSettings([
        'section-slug' => [
            Field::text('street-address'),
            Field::text('phone'),
            Field::media('theme-logo')
        ]
    ])
    ->set();
this is cool it works, how can i get the value of a field after saving changes in the form.

**Comment by jlambe** [comment]
Values are stored in the options table. By default, all options keys are prefixed with the `th_`. So your `phone` value is stored under the `th_phone` option name.

Use core WordPress `get_option()` function to fetch its value: `get_option('th_phone')`.
