### ISSUE TITLE
[FEATURE] Page Tabs

### ISSUE THREAD

**Issue by Jaspervv** [themosis/themosis#245]
## Is the tabs functionality still available in 2.0?  
If so how can it be activated?  
If not, is it in the planning? 

In **1.3** we had the option to make sections behave like tabs:
```php
Page::make('my-page', 'My Page')->set([
    'tabs'       => true,
]);
```
This was very useful for pages which contain a lot of settings.

**Comment by jlambe** [comment]
The tabs layout is no longer available for now but it is planned to bring it back at some point. Just not sure about the design layout.

**Comment by jlambe** [comment]
I'm closing this now as it is planned to build a refreshed UI on 2.1.
