### ISSUE TITLE
Combine controller action with WP page (2.0)

### ISSUE THREAD

**Issue by twosg** [themosis/themosis#246]
I may be totally on the wrong path, working with 2.0-beta, I am just wondering if it's possible to combine regular wordpress pages with controller actions?

For example I have a page "/reseller" in WP and I have created a route with a controller for it. The page loads fine, but it seems it loads because of my "default" page route:

```php
Route::match(['GET', 'POST'], 'page', function($post, $query) {
	$page_template = get_post_meta($post->ID, '_wp_page_template');
	if(!is_array($page_template) || !isset($page_template[0])) {
		$page_template = ['default'];
	}
	return view('pages.default', [
		'page' => $post,
		'template' => $page_template[0]
	]);
});
```

The controller, routed with: `Route::match(['GET', 'POST'], '/reseller/', ['uses' => 'Reseller@index'])->name('reseller.index');` also runs on the /reseller page. Reseller@index looks like this:

```php
function index() {
// ... some stuff is done here for displaying a map based on user input
return view('pages.default', [
		'message' => $outputMessage,
		'lat' => $lat,
		'lng' => $lng,
		'formatedAddress' => $formatedAddress,
		'result' => $result,
		'addressValue' => $address_value,
		'zoom' => $zoom
	]);
}
```

As soon as I want to use the view variables in my view, I get an error regarding that the variable is undefind. So somehow the controller runs but the view for /reseller seems to be the default view for pages.

Reason behind this is that the customer shall be able to edit the page in WP (texts, images) but that page should also render a nice map, where the address for the map is provided by a form on that page.

Is there a better/other way of doing such a thing?

**Comment by jlambe** [comment]
Yes definitaly, there is a better way. You can either use the `reseller` slug/uri as a parameter for the page route or you can use the `template` route directly as it seems that you may attach a template to your reseller page.

You can also directly attach a controller to it to better handle the logic before rendering. Here are the 2 examples:

```php
Route::match(['get', 'post'], 'page', ['reseller', 'uses' => 'PageController@method']);

// ...or the template way
Route::match(['get', 'post'], 'template', ['map-template', 'uses' => 'PageController@method']);
```

As you don't work with a redirect, you can write all the logic for your map inside the controller method and return necessary data to your view.

If your client needs to control the content of the page, use WordPress routes only. If they don't, use a custom route. Hope this helps.

**Comment by twosg** [comment]
Thanks that helped :)
