### ISSUE TITLE
Create PostType

### ISSUE THREAD

**Issue by alcir-junior-caju** [themosis/themosis#247]
I'm having trouble creating a PostType, I'm following the documentation: https://framework.themosis.com/docs/2.0/posttype/#basic-usage

I'm creating the Books.php file in app/Hooks but in wordpress it does not display the content type, am I forgetting something? Thank you.

**Comment by jlambe** [comment]
After creating a `Hookable` class, it has to be registered in the `hooks` property of the `config/app.php` file at root of your application like so:

```php
'hooks' => [
    App\Hooks\Application::class,
    App\Hooks\Books::class,
    ...
]
```

I miss to provide information about hookable classes yet, sorry.

**Comment by alcir-junior-caju** [comment]
Perfect, I did not find this information in the documentation, I believe it has gone unnoticed.

Thank you

**Comment by jlambe** [comment]
It's my fault, I haven't yet written a doc for using hookable classes. Coming soon :)

**Comment by alcir-junior-caju** [comment]
No problems... Thanks :)
