### ISSUE TITLE
Unable to find the asset with the following path: css/theme.css

### ISSUE THREAD

**Issue by 4568520** [themosis/themosis#248]
Windows 10 using [Laragon](https://laragon.org/) with nginx-1.52.2, PHP 7.1.14 and MariaDB 10.2.14.
I replicate installation process step by step from [documentation](https://framework.themosis.com/docs/2.0/installation). Without  setting up Laravel Homestead.
Set root to htpdocs. I went through wp install process(db looks legit). Then I get [error](https://user-images.githubusercontent.com/33126420/52220845-7ee40400-28a8-11e9-93fe-19b1c49569a9.jpg) on any url. Theme.css and other theme files seems to be in the [right place](https://user-images.githubusercontent.com/33126420/52221292-83f58300-28a9-11e9-96d3-8565135f95d5.jpg).
I have no idea where is my mistake(if i made any).

**Comment by Jaspervv** [comment]
Are you sure you're using beta3 of the Themosis/Framework?
I personally have no issues on Windows 10 with the new beta3, although on WIndows I run it with XAMPP, Apache, PHP7.2, MySQL.

**Comment by Jaspervv** [comment]
This problem was mentioned in the following issue: themosis/framework#560 and fixed in the following commit: [5136103](/themosis/framework/commit/51361036f53e8271a3b2693f8b15e374dbca73ed), which has been included since `2.0-beta3`.
Hope you encounter no issues with beta3 :smiley:

**Comment by 4568520** [comment]
Yep, it is solved! Thank you for fast reply and work done! 😃

**Comment by alexv96** [comment]
> ¿Estás seguro de que estás usando beta3 de Themosis / Framework?
> Personalmente, no tengo problemas en Windows 10 con el nuevo beta3, aunque en Windows lo ejecuto con XAMPP, Apache, PHP7.2, MySQL.

How did you configure it with xampp I can't get it to work.
