### ISSUE TITLE
Creating hooks

### ISSUE THREAD

**Issue by Pavel-Mukha** [themosis/themosis#251]
Hello, I created several hooks from the help console commands - php console make: hook Test. But when I write some code, it is not used in the application. How to include this created class?

**Comment by Jaspervv** [comment]
After creating a `Hookable` class, it has to be registered in the `hooks` property of the `config/app.php` file at root of your application like so:
```php
'hooks' => [
    App\Hooks\Application::class,
    App\Hooks\Books::class,
    ...
]
```

**Comment by Pavel-Mukha** [comment]
Thank you very much, everything works :)
