### ISSUE TITLE
Custom routes for the post and page WordPress

### ISSUE THREAD

**Issue by Pavel-Mukha** [themosis/themosis#252]
I need to customize the routing page, for example, we need to get such a route 
`http://site.com/sample-page/args/`
`sample-page` is a real WordPress page created in the admin panel.

I tried to write the following code in the routes 
`Route::get('page/{id}', 'PageController@pageID');`
But by going to `http://site.com/sample-page/args/` I get an error 404.

Is there support for such routes? For example, with api wordpress, you can do this as follows:

```
Action::add('init', function (){ 
       add_rewrite_rule('^([^/]+)/([^/]*)/?$', 'index.php?pagename=$matches[1]&id=$matches[2]', 'top');
});
```

**Comment by Pavel-Mukha** [comment]
I understand the framework does not support such routing?

**Comment by jlambe** [comment]
Normally a `page` WordPress route will only listen to WordPress page requests. Adding an URI like `args` makes it a custom route that WordPress should not be able to listen to.

So you'll have to define a custom route for the `sample/args` url like so:

```php
Route::get('sample/args', 'PageController@pageID');
```

Declaring the custom route before the WordPress one to make sure to listen to it.
