### ISSUE TITLE
Running Themosis in App Engine Flex

### ISSUE THREAD

**Issue by nathanopereira** [themosis/themosis#253]
Hi,

I'm trying to run Themosis on the Google Cloud App Engine Flex, and the app's location is read-only, needs to use Cloud Storage, and also needs to configure routes using app.yaml.

Do you already have any configuration, or any experience, in the Themosis configuration in App Engine Flex?

**Comment by jlambe** [comment]
@nathanopereira Personnally no experience with that platform so I can't help :(
