### ISSUE TITLE
multi-site Incorrect dashboard (wordpress) URLs 

### ISSUE THREAD

**Issue by Jaspervv** [themosis/themosis#255]
## Problem
I have an issue with accessing my multi-site dashboards. My multi-site is path-based.

#### Expected links
The **main site** has to be accessed from:  
site: `themosis.project`  
dashboard: `themosis.project/cms/wp-admin`

The **subsites** have to be accessed from:  
site: `themosis.project/my-site`
dashboard: `themosis.project/my-site/wp-admin`

#### Actual links
All links linking to a subsite's dashboard link like so: `themosis.project/my-site/cms/wp-admin`.  
I have no idea where the `cms/` comes from.

#### Documentation
According to the [documentation](https://framework.themosis.com/docs/1.3/multisite), this is a WordPress core isue. It also offers a fix, but this fix did not work for me.  
The [WordPress issue](https://core.trac.wordpress.org/ticket/33909) it has linked has also been closed due to inactivity.

**Comment by Jaspervv** [comment]
## Fix
Adding the following RewriteRule to my `.htaccess` file fixed it for me:
```apache
RewriteRule ^([_0-9a-zA-Z-]+/)+(cms/)+(wp-(content|admin|includes).*) $1$3 [L]
```

This rewrites `themosis.project/my-site/cms/wp-admin` to `themosis.project/my-site/wp-admin`.   

I don't know if this is the best solution, but it's a solution.

**Comment by jlambe** [comment]
I'm still wondering if this is correct. WordPress, and so its administration is installed inside the `cms` directory. So it is natural to have access to the administration on the root site with the following URL:
- http://themosis.project/cms/wp-admin

So keeping the fact that WordPress is under the `cms` URI, it seems "logical" for me to have the administration panel for a sub-site, installed as a sub-folder on the following URL:
- http://themosis.project/my-subsite/cms/wp-admin

So the default URL returned by WordPress looks correct for me. Now there is nothing under the `my-subsite/cms/wp-admin` folder but I'm wondering if this is not just a URL filter issue.

On the `Application` [hookable class](https://github.com/themosis/themosis/blob/master/app/Hooks/Application.php#L41), there are filters defined that fix network administration URLs for multisite installed as subdomains. Perhaps there is some logic to add on the attached trait that can fix a sub folder network installation.
