### ISSUE TITLE
Hot reload and Homestead

### ISSUE THREAD

**Issue by Bartiff** [themosis/themosis#256]
Hi,
I'm testing the latest version of Themosis (2.0-beta3) with Homestead and I'm having trouble with the default theme. When I make the commands ```npm run watch``` and ```npm run hot``` the observer doesn't work.
If I do ```npm run watch -- --watch-poll``` it works. But I don't know how to get hot reload.

Thanks for your help

**Comment by Jaspervv** [comment]
To make npm run watch work you have to add a script to your page, it tells you this in the terminal after running the command.

for example:

<?php
Action::add('wp_footer', function()
{
        ?>
        <script type="text/javascript" id="__bs_script__">
            //<![CDATA[
            document.write('<script async src="http://HOST:3000/browser-sync/browser-sync-client.js?v=2.24.6"><\/script>'.replace("HOST", location.hostname));
            //]]>
        </script>
        <?php
});

**Comment by Jaspervv** [comment]
To make `npm run watch` work you have to add a script to your page, it tells you this in the terminal after running the command.

for example:
```php
<?php
Action::add('wp_footer', function()
{
        ?>
        <script type="text/javascript" id="__bs_script__">
            //<![CDATA[
            document.write('<script async src="http://HOST:3000/browser-sync/browser-sync-client.js?v=2.24.6"><\/script>'.replace("HOST", location.hostname));
            //]]>
        </script>
        <?php
});
```

**Comment by jlambe** [comment]
@Bartiff You can do as shown by @Jaspervv or you can define a proxy property to the mix `browserSync()` method like so:

```js
mix.browserSync({
    proxy: 'http://yourappdomain.test'
});
```

**Comment by Bartiff** [comment]
Thanks a lot you two.
I tested both solutions and Browser Sync is connected to `http: //yourappdomain.test: 3000`. But when I do `npm run watch`, the changes are not detected.
If I do `npm run watch - --watch-poll` the changes are detected but I don't have Hot Reload.

**Comment by Bartiff** [comment]
I already used Themosis version 1.3 and now I remember that I changed the `watch` Gulp task like this:
```
/*------------*/
/* Watch Task */
/*------------*/
gulp.task('watch', function()
{
    bs.init({
        https: false,
        open: false
    });
    var options = {
        usePolling: true
    };

    gulp.watch(dirs.src + '/stylus/**/*.styl', options, gulp.series('stylus:dev'));
    gulp.watch(dirs.src + '/sass/**/*.scss', options, gulp.series('sass:dev')).on('change', bs.reload);
    gulp.watch(dirs.src + '/js/**/*.js', options, gulp.series('webpack:dev')).on('change', bs.reload);
});
```
It must have been the same problem ...

**Comment by jlambe** [comment]
@Bartiff You need to specify which directories to watch to make it work and relaod the browser. Configure the `files`property of BrowserSync https://browsersync.io/docs/options/#option-files

**Comment by Jaspervv** [comment]
Quick tip, you can also use [`dotenv-extended`](https://www.npmjs.com/package/dotenv-extended) for getting getting the proxy using your already existing `.env` values:
```js
const mix = require('laravel-mix'),
    env = require('dotenv-extended').load()

// compile assets
mix.js('assets/js/script.js', 'dist/js')
    .sass('assets/sass/style.scss', 'dist/css')

// watch
mix.browserSync(
{
    proxy: env.WP_HOME,
    files:
    [
        './dist/css/{*,**/*}.css',
        './dist/js/{*,**/*}.js',
    ]
})

```

**Comment by Bartiff** [comment]
Unfortunately I did everything you advised me. But still not watching files...

**Comment by jlambe** [comment]
Do not watch the `dist` directory but the `assets` one instead.

**Comment by Bartiff** [comment]
Yes I tried too. But that does not work either.
Could the problem be coming from Homestead?

**Comment by jlambe** [comment]
I don't think so. I personnaly run front-end tools from my computer not the virtual machine.
