### ISSUE TITLE
Questions about routes

### ISSUE THREAD

**Issue by alcir-junior-caju** [themosis/themosis#258]
For me to display pages and even blog is it necessary to always add routes?

Example: I have a blog with several articles, so that I can display in frontend, do I need to create a route for this blog and link in the theme menu?

In the documentation I was a bit confused.

Thank you.

**Comment by jlambe** [comment]
Routes are necessary as the theme do not use default template files like `archive.php`, `single.php`, ... In order for your blog to return a response, you have to define those routes:

```php
Route::any('blog', ...);
Route::any('single', ...);
...
```

It all depends on your needs.

**Comment by alcir-junior-caju** [comment]
Thanks
