### ISSUE TITLE
Rest url prefix not changing

### ISSUE THREAD

**Issue by YassineBenaziz** [themosis/themosis#259]
I'm working on 2.0-beta3, and I have a probleme to change the api slug. I add the following code to the register function in app/Hooks/Application.php, but it changes nothing.

`        Filter::add('rest_url_prefix',   function(){
            return 'api-test';
        });`
The REST API still working with wp-json slug, instead of api-test

**Comment by jlambe** [comment]
Have you tried to call the core function `add_filter` to see if it works or not? Your issue is perhaps a filter that is never called due to a specific action.

I suggest you to create a separate Hook class, registers it and attach it to the `rest_api_init` action hook before calling your filter.

**Comment by YassineBenaziz** [comment]
I tried both alternatives, but it does'nt work. I created a class named API, and add it to Hooks array in config/app.php like so : 

`<?php
/**
 * Created by PhpStorm.
 * User: y.benaziz
 * Date: 21/02/2019
 * Time: 15:16
 */

namespace App\Hooks;

use Themosis\Hook\Hookable;
use Filter;


class API extends Hookable
{


    public function register() {
        
        /*
        |--------------------------------------------------------------------------
        | Change API Slug
        |--------------------------------------------------------------------------
        |
        | This Filter is for changing the API Slug
        |
        */


        Filter::add('rest_url_prefix',function(){
            return 'api-test';
        });


    }



}`


and in config/app.php file : 

`    /*
    |--------------------------------------------------------------------------
    | Application hooks
    |--------------------------------------------------------------------------
    |
    | This array of hookable classes will be triggered when the WordPress
    | hook API is loaded. Feel free to register as many hookable classes
    | as you wish in order to organize your code.
    |
    */
    'hooks' => [
        App\Hooks\Application::class,
        App\Hooks\Backend::class,
        App\Hooks\Compat::class,
        App\Hooks\Mail::class,
        App\Hooks\Media::class,
        App\Hooks\Metaboxes::class,
        App\Hooks\Widgets::class,
        App\Hooks\API::class,
    ],
.
.
.
`

**Comment by jlambe** [comment]
The imported Filter class is wrong, it should be `Themosis\Support\Facades\Filter`. Perhaps that's the issue ?

Try this code for your Hook class:

```php
<?php

namespace App\Hooks;

use Themosis\Hook\Hookable;
use Themosis\Support\Facades\Filter;

class API extends Hookable
{
    public $hook = 'rest_api_init';

    public function register()
    {
        Filter::add('rest_url_prefix', function () {
            return 'api-test';
        });
    }
}
```

**Comment by YassineBenaziz** [comment]
I tried this, but it does'nt resolve my problem, the use statement `use Filter` is just an alias of `use Themosis\Support\Facades\Filter` that's been declared in config/app.php file like so : 
`'aliases' => [
        'Action' => Themosis\Support\Facades\Action::class,
        'Ajax' => Themosis\Support\Facades\Ajax::class,
        'App' => Illuminate\Support\Facades\App::class,
        'Asset' => Themosis\Support\Facades\Asset::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Console' => Themosis\Core\Support\Facades\Console::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Field' => Themosis\Support\Facades\Field::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Form' => Themosis\Support\Facades\Form::class,
        **'Filter' => Themosis\Support\Facades\Filter::class,**
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Html' => Themosis\Support\Facades\Html::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Loop' => Themosis\Support\Facades\Loop::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Metabox' => Themosis\Support\Facades\Metabox::class,
        'Page' => Themosis\Support\Facades\Page::class,
        'PostType' => Themosis\Support\Facades\PostType::class,
        'Route' => Themosis\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'Taxonomy' => Themosis\Support\Facades\Taxonomy::class,
        'Twig' => Themosis\Support\Facades\Twig::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class
    ],`

**Comment by ccambournac** [comment]
Salut @yassine ! :)

Est-ce que tu utilises un paramètre de priorité dans ton filtre ?

**Comment by YassineBenaziz** [comment]
Salut Cyril, 
Oui j'ai bien essayé de mettre un indice de priorité élevé, mais sans succès.

**Comment by YassineBenaziz** [comment]
When I call my API with te URI : mydomain/**wp-json**/wp/v2/posts/1 , it returns me the result with href links thats contains api-slug , which means that it works but not every time (routing does not work) like so : 

.
.
"_links":{  
      "self":[  
         {  
            "href":"http:\/\/domain\/**api-test**\/wp\/v2\/posts\/1"
         }
      ],
.
.

**Comment by jlambe** [comment]
@YassineBenaziz The following is working perfectly. The one to not forget is that Rest API endpoints are registered in the database.. So after changing the prefix, you net to flush permalinks.

```php
<?php

namespace App\Hooks;

use Themosis\Hook\Hookable;
use Themosis\Support\Facades\Filter;

class Api extends Hookable
{
    public function register()
    {
        Filter::add('rest_url_prefix', function () {
            return 'api-test';
        });
    }
}
```

**Comment by YassineBenaziz** [comment]
@jlambe  Thanks a lot, it works perfectely, it's the flush permalinks that I missed
