### ISSUE TITLE
template routing not working 2.0 beta

### ISSUE THREAD

**Issue by Bozzified** [themosis/themosis#260]
In previous version I had no problem defining templates and routing, however with 2.0 I am having problem loading templates. Namely when I define one template route it works fine. As soon as I add the one after like I do in the example below, login template loads fine, but registration one doesn't, it reports as if the page/route is not found.

Here's what I have. Pretty simple and works on other sites I built with Themosis but not on this new one with 2.0.

Defining templates in config/templates
```
return [
    'custom-template' => [__('Custom Template', THEME_TD), ['page']],
    'login' => [__('Login Page', THEME_TD), ['page']],
    'registration' => [__('Register Page', THEME_TD), ['page']],
];
```
routes defined in routes/web.php

```
Route::get('front', 'AppController@front');
Route::any('template', ['registration', 'uses' => 'AppController@register']);
Route::any('template', ['login', 'uses' => 'AppController@login']);
```

AppController.php
```
    public function front() {
      return view('pages.front');
    }
    public function login() {
      return view('pages.login');
    }
    public function register() {
      if(is_user_logged_in()) {
         // do something
      } else {
        return view('pages.register');
      }
    }
```

**Comment by jlambe** [comment]
The issue has been fixed with `2.0-beta3` release. Update the core framework package and it should work as expected.
