### ISSUE TITLE
How to extend Forms and Fields

### ISSUE THREAD

**Issue by twosg** [themosis/themosis#261]
Asked shorty, what is the recommended way to add or extend functionality of the Themosis classes?

Longer version:

https://framework.themosis.com/docs/2.0/form/#organizing-form-fields
The grouping is already a helpful feature, but I would like to add

1) Custom fields

Instead of ```->add($fields->text('telefon', [
			    'group' => 'company',
			    'label' => 'Telefon',
			    'rules' => 'required',
]))```
I would like to do something like this:
`->add($fields->telephone())`

And the telephone field type contains already all default properties.

2) Especially for the Bootstrap4 use, I want to wrap two fields within one row. Like ZIP + Town/City for example. Thought on something like this:

`->add($fields->wrapperStart()) //would add class="row"`
`->add($fields->text('zip', ['attributes'=>['class'=>'col-4']]))`
`->add($fields->text('city', ['attributes'=>['class'=>'col-8']]))`
`->add($fields->wrapperEnd()) //end "row"`

**Comment by jlambe** [comment]
There are ways to build custom fields but a full API has not yet been given. I encourage you to check the source code on the `Forms/Fields/Types` to see how core fields are built.

You won't be able to use the `Field` factory class yet has there are no method defined to call a custom field from it but instead, you can directly instantiate your custom field like so:

```php
->add((new CustomField('telephon'))->setOptions([...]))
->add(...)
```

To build a field, you need to extend the `BaseType` class for groundwork and fully implement the `FieldTypeInterface`. Then provide a dedicated view for the html of your field.
