### ISSUE TITLE
Field Documentation Error

### ISSUE THREAD

**Issue by jgoslinga** [themosis/themosis#263]
I just want to say I really enjoy this framework! 

I realize that you are still working on the documentation for 2.0 but there's an issue in the Fields documentation.

You have it correct in the Fields list but the documentation still reflects using the old Field::select().

For anyone having issues with ``` Field::select()``` throwing an exception change it to ```Field::choice()```. 

Thanks again for creating such a wonderful framework.

**Comment by jlambe** [comment]
Thanks for this report. Yes I currently stop the field doc right after the list, I should have moved the warning about the docs there to avoid confusion with the old information. Yes, the select field is part of the new "choice" field. If you need to pass a list a list of options, you need to provide a `choices` property like so:

```php
Field::choice('color', [
    'choices' => [
        'red',
        'green',
        'blue'
    ]
]);
```

If you need a multiple select, pass the `multiple` property and set it to `true`.

The documentation is planned to be completed for stable release of 2.0.

**Comment by jgoslinga** [comment]
One other question, has the infinite field not been implemented? I can't find anything in the Themosis\Field\Factory class so am I right to think that it's currently not available.

**Comment by jlambe** [comment]
@jgoslinga Yes the infinite field has not yet been ported to the 2.0 release. You can read about it here: https://blog.themosis.com/2019/02/06/state-of-the-themosis-framework/
