### ISSUE TITLE
My Created page not showing my blade content 2.0 beta 3

### ISSUE THREAD

**Issue by YassineBenaziz** [themosis/themosis#264]
I want to create a page with custom html, so I created my blade view , and then my View and Page instances,  but when I try to show my page, i got empty canvas like so : 

![canvas](https://user-images.githubusercontent.com/7352492/53489506-a71ee700-3a91-11e9-8a9d-842947a2952f.png)

This is my code : 

/ressources/view/admin/sites.blade.php

`

    // Custom HTML content

    <div> Custom HTML content </div>
    <div> Custom HTML content </div>
    <div> Custom HTML content </div>

`

         $page_view = View::make('admin.sites');

         Page::make('press_release', __("Press Release"),null,$page_view)
            ->setCapability('manage_options')
            ->setIcon('dashicons-admin-site')
            ->setPosition(1)
            ->setMenu(__("Press Release"))
            ->set();

**Comment by YassineBenaziz** [comment]
I see that it does not review my page which is in:   /resources/views/admin/sites.blade.php   but the one that is in :     vendor/themosis/framework/src/Page/views/themosis/pages/default/page.blade.php

**Comment by jlambe** [comment]
@YassineBenaziz In order to build a custom page, there is now a "kind of" routing system available on pages:

```php
$page = Page::make(...);

$page->route('/', 'App\Http\Controllers\MyControllerClass@method');
```

Then from the controller method you can do some logic and at the end return a view instance.

The `route` method only support by default a `GET` request. If you want to handle `POST` request, you can pass a third argument `post` and you can separate the logic on each request.

> Note: the documentation is not yet ready and the page route is a WordPress hook "trick" somehow. Basically the post request is listening to an action hook from the `admin-post.php` file...

**Comment by YassineBenaziz** [comment]
@jlambe Thank you for your reply. I tried to do that,  but it always returns me the page that is in the vendor.
Should I call the set() method when  creating the a Page like so :  Page::make(...)->set() ? 

For the routing system, the '/' means that I should reach / int the browser to get my page ? because I do it like so : /cms/wp-admin/admin.php?page=press_release

And my Controller method and my function seems not to be running

I'm lost , can u give me an exemple of use please ? 

Thank you

**Comment by jlambe** [comment]
Here is an example:

```php
use Illuminate\Support\Facades\View;
use Themosis\Support\Facades\Page;

$page = Page::make('my-page', 'Page Title')
            ->set();

$page->route('/', function () {
    return View::make('admin.home');
});
```

The `/` is simply referencing the default page request URL but not specifically the admin home request. The first parameter is not an URI to define but what WordPress call has an `action`. The `/ ` action is referencing the following URL: `domain.com/cms/wp-admin/admin.php?page=my-page`.

If you define a second route with an `action` of `settings` for example:

```php
$page->route('settings', function () {
    return View::make('admin.settings');
});
```

The page is accessible on the following URL: `domain.com/cms/wp-admin/admin.php?page=my-page&action=settings`

The `action` query variable is the element controlling the admin page routing.

In the case of a POST request, the `action` value must be sent during the request in order for the routing to detect it. But as you can add multiple pages, the post action value is a combined value to avoid conflicts between pages. The action value is used inside the `admin-post.php` file to execute code for specific requests and a form for an admin post request should always send request to the `admin-post.php` file.

When building a form from an admin page to send a POST request, your form must have an `action` input with it like so:

```php
<form action="{{ admin_url('admin-post.php') }}" method="post">
    <input type="hidden" name="action" value="{{ $__page->getAction('register') }}">
    ...
</form>
```

Each page view receives by default the page instance under the `$__page` variable. Use the `getAction` method to generate the correct action value.

The route for then managing the request from above example would then be:

```php
$page->route('register', function () {
    // Do some logic... and redirect back to one of your page
    
    wp_safe_redirect(add_query_arg([
        'page' => 'my-page'
    ], admin_url('admin.php')));
    exit();
}, 'post');
```

**Comment by YassineBenaziz** [comment]
@jlambe  Thank you very much, it works very well
