### ISSUE TITLE
Create Hooks inside theme

### ISSUE THREAD

**Issue by YassineBenaziz** [themosis/themosis#266]
Hello everybody,

How can I create Hook inside the theme and triggered it when the WordPress hook API is loaded ? 

I'm working on 2.0-beta3

**Comment by YassineBenaziz** [comment]
@jlambe Hello

Thank you for your quick reply

Tell me if I'm wrong, what I understand is that Hooks on stack root are executed before that all WordPress APIs are loaded ?

**Comment by jlambe** [comment]
@YassineBenaziz Hook classes are called right after all WordPress APIs are loaded, think of it as a `mu-plugin`. So it runs before plugins from the `plugins` directory and the theme.

**Comment by YassineBenaziz** [comment]
@jlambe ok I see, Thank you for your explanation

**Comment by YassineBenaziz** [comment]
So, in this case I can't use  PostType Class, because it should be registred inside a hookable class.
Is there another way to register my new PostType  ?

**Comment by jlambe** [comment]
@YassineBenaziz You can call the `PostType` class anywhere you want. Normally it should not happen that you register a custom post type inside your theme, it is best at application root through a Hook class or through a plugin.

Your custom post type should be very very tight to your theme to define it there. So if you want to create a custom post type from your theme (which I no longer recommend), you can simply create a file inside the `inc` directory and call the `PostType` class from there. Files inside the `inc` directory are autoloaded and you can nest directories as well.

**Comment by YassineBenaziz** [comment]
@jlambe  , yes because of my custom post type is related directly with my theme. I have already create my class and call it from template-functions.php which is located in the inc directory.

Thank you for your help
