### ISSUE TITLE
Themosis 2.0-beta3 Rank Math plugin issue.

### ISSUE THREAD

**Issue by krzjablonski** [themosis/themosis#267]
Hi!

I've just installed Rank Math plugin v 1.0.20 and when I try to edit page or create a new one page doesn't load. I get a notice, and all appropriate html tags are getting 'hide-if-no-js' class. When I disable guttenberg I can see edit screen but options for Rank Math are broken.
![image](https://user-images.githubusercontent.com/40863404/53964013-b97ecd80-40ee-11e9-9bb0-8ac74e3c1678.png)

**Comment by jlambe** [comment]
And what about the issue you have on screen ? seems like your plugin is using another as a dependency and is calling a deprecated function. It doesn't seem to be related to the framework especially when the framework does not change the default WordPress behavior. Have you tried to fix the plugin issue ?

**Comment by krzjablonski** [comment]
Hi @jlambe 

Thanks for your answer. The problem is that the same plugin works perfectly fine on fresh, "standard" installation of wordpress (the same versions), but do not work with Themosis :-(

**Comment by jlambe** [comment]
This is because by default the framework catch all errors as exceptions and this stop the PHP process for local development. The plugin might have a PHP warning issue that standard WordPress let pass through. Try to set the `APP_DEBUG=false` in your `.env` file and see if it works as expected.

**Comment by krzjablonski** [comment]
@jlambe i've tried that with no results. What I did was deleting vendor folder and running `composer install` once more, and it solved problem...

Thanks for your support, I really appreciate it :-)
