### ISSUE TITLE
Error Argument 1 passed to Themosis\Core\ThemeManager::getPath() must be of the type string, null given

### ISSUE THREAD

**Issue by Pavel-Mukha** [themosis/themosis#268]
Hello, immediately after installing the framework and the theme as well as installing the wordpress, I press the login and get the following error - Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Argument 1 passed to Themosis\Core\ThemeManager::getPath() must be of the type string, null given, 
called in /var/www/themosis.loc/htdocs/content/themes/my-theme/functions.php on line 31

http://joxi.ru/brRxoXt77nn421 - here screenshot

Why does this error occur?

my software
PHP 7.3.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:31:26) ( NTS )

Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03

OS: Mint 18.3 sylvia
Kernel: x86_64 Linux 4.15.0-46-generic

**Comment by Pavel-Mukha** [comment]
http://joxi.ru/brRxoXt77nn421 - here screenshot

**Comment by Pavel-Mukha** [comment]
I suspect that there is not enough of a module for apache2

**Comment by jlambe** [comment]
Hi!

Which version of the framework are you using ? It seems that you're on one of the first beta version. May I suggest you to install the release candidate and try again:

```php
composer create-project themosis/themosis your-project-name 2.0-RC1
```

Also, note that the framework is bundled with the `Homestead` virtual machine with all necessary requirements for the application. It might easier than looking after a missing apache module.

**Comment by Pavel-Mukha** [comment]
Now everything works great, thank you.
I do not understand where you took such a suffix 2.0-RC, revised the documentation and I did not find this :)

I installed from the documentation page - http://joxi.ru/p27YyqCKKD9Jr7

**Comment by jlambe** [comment]
I haven't yet announced the release candidate release officially ;)

Regarding debugging functions like `dd()` or `dump()`, it is now part of the `symfony/var-dumper` package. By default, it is installed as a required-dev dependency so you have access to those helper functions on your local development.

**Comment by Pavel-Mukha** [comment]
super thank you, you have created a wonderful software :)
