### ISSUE TITLE
Oops! That page can’t be found.

### ISSUE THREAD

**Issue by baryaz** [themosis/themosis#274]
Hi,
I created a page of test and I get this when I click on the menu of this page 

`Oops! That page can’t be found.`

the same thing when I try to view the article.

Sincerely.

**Comment by jlambe** [comment]
You probably haven't defined routes for your WordPress page. Try to add this on your `routes/web.php` file:

```php
Route::get('page', function () {
    return 'My Page';
});
```

See the routing guide for details on how to listen to requests done to your application: https://framework.themosis.com/docs/2.0/routing/

**Comment by baryaz** [comment]
but i want to return the page created on backoffice wordpress

**Comment by jlambe** [comment]
Then simply return a view (html) where you define the classic WordPress loop or use any of the provided helpers and display the page content.

```php
Route::get('page', function () {
    return view('pages.default');
});
```

The `pages.default` is provided inside the theme `views` directory.

Please read the documentation on routing and views:
- https://framework.themosis.com/docs/2.0/routing/
- https://framework.themosis.com/docs/2.0/views/

**Comment by baryaz** [comment]
thank you so mutch, i have two more questions : 
1 - what is the difference between [my-proj/resources/views] and and the view on my theme [my-proj/htdocs/content/themes/first-theme/views],
2 - if i create a view on a plugin how to display it inside a view of my theme first-theme.

Sincerely.

**Comment by jlambe** [comment]
Most is explained in the application structure documentation:
- https://framework.themosis.com/docs/2.0/structure/

You can reference any views from anywhere by specifying their path `my.plugin.view` is looking after a view stored inside the `my/plugin` directory from one of the registered views directory.
