### ISSUE TITLE
Metabox are rendered, but without any fields in it

### ISSUE THREAD

**Issue by jminguely** [themosis/themosis#277]
Hello !

Thanks for your work and this framework. I really like to work with it.

I've recently had an issue with the metaboxes. I've created a custom post type with a metabox and a few field in it:

```php
// File stored in resources/admin/books.php
$members = PostType::make('members', 'Members', 'Member')->set([
  'public'        => true,
  'menu_position' => 20,
  'supports'      => ['title'],
  'rewrite'       => false,
  'query_var'     => false
]);

Metabox::make('Informations', 'members')->set([
  Field::text('name'),
  Field::text('phone'),
  Field::textarea('address')
]);
```

The Custom Post type is created, the metabox is even rendered for this post type. But the content of the Metabox is empty:

![Capture d’écran 2019-03-23 à 17 46 36](https://user-images.githubusercontent.com/2260030/54869073-fbb53980-4d93-11e9-8e5d-4ca3bfaa37f4.png)

I've experienced this issue on two projects, one was on version `2.0-beta3` and the other was updated on version `2.0-RC1` without any success.

Thanks for your help / support !

**Comment by jlambe** [comment]
Hi @jminguely, the documentation has been updated regarding metabox and custom fields.

There is a new API and you no longer pass a list of custom fields to a metabox through its `set` method but instead call the `add` method:

- https://framework.themosis.com/docs/2.0/metabox/#custom-fields

```php
Metabox::make('Informations', 'members')
    ->add(Field::text('name'))
    ->add(Field::text('phone'))
    ->add(Field::textarea('address'))
    ->set();
```

**Comment by jminguely** [comment]
Okay, thanks for your support. It works with basic field (text, editor, integer, password), but I get a blank box when adding one of the following field type:

```php
Metabox::make('properties', 'members')
->add(Field::media('image'))
->set();
```

```php
Metabox::make('properties', 'members')
->add(Field::collection('gallery'))
->set();
```

**Comment by jlambe** [comment]
Probably the media assets are not loaded. Can you check your `app/Hooks/Application.php` file and see if you have the call to `wp_enqueue_media()` like in this file:

https://github.com/themosis/themosis/blob/master/app/Hooks/Application.php#L115

If so, can you provide the JS console error message if any ?

**Comment by jminguely** [comment]
Once again, thanks a lot for your quick support.

Great job on this framework. I can't wait to be more effective with it and to start to contribute!

J

**Comment by spagi** [comment]
Hello, I have same issue with new API
`$membership = PostType::make('membership', 'Membership', 'Memebership')
			->setArguments([
				'public' => true,
				'menu_position' => 20,
				'supports' => ['title', 'editor'],
				'rewrite' => false,
				'query_var' => true,
				'menu_icon' => 'dashicons-groups'
			])->set();
		$membership->status([
			'trial',
			'active',
			'expired'
		]);

		 Metabox::make('informations', 'membership')
			->setTitle(_x('Membership details', 'metabox', 'textdomain'))
			->setContext('side')
			->add(Field::text('price',['label' => 'Price']))
			->set();
`

**Comment by spagi** [comment]
Hi, I have same issue with new api
`$membership = PostType::make('membership', 'Membership', 'Memebership')
			->setArguments([
				'public' => true,
				'menu_position' => 20,
				'supports' => ['title', 'editor'],
				'rewrite' => false,
				'query_var' => true,
				'menu_icon' => 'dashicons-groups'
			])->set();
		$membership->status([
			'trial',
			'active',
			'expired'
		]);`

		 `Metabox::make('informations', 'membership')
			->setTitle(_x('Membership details', 'metabox', 'textdomain'))
			->setContext('side')
			->add(Field::text('price',['label' => 'Price']))
			->set();`
`

**Comment by jminguely** [comment]
hello,

you seem to have a typo in your code. If I remove the extra backtick ``(`)`` in your code it seems to work on my version of themosis `2.0.1`:
here:
```
])->set();`
```

**Comment by spagi** [comment]
Thax for response, but the backtick is not the problem :(
Here is my Membersip class can you check it please?

```php


namespace App\Hooks;


use Themosis\Hook\Hookable;
use Themosis\Support\Facades\PostType;
use Themosis\Support\Facades\Metabox;
use Themosis\Support\Facades\Field;



class Membership extends Hookable {

	/**
	 * Widgets action hook.
	 *
	 * @var string
	 */
	public $hook = 'init';

	/**
	 * Register membership post type
	 */
	public function register() {

		$membership = PostType::make('membership', 'Membership', 'Memebership')
			->setArguments([
				'public' => true,
				'menu_position' => 20,
				'supports' => ['title', 'editor','page-attributes'],
				'rewrite' => false,
				'query_var' => true,
				'menu_icon' => 'dashicons-groups'
			])->set();
		$membership->status([
			'trial',
			'active',
			'expired'
		]);

		Metabox::make('informations', 'membership')
			->setTitle(_x('Membership details', 'metabox', 'textdomain'))
			->setContext('side')
			->add(Field::text('price',['label' => 'Price']))
			->set();




	}

}
```

**Comment by jminguely** [comment]
@spagi : What version of themosis are you using? Your code is working on my local installation of a `2.0.2` themosis framework.

**Comment by romainhe** [comment]
Hi! Someone have this code working on 2.0.6 themosis framework ? @jminguely 

thx for help !
