### ISSUE TITLE
Cache-Control headers alway no-cache, private

### ISSUE THREAD

**Issue by johnnypea** [themosis/themosis#278]
Any reason why Response headers are always "no-cache, private"? I tested with fresh framework and theme install as well.

I had to create middleware like this to override it:
```php
namespace App\Http\Middleware;

use Closure;

/**
 * Class Varnish
 * @package App\Http\Middleware
 */
class Varnish
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        $response->header('Cache-Control', 'public');

        return $response;
    }
}
```

Thank you.

**Comment by jlambe** [comment]
No particular reason, looking at source code, it seems that the `Response` instance is setting this as the default if no custom `Cache-Control` header has been defined.

This can probably be investigated more in depth.
