### ISSUE TITLE
THEMOSIS_ROOT in tests/bootstrap.php is incorrect

### ISSUE THREAD

**Issue by yanmorinokamca** [themosis/themosis#279]
While testing models and themosis $app with phpunit, I found that constant THEMOSIS_ROOT use the incorrect path.
Inside tests/bootstrap.php, the themosis root path should use  `__DIR__.'/../'` like the vendor path.

line 12:
`define('THEMOSIS_ROOT', realpath(__DIR__.'/../'));`

It seems to be the same in develop, next and master git branches.

Thanks for themosis.

**Comment by jlambe** [comment]
Thanks for catching this one. I'm going to update it right away.
