### ISSUE TITLE
Custom Post Type Implementation example ?

### ISSUE THREAD

**Issue by maximusblade** [themosis/themosis#280]
Hi

Is there somewhere I can see a working example of a Post Type implementation.

I am using the example in the documentation
https://framework.themosis.com/docs/2.0/posttype/

With no results. Post type does not appear in Dashboard menu.

Thanks in advance.

**Comment by jlambe** [comment]
Hi,

the example is using an `Hookable` class to register the post type from the root `app/Hooks` directory. Hookable classes are not automatically registered within the application, you need to add your hook class to the `hooks` property of the `config/app.php` file.

See the new Hooks guide for more details: https://framework.themosis.com/docs/2.0/hooks/

Hope this helps.

**Comment by maximusblade** [comment]
Brilliant.
It makes sense now.
Thank you!
