### ISSUE TITLE
multisite subdomain Home Page redirects to Primary domain Home Page - Asset URL issue

### ISSUE THREAD

**Issue by besrabasant** [themosis/themosis#282]
## Problem
I have an issue with accessing the **homepage** of my subdomains in my multi-site installation. My multi-site is subdomain-based.

## Expected
The main site **Home Page** has to be accessed from:
site: `themosis.project`

The subdomain has to be accessed from:
site: `subdomain.themosis.project`

## Behavior
When I try to access my subdomain `subdomain.themosis.project`, I get redirected to my main site `themosis.project`.  
But when I access the admin for my subdomain under 'subdomain.themosis.project/cms/wp-admin' or any other URL under my subdomain, it works. 
I can only access the subdomain under `subdomain.themosis.project/cms` which is not the intended URL. 

I have just issue with accessing the Home page on my subdomain site.

**Comment by Jaspervv** [comment]
is your  `.env` set correctly?  Are the values set correctly in the database's 'wp_options` table?

**Comment by besrabasant** [comment]
Yes.

here's my **.env**
```
---
APP_URL=http://themosis.project
WP_URL=http://themosis.project/cms
DOMAIN_CURRENT_SITE=themosis.project
---
```

**Comment by besrabasant** [comment]
Ok, So I looked into the issue. I made a clean **WP Bedrock Multisite** installation and it works fine. I am using *Valet* to serve my site. Now when I stop the script execution in the Valet Driver for Wordpress, I still get redirected to my **Primary Site** which should not be as expected.

**Comment by Jaspervv** [comment]
@besrabasant have you tried flushing your DNS and clearing your browser cache? (possibly the redirect is being cached)

**Comment by besrabasant** [comment]
@Jaspervv yes. I have already tried that.

**Comment by jlambe** [comment]
Hi @besrabasant,

I've just tested a fresh 2.0 mutlisite installation and unfortunately, I don't have a redirect from the subdomain to the main one.

But I do have an issue on the admin side where WordPress seems to not find core assets (js, css). I fixed it by adding the following filters on the `App\Hooks\Application.php` class:

```php
Filter::add('network_admin_url', function ($url) {
    return $this->formatUrl($url);
});

Filter::add('admin_url', function ($url) {
    return $this->formatUrl($url);
});

Filter::add('includes_url', function ($url) {
    return $this->formatUrl($url, WPINC);
});

// Here is the new filter to return correct URL
Filter::add(['style_loader_src', 'script_loader_src'], function ($url) {
    if (strrpos($url, 'wp-admin') !== false) {
        return $this->formatUrl($url);
    }

    return $this->formatUrl($url, WPINC);
});
```

My setup is simple, generate a Homestead configuration file upon project creation, defined an additional subdomain, run the multisite installation as found in the documentation and everything seems to work smoothly except the broken URLs (fix above).

- Homestead official documentation: https://laravel.com/docs/5.8/homestead
- Multisite installation: https://framework.themosis.com/docs/2.0/multisite/

**Comment by besrabasant** [comment]
Finally got this working. I due to a misconfiguration in **laravel/valet**.

I had to add a [Multisite Driver](https://gist.github.com/besrabasant/ffad5a5c20afa6c5ff5d35f402daaf46) to **laravel/valet**.
