### ISSUE TITLE
How to set up on shared hosting

### ISSUE THREAD

**Issue by KevinBatdorf** [themosis/themosis#285]
I haven't attempted this yet but is there a path to getting 2.0 to work in a shared hosting environment? With 1.3 it doesn't take much to move it to a shared hosting but the way 2.0 is set up it might 

The reason I ask is I often work with designers who handle the clients. I always develop on a Digital Ocean VPS which works fine, but every now and then there's a client who wants to use GoDaddy or WP Engine for some reason.

**Comment by jlambe** [comment]
@KevinBatdorf I haven't tested but yes it is much harder or probably impossible to make the 2.0 version work on a shared hosting. Previously you could somehow get access to the APIs by installing the core framework as a plugin and go with it. Now it's no longer the case. You'll go with a lot of refactoring to make it work on a shared hosting or at least on one that do not allow a "public/htdocs" directory structure.

**Comment by KevinBatdorf** [comment]
@jlambe Not sure I'll have time soon but I'll see if there's some obscure way to even just get it working. Then maybe there can be a console command to wrap it up and nice and neat. For me anyway development usually stops at that point so workflow isn't important. 

If I figure something out I'll share it here.

Thanks

**Comment by jlambe** [comment]
I'm going to close this in the meantime.
