### ISSUE TITLE
No Infinite field in version 2.0

### ISSUE THREAD

**Issue by dimitriBouteille** [themosis/themosis#287]
Why they are no Infinite field in version 2.0 ? 
https://framework.themosis.com/docs/1.3/field/#infinite-field

**Comment by jbfournot** [comment]
Hello again @dimitriBouteille 
As mentioned in the documentation, unfortunately, the repeater field (or infinite field) is not available in the 2.0 and not scheduled for the next releases. (see the issue #524)

**Comment by jlambe** [comment]
@dimitriBouteille The infinite field has been removed for 2.0 release. It will be included back at some point but can't give you a date for a release. The field must be refactored completely. You can read more about this here: https://blog.themosis.com/2019/02/06/state-of-the-themosis-framework/
