### ISSUE TITLE
Attributes key don't work in Field::text

### ISSUE THREAD

**Issue by dimitriBouteille** [themosis/themosis#288]
I tried to add the "attributes" property to a text field (Field::text) , but it doesn’t work in version 2.0 :(

```
$slides = PostType::make(...);

Metabox::make('slide', $slides->getName())
            ->setTitle('Un slide')
            ->add(Field::text('title', [
                'label' => 'Titre du slide',
                'attributes' => [
                    'id' => 'demo-id',
                    'class' => 'custom-demo',
                    'required'
                ]
            ]))
...
```

**Comment by jbfournot** [comment]
Hello @dimitriBouteille 
You can use the method `setAttributes(array $attributes)`.
```php
Field::text('title')->setAttributes(['id' => 'demo-id', 'required' => true]);

**Comment by jlambe** [comment]
@dimitriBouteille After testing, fields attibutes are missing when used within a metabox. Your code is correct but I completely forget to take these into account.

**Comment by jlambe** [comment]
@dimitriBouteille Can you close the issue here and move it to the `themosis/framework` repository so we can track it ? Thanks.
