### ISSUE TITLE
How do you use socialite on themosis

### ISSUE THREAD

**Issue by rovillesarate** [themosis/themosis#291]
Hi! How do you use socialite on themosis? Is socialite already included on themosis or do I still need to add it via composer? If so, How do I use it?

**Comment by rovillesarate** [comment]
I have already included socialite via composer.

`composer require laravel/socialite`

On the socialite documentation, it says that I need to add credentials on config/services.php

Do I need to make a services.php inside themosis config directory?

**Comment by jlambe** [comment]
It is not included by default but as many Laravel packages, you install it through composer, add its service provider and if it needs configuration files like `services.php`, add it to your root `config` directory with appropriate options.

**Comment by rovillesarate** [comment]
I have already made it work. but I'm currently figuring out how to use it for two types of users. they can log in and be registered on their particular user type. Trying to use the scope as the parameter to check if is a vendor or a client.

As for the customer class. how do you verify if the email is already listed on the database?

**Comment by rovillesarate** [comment]
How do you authenticate a user that is already included in the customer's database when using Socialite?

`use Laravel\Socialite\Facades\Socialite;

class SocialController extends Controller
{
    public function redirect($provider)
    {
     return Socialite::driver($provider)->redirect();
    }

    public function shop_redirect($provider)
    {
     return Socialite::driver($provider)->with(['state' => '5'])->redirect();
    }

    public function Callback($provider){
        $userSocial =   Socialite::driver($provider)->stateless()->user();


        $state = htmlspecialchars($_GET["state"]);
        if ( $state == 5 ) :
        	$cust_type = 'vendor';
        else :
        	$cust_type = 'customer';
        endif;

        $customerController = new CustomerController;

        $email = $userSocial->getEmail();
        $emails = $customerController->check_email();
        if ($emails) :
	        if (in_array($email, $emails)) :
			    // How do I login? What class should I use
			endif;
		else :
			$customer = Customer::create([
		            'name' => $userSocial->getName(),
		            'email' => $userSocial->getEmail(),
		            'image' => $userSocial->getAvatar(),
				    'provider_id'   => $userSocial->getId(),
				    'provider'      => $provider,
		            'password' => wp_generate_password(),
		            'email_verified_at' => date('Y-m-d H:i:s'),
		            'cust_type'		=> $cust_type
		        ]);

			$name = trim($userSocial->getName());
		    $last_name = (strpos($name, ' ') === false) ? '' : preg_replace('#.*\s([\w-]*)$#', '$1', $name);
		    $first_name = trim( preg_replace('#'.$last_name.'#', '', $name ) );
			return redirect('account');	
		endif;

	}
}`

**Comment by jlambe** [comment]
@rovillesarate The framework provides a default authentication system where a customer can be registered and can log in by using its email address and a password.

If you're looking to authenticate customers using a social network authentication, the default customer database schema is not ready for it, meaning that you have to add a column to store the social network user id for example at registration and then when logging in, you only compare the retrieved user id with the stored id.

This means that you have to change the default auth controllers for registration, the `RegisterController`and the controller for logging in with the `LoginController` both installed inside the `app/Http/Controllers/Auth` directory:

Here is the guide to enable default auth with Themosis:
https://framework.themosis.com/docs/2.0/authentication/

And here is a link to Laracast video example (perhaps you need to subscribe to their channel):
https://laracasts.com/series/laravel-authentication-techniques/episodes/2
