### ISSUE TITLE
Custom Routing for SubMenu Page

### ISSUE THREAD

**Issue by rumur** [themosis/themosis#293]
Hi @jlambe 

Could you please tell if there is a way to make a custom routes work for SubMenu pages as well?
 
I didn't manage to find this in the doc - https://framework.themosis.com/docs/2.0/page/#page-routing

Right now, I can see that this functionality works only if the `Page` doesn't have a parent.

Not Working example:

```
$page = \Page::make('sub-menu-page', __('Sub Menu Page', APP_TD))
            ->setParent('tools.php')->set();

        $page->route('/', function () {
            return view('admin.layouts.tabs');
        }); 
```

Thanks.

**Comment by besrabasant** [comment]
I too am experiencing similar issues using **spaces** or **special character** like **&** in `setMenu()`

**Comment by jlambe** [comment]
@rumur normally I would have think that the page slug parameter of the subpage should be used on the `action`. I will test this, perhaps there is indeed an issue on this.

**Comment by besrabasant** [comment]
Well from my findings replacing `strtolower($parent->getMenu())` with `str_slug($parent->getMenu())` on line https://github.com/themosis/framework/blob/9931cdda709b94cc712495acf93211b6fa9d23a7/src/Page/Page.php#L397 fixes the issue.

**Comment by besrabasant** [comment]
So I tested adding subpages to all default WP Admin Pages and modified the function `findParentHook()` in https://github.com/themosis/framework/blob/9931cdda709b94cc712495acf93211b6fa9d23a7/src/Page/Page.php#L375 and replacing it with the code below works.

```
protected function findParentHook(): string
    {
        if (!$this->hasParent()) {
            return '';
        }

        // Check if parent attribute is attached to a custom post type or another page.
        if (false !== $pos = strpos($this->getParent(), 'post_type=')) {
            // Parent hook is equivalent to the post type slug value.
            if ('page' == substr($this->getParent(), $pos + 10)) {
                return 'pages';
            }
            return substr($this->getParent(), $pos + 10);

        } elseif ('edit.php' === trim($this->getParent(), '\/?&')) {
            // Parent is the default post post type.
            return 'posts';
        } elseif ('index.php' === trim($this->getParent(), '\/?&')) {
            return 'dashboard';
        } elseif ('upload.php' === trim($this->getParent(), '\/?&')) {
            return 'media';
        } elseif ('themes.php' === trim($this->getParent(), '\/?&')) {
            return 'appearance';
        } elseif ('tools.php' === trim($this->getParent(), '\/?&')) {
            return 'tools';
        } elseif ('edit-comments.php' === trim($this->getParent(), '\/?&')) {
            return 'comments';
        } elseif ('plugins.php' === trim($this->getParent(), '\/?&')) {
            return 'plugins';
        } elseif ('users.php' === trim($this->getParent(), '\/?&')) {
            return 'users';
        } elseif ('options-general.php' === trim($this->getParent(), '\/?&')) {
            return 'settings';
        }

        // The current page is attached to another one.
        $abstract = 'page.' . $this->getParent();

        if ($this->ui()->factory()->getContainer()->bound($abstract)) {
            // Parent hook is equivalent to the page menu as lowercase.
            $parent = $this->ui()->factory()->getContainer()->make($abstract);

            return \Illuminate\Support\Str::slug($parent->getMenu());
        }

        return '';
    }
```

**Comment by rumur** [comment]
Hi @jlambe !
I've noticed that you released the [2.0.2](https://blog.themosis.com/2019/05/22/themosis-framework-release-2-0-2-and-more/) where you said that the Admin Page Routing issue has been fixed, but is not.

It doesn't work for custom pages when you're trying to use the custom page as a Parent One.

Some Real example:

```php
<?php
/** @var Page $parent_page */
$parent_page = \Page::make('parent-page', __('Parent Settings', APP_TD))->set();

/** @var Page $sub_page */
$sub_page = \Page::make('sub-page-settings', __('Sub Page Settings', APP_TD))
            ->setParent($parent_page->getSlug())
            ->set();

/** @NOTE With Current bug you won't see the custom view !!!  */
$sub_page->route('/', function() {
  return view('replace.with.custom.view');
});

```

### With this bug you won't be able to see the custom view.

Why?

Because: `Themosis\Page\Page::findParentHook` returns `return strtolower($parent->getMenu());`
and in this case it's gonna be `parent settings`, but action for custom routes is listening to `parent-settings`.

### What am I suggesting to do here? 

just return the kebab string `return \Illuminate\Support\Str::kebab($parent->getMenu());`

**Comment by jlambe** [comment]
The `2.0.2` release has fixed the issue about core WordPress pages used as parent. The case here has not been treated because I simply forget it as it is in the `themosis/themosis` repository. Sorry for this :(

Can you open a ticket on the `themosis/framework` repository so I can set it for next minor release 2.0.3 ? Your solution seems to be good but I will investigate about the use of the page title as sub-page reference, it sounds odd to me as everything in WordPress is tied to "slugs".

Sorry again for having forget this issue 😭 Please open it on the other repository so I can better track it.

**Comment by rumur** [comment]
It's my bad too, bc I opened in diff repo.

One more thing to add, if I'm not mistaken if you use the `getSlug` instead of the `getMenu` it won't work either.

bc in this case `Themosis\Page\Page::registerRouteActions` is listening to this action `$this->action->add('load-'.$this->findParentHook().'_page_'.$this->getSlug(), [$this, 'parseGetRoute']);`
