### ISSUE TITLE
My Middelware not working well when I upgrade to themosis 2.0.1

### ISSUE THREAD

**Issue by YassineBenaziz** [themosis/themosis#294]
I have a problem on my middelware since when I upgrade to themosis 2.0.1. Actually I use juste the admin part of themosis, with an API that provide content to what I generate on the BackoOffice. 
So I use a middleware to stop all request that goes to the FO like so : 

`<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Request;
use Log;

class DenyFOAccess {
	/**
	 * @var
	 * path that comes after domain name
	 */
	private static $path;
	
	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  \Closure                 $next
	 *
	 * @return mixed
	 * redirect all FO routes to 404 view
	 * @throws \Illuminate\Container\EntryNotFoundException
	 */
	public function handle($request, Closure $next) {

		self::$path = Request::path();
		if (starts_with(self::$path, config('app.authorized-path'))) {
			return $next($request);
		}
		return response()->view('errors.404', [], 404);
	}
}
`

my middelware are not redirecting me to my custom 404 error page, but continue the execution and enter to the BO template views in my theme that I use. 
it's like this line does not work anymore : 

`return response()->view('errors.404', [], 404);`

And also my routes that are defined in the web.php file are no longer taken into consideration

Does someone have the same problem ? 

Thank you

**Comment by jlambe** [comment]
Hmm not sure, it seems that your "if" condition is perhaps not working as expected and is always returning `true`, making your front-office (FO?) accessible. Perhaps looking at the content of the request path and `app.authorized-path` configuration might give some hints ?

**Comment by YassineBenaziz** [comment]
this is the value of 	config('app.authorized-path') : 

`'authorized-path' => [
		'api' => env('API_PREFIX', 'api/'),
		'bo'  => env('BO_PREFIX', 'cms/'),
	],`

It's about my routing that not working very well. Even If I remove my middleware, and I just put a simple route in web.php like so : 
`Route::get('/', function () {
    return view('welcome');
});
`
This is not rendering my 'welcome' view  located in resources/views/welcome.blade.php, but its try to show the view in the theme located in : htdocs/content/themes/my-theme/views/pages/errors/404.blade.php. 

The file route.php located in the theme is empty. And this is my app/http/Kernel.php file : 

`<?php

namespace App\Http;

use Themosis\Core\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        'denyFO' => \App\Http\Middleware\DenyFOAccess::class
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            'wp.bindings',
            'bindings',
            \Illuminate\Session\Middleware\StartSession::class
        ],
        'api' => [
            'wp.can:edit_posts',
            'bindings'
        ],
        'apiFS' => [
            /*'throttle:60,1',*/
            'bindings',
            'api.basic.auth'
        ]
    ];

    /**
     * The application's route middleware.
     * Aliased middleware. Can be used individually or within groups.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'wp.bindings' => \Themosis\Route\Middleware\WordPressBindings::class,
        'wp.can' => \Themosis\Route\Middleware\WordPressAuthorize::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'api.basic.auth' => \App\Http\Middleware\APIAuth::class
    ];
}
`

And this is my app/Providers/RouteServiceProvider.php file  : 
`<?php

namespace App\Providers;

use Themosis\Core\Support\Providers\RouteServiceProvider as RouteProvider;
use Themosis\Support\Facades\Route;

class RouteServiceProvider extends RouteProvider
{
    /**
     * Main controllers namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    public function boot()
    {
        parent::boot();
    }

    /**
     * Register application main routes.
     */
    public function map()
    {
        $this->mapWebRoutes();
        $this->mapApiRoutes();

    }

    /**
     * Define the "web" routes for the application.
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }

    /**
     * Define the "api" routes for the application.
     */
    protected function mapApiRoutes()
    {
        Route::middleware('apiFS')
            ->prefix('api')
            ->namespace($this->namespace)
            ->group(base_path('routes/api.php'));
    }
}
`

**Comment by jlambe** [comment]
The list of middlewares have changed on release 2.0 since the beta releases. Looks like your `Kernel` class is lightweight compared to latest release. Try to update it by following this file:
- https://github.com/themosis/themosis/blob/2.0/app/Http/Kernel.php

**Comment by YassineBenaziz** [comment]
I updated my kernel when I passed to the release 2.0, but I still have the problem, so I roll back to the 2.0-beta3
