### ISSUE TITLE
Sharing data for all the views

### ISSUE THREAD

**Issue by johnnypea** [themosis/themosis#295]
1) Does `View::share()` works with `@include` statement in Blade engine templates?

2) I would like to apply a custom view composer for all the views. Is this possible?

Thank you.

**Comment by jlambe** [comment]
1. Yes, normally it works for views called by the `@include` statement as well.
2. Yes. The best location is inside a service provider or a Hookable class if you need WordPress functions as well.

**Comment by johnnypea** [comment]
@jlambe thanks. But how can I use a composer for all the views in my application? Do I have to define each one of them or is there some generic statement?

**Comment by jlambe** [comment]
@johnnypea Looking at the [official documentation](https://laravel.com/docs/5.8/views#view-composers), you can pass a wildcard character to define a view composer for all views like so:

```php
View::composer('*', function ($view) {
    // Your code here...
});
```
