### ISSUE TITLE
Sharing data to all views and WP functions

### ISSUE THREAD

**Issue by palicko** [themosis/themosis#296]
Hi,

I need to pass some data to all views, but I get `Call to undefined function home_url()` fatal error (It is same for all WP or theme functions).

I'm adding this to my `routes.php`.
```
View::share([
    'global_data' => [
        'site_url' => home_url('/'),
    ],
]);
```

What is the logic behind and how can I fix it or is there other way to pass those data? `View::composer()` is not really usable, because I would need to include all those views one by one.

Thanks.

**Comment by jlambe** [comment]
It depends on where you define your call to the `View::share` method. If it is inside a service provider stored inside the `app` directory, it is called too early. WordPress functions are not yet included.

You could call it from a [Hookable](https://framework.themosis.com/docs/2.0/hooks/) class or from a service provider defined under a custom plugin or inside your theme.

**Comment by Jaspervv** [comment]
As Julien mentioned in [another issue](https://github.com/themosis/themosis/issues/295#issuecomment-493161232), according to the [Laravel documentation](https://laravel.com/docs/5.8/views#view-composers) you can share data with all views using a wildcard character like so:
```php
View::composer('*', function ($view) {
    $view->with('hello', 'world');
});
```
