### ISSUE TITLE
WooCommerce script "wc-add-to-cart-variation" not loaded

### ISSUE THREAD

**Issue by VlooMan** [themosis/themosis#297]
When displaying a variable product the function which is hoked to standard WooCommerce hooks looks like this before loading the template.

```
function woocommerce_variable_add_to_cart() {
	global $product;

	// Enqueue variation scripts.
	wp_enqueue_script( 'wc-add-to-cart-variation' );

	...

	// Load the template.
	wc_get_template( ... );
}
```

The "wc-add-to-cart-variation" script however never gets loaded on single product detail when the product is set to have multiple variations.

Any idea how to ensure these scripts are loaded correctly whenever needed?

**Comment by jlambe** [comment]
I would say that from your controller handling the requests to single products pages, you can enqueue the script as well.

You can call the core function like in your sample: `wp_enqueue_script('wc-add-to-cart-variation')` as WooCommerce has already registered the asset.

Or isn't there a missing hook from the template ? Perhaps the default documentation is missing a `do_action` for variable products ?!

**Comment by SanderMuller** [comment]
For anyone else that runs into this, it's correct that the `wc-add-to-cart-variation` has to be queued by the theme, I made product variations work by adding an action to queue the script using the Action facade supplied by Themosis:
```
Themosis\Support\Facades\Action::add('wp_enqueue_scripts', function (): void {
    wp_enqueue_script('wc-add-to-cart-variation');
});
```

This block of code can be added to a register method of a service provider.
