### ISSUE TITLE
Custom fields showing for all taxonomies

### ISSUE THREAD

**Issue by msufiannasir** [themosis/themosis#298]
I have created a couple of custom fields for a custom taxonomy but that field is showing for all taxonomies. It should only show fields for specific taxonomy not for all. Any help would be appreciated.

**Comment by jlambe** [comment]
Hi,
can you provide a code snippet with your taxonomy custom fields definition so we can test it as well ?

**Comment by msufiannasir** [comment]
Here you go

Metabox::make('Areas-Fields', 'areas')
        ->add(Field::text('rss_title'))
        ->add(Field::collection('button_icon', [
                                'label' => 'Area Icon',
                                'limit' => 1,
        ]))
        ->set();

**Comment by msufiannasir** [comment]
Let me know if you were able to reproduce the issue?

**Comment by jlambe** [comment]
@msufiannasir Sorry for late answer but after testing, there is indeed an issue with the taxonomy fields. In order to better track the issue, could open an issue for this on the `themosis/framework` repository instead:

- https://github.com/themosis/framework/issues

Thanks

**Comment by jlambe** [comment]
I'm closing this issue. Please follow this one:
- https://github.com/themosis/framework/issues/674

**Comment by jlambe** [comment]
@msufiannasir Current `themosis/framework` `2.0` branch has a fix for this. You can already try by changing your dependency version or wait until release `2.0.3` in upcoming days.
