### ISSUE TITLE
HTTP Response 419: The page has expired due to inactivity.

### ISSUE THREAD

**Issue by martinkrcho** [themosis/themosis#301]
I am repeatedly getting HTTP Response with **code 419** to various POST requests on my Themosis based site. This stops all forms on site from working as well as all AJAX (POST) requests.

Could you suggest a fix? Is there something that needs to be done with default framework and/or theme configuration?

**Comment by jlambe** [comment]
@martinkrcho Hi, it seems that your forms are missing the `csrf` hidden input used to identify your requests.

Can you provide the framework exact version and a code sample for one of your forms ?

Also, I suggest that you compare the `app\Http\Kernel.php` file of your application with [latest one](https://github.com/themosis/themosis/blob/2.0/app/Http/Kernel.php#L28), make sure to have similar middleware configuration for your `web` group.

Finally, you can verify if your form has the hidden `_token` csrf input by inspecting the page source code.

**Comment by martinkrcho** [comment]
@jlambe, thanks for a quick response. I am experiencing the issue with framework versions 2.0.0, 2.0.2 as well as 2.0-beta3.

I am using FacetWP plugin to reload a list of WooCommerce products. Hence, the code sample might be tricky.

I could inject the hidden `_token` input to each form or set the `X-CSRF-TOKEN` HTTP header for all `jQuery.AJAX` requests. This won't work for other forms, such as login or add to cart (non-AJAX).

I checked the web group in the middleware configuration and it matches the latest one. Is there an easy way to tell Themosis to check cookies instead of HTTP headers in `VerifyCsrfToken::getTokenFromRequest()`?

**Comment by jlambe** [comment]
Is it your Ajax calls from the FacetWP plugin that break ? What kind of request the plugin is performing and to which URL ?

**Comment by martinkrcho** [comment]
It's not just the FacetWP that is broken. It is also login form, WooCommerce "add to cart" request and various contact forms.

**Comment by jlambe** [comment]
But are these the default forms from WordPress and WooCommerce or custom ones built by you ? I've not yet encountered issue with WooCommerce and its forms. At this moment, I do not have any information to help you. I will have to try a fresh installation with WooCommerce and see how it goes.

Was the issue already there on your first installation with WooCommerce ?

**Comment by jlambe** [comment]
@martinkrcho I responded on a similar issue recently. If you're all WooCommerce on the project, the conflict is coming from the `VerifyCsrtToken` middleware. What you can do, is to remove the `csrf` middleware from the `web` group inside the `app/Http/Kernel.php` class and this should fix your issue.

**Comment by martinkrcho** [comment]
I did the very same thing couple of weeks ago. I was under impression that the CSFR token header is automatically populated by the framework. I guess, we need to send the token ourselves with each custom form if we want to use the csfr middleware.

**Comment by jlambe** [comment]
@martinkrcho yes, it's a manuel process. It's easy to populate it though as you can use the `@csrf` directive or simply create a hidden field with the `_token` name and use the `csrf_field` function (or similar, need to verify :))

**Comment by ligne13** [comment]
If you use GravityForms, like I do, you can add the CSRF field to every form using the snippet below:
```
Filter::add('gform_form_tag', function ($form_tag, $form) {
    return $form_tag . csrf_field();
}, 10, 2);
```
