### ISSUE TITLE
It is possibile to call WordPress functions from Console command?

### ISSUE THREAD

**Issue by MoiseScalzo** [themosis/themosis#311]
Hello,
as wrote in the the object if I try using any WordPress function inside a ```::command``` function I  got _**Call to undefined function get_post**_ error.

For example:

```php
Console::command('normalize', function() {
	$post = get_post(1452);
});

```
This example it fail...
Thank you in advance.

**Comment by jlambe** [comment]
@MoiseScalzo WordPress functions are not available inside commands as the CLI tool is aimed to work without a WordPress installation.

You could rewrite your command like so instead and leverage Illuminate packages:

```php
Console::command('normalize', function () {
    $post = DB::table('posts')->find(1452);
});
```

Many functions from WordPress are bundled by file so it is also possible to include it if you need some WordPress functions for your command.

**Comment by MoiseScalzo** [comment]
Thank you very much @jlambe.
Unfortunately I also need 3rd party plugin functions and many other WP things...so...I think I will try to proceed with WP CLI instead...

**Comment by jlambe** [comment]
@MoiseScalzo Another active user has a working solution for using WordPress through the CLI, see the thread here: https://github.com/themosis/framework/issues/646#issuecomment-508433102

We might look at implementing WordPress to the CLI tool as this looks promising.

**Comment by tipytechnique** [comment]
Hi @MoiseScalzo , you can track this PR https://github.com/themosis/framework/pull/706

This is a work in progress, but if you need to use Wordpress functions right now, you can add this line : `require web_path('cms/wp-load.php');` on your command's constructor.

```
/**
 * Create a new command instance.
 */
public function __construct()
{
    parent::__construct();

    require web_path('cms/wp-load.php');
}
```
Let me know if this works for you :)

**Comment by MoiseScalzo** [comment]
Thank you @tipytechnique I will try it...

**Comment by tipytechnique** [comment]
Edited my comment, forgot about the `wp-config` file.

**Comment by besrabasant** [comment]
`require web_path('cms/wp-load.php');` didnot work for me.

What worked for me though is below:
```php
$_SERVER['SERVER_PROTOCOL'] = 'HTTP/1.0';
$_SERVER['HTTP_HOST'] = 'www.test.sds';
$_SERVER['PATH'] = 'www.test.sds';
$_SERVER['REQUEST_METHOD'] = 'GET';

define( 'ABSPATH', web_path( 'cms/' ) );
define( 'WPINC', 'wp-includes' );

require_once ABSPATH . 'wp-includes/functions.php';
```

@tipytechnique
