### ISSUE TITLE
Cannot redeclare __()

### ISSUE THREAD

**Issue by Jaspervv** [themosis/themosis#317]
I'm trying to make use of the [`laravelium/sitemap`](https://gitlab.com/Laravelium/Sitemap) package, but I get an error when I require it.

This error comes from WordPress and Laravel both having the same translate function, and WordPress never heard of the `function_exists` function.  
However, why do I not have this problem until I require this package? Did this Laravel helper only just get added?

## Error
Error thrown from `/home/jasper/Projects/themosis/themosis/htdocs/cms/wp-includes/l10n.php:249`:
```php
Cannot redeclare __() (previously declared in /home/jasper/Projects/themosis/themosis/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:907)
```

## Recreate
Setup a fresh Themosis project, and require the package: 
```bash
$ composer require laravelium/sitemap
```

## Output
Below is the output of requiring the package. For some reason it removes packages, and it updates `laravel/framework` to the same version? :?
```bash
jasper@pop-os:~/Projects/themosis/themosis$ composer require laravelium/sitemap
Using version ^3.1 for laravelium/sitemap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 1 update, 27 removals
  - Removing illuminate/contracts (v5.8.29)
  - Removing illuminate/http (v5.8.29)
  - Removing illuminate/queue (v5.8.29)
  - Removing illuminate/support (v5.8.29)
  - Removing illuminate/session (v5.8.29)
  - Removing illuminate/console (v5.8.29)
  - Removing illuminate/container (v5.8.29)
  - Removing illuminate/database (v5.8.29)
  - Removing illuminate/filesystem (v5.8.29)
  - Removing illuminate/broadcasting (v5.8.29)
  - Removing illuminate/bus (v5.8.29)
  - Removing illuminate/pipeline (v5.8.29)
  - Removing illuminate/cache (v5.8.29)
  - Removing illuminate/config (v5.8.29)
  - Removing illuminate/cookie (v5.8.29)
  - Removing illuminate/encryption (v5.8.29)
  - Removing illuminate/events (v5.8.29)
  - Removing illuminate/hashing (v5.8.29)
  - Removing illuminate/log (v5.8.29)
  - Removing illuminate/mail (v5.8.29)
  - Removing illuminate/notifications (v5.8.29)
  - Removing illuminate/pagination (v5.8.29)
  - Removing illuminate/redis (v5.8.29)
  - Removing illuminate/routing (v5.8.29)
  - Removing illuminate/translation (v5.8.29)
  - Removing illuminate/validation (v5.8.29)
  - Removing illuminate/view (v5.8.29)
  - Updating laravel/framework (v5.8.29 => v5.8.29):Downloading (100%)         )
  - Installing laravelium/sitemap (v3.1.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Themosis\Core\ComposerScripts::postAutoloadDump
> @php console package:discover --ansi
Discovered Package: laravel/tinker
Discovered Package: laravelium/sitemap
Discovered Package: nesbot/carbon
Package manifest generated successfully.
```

**Comment by jlambe** [comment]
@Jaspervv You get the error because the package is including the `laravel/framework` package and with it its `foundation` code containing core Laravel helpers functions which are conflicting with the ones defined by Themosis and WordPress. The `laravelium/sitemap` package is doing it wrong in defining its dependencies as I would say it should have require `illuminate/packages` instead.

Perhaps you can do a fork of it, remove the `laravel/framework` dependency with the necessary illuminate ones and add your own package to the project.

**Comment by Jaspervv** [comment]
Thanks, I was really lost why this was happening. :P  
I might be able to do a PR there, if that's not possible I'll create a fork instead.
