### ISSUE TITLE
Call to undefined function Themosis\Hook\add_action()

### ISSUE THREAD

**Issue by dsazup** [themosis/themosis#318]
Hi, I was following an example from [here](https://framework.themosis.com/docs/2.0/page/#introduction), trying to add a custom administration page. I get this error 

```php
Call to undefined function Themosis\Hook\add_action()
```

My web.php route file:

```php
<?php
use Themosis\Support\Facades\Page;

/**
 * Application routes.
 */
Route::get('/', function () {
    return view('welcome');
});

Page::make('demo-page', 'Demo Page')
    ->set();
```

Am I missing something?

**Comment by edwinsiebel** [comment]
Hi @dsazup,

I got the same error as you. However, the meaning of the error is that the WordPress function ```add_action``` is not loaded (yet).

Try to insert the code:

```
\Themosis\Support\Facades\Page::make('demo-page', 'Demo Page')
    ->set();
```

into the file: /app/Hooks/Application.php and specific in the ```register``` method.

That works and I see the demo-page in the admin.

**Comment by dsazup** [comment]
Hi @edwinsiebel, thanks for your message. Yes, I figured that out after posting here. 👍 To me it would make sense these pages are created in the routes file, but there was no mention of it in the docs. It should probably be added. 

I noticed a few docs pages are saying "Add this code" but they do not say where to add it.

**Comment by jlambe** [comment]
@dsazup Hello, in fact, when you're trying to "customize" the WordPress administration, you always need to create a "Hookable" class to define your code. When the `register` method of a hookable class is executed, it is executed at the same level as a `mu-plugin`, so only at that moment you get access to all WordPress APIs.

Here is the link to the documentation page to let you create a hookable class: https://framework.themosis.com/docs/2.0/hooks/

Hope this help.
If you have suggestions so we can improve the documentation, don't hesitate to tell ;)
