### ISSUE TITLE
Session issues in pre_get_posts WP hook

### ISSUE THREAD

**Issue by rajogit** [themosis/themosis#319]
Hello @jlambe 

Do you have an idea how can I use Session class in pre_get_posts hook wordpress ?
I've got nothing when i try to get session content on pre_get_posts. But Session work if I use an other wp hook where the trigger is different (lower) than pre_get_posts.

Thanks for help

**Comment by jlambe** [comment]
Hmm no idea yet but dunno if the `pre_get_posts` hook is not expose to session issue we currently have on the WordPress administration: https://github.com/themosis/framework/issues/621

If you can share your code, perhaps I can reproduce it and see if I can help.
