### ISSUE TITLE
Sentry.IO Integration Help

### ISSUE THREAD

**Issue by maximusblade** [themosis/themosis#321]
Any one have some advice on how to successfully  integrate  Sentry.io 
with Themosis?
I'm getting the error below.

`Fatal error: Declaration of App\Exceptions\Handler::report(App\Exceptions\Exception $exception) must be compatible with Themosis\Core\Exceptions\Handler::report(Exception $e) in /home/vagrant/code/app/Exceptions/Handler.php on line 7`

We provide support for enterprise, please visit our dedicated platform for help:

- https://support.themosis.com

Alternatively, you may ask for help using the Gitter channel:

- https://gitter.im/themosis/framework

**Comment by jlambe** [comment]
I personnally no longer provide support on the repository issues. If you need assistance, you can use our new support platform:
- https://support.themosis.com

You might also get help from other users using the current Gitter chat room:
- https://gitter.im/themosis/framework
