### ISSUE TITLE
Can't disable View cache

### ISSUE THREAD

**Issue by KeironLowe** [themosis/themosis#323]
- Themosis Version: 2.0.4
- WordPress Version: 5.2.4
- PHP Version: 7.3

### Description
I can't seem to disable the View cache, I've tried setting `CACHE_DRIVER=array` and `CACHE_EXPIRE=-1` but they still cache. I'm trying to build a Blade Directive but I keep having to manually delete the cached files to see any changes.

### Steps to reproduce
Load a page, check the view cache directory.

### Expected behavior
Views shouldn't cache.

**Comment by jlambe** [comment]
In fact, you can't control the views with the cache configuration. A view is compiled to a php file before being rendered and the package checks the modified date of the view to know if it needs to be re-compiled or not.

If you write a custom directive, the code isn't changing inside your blade view. You only expect the compiled version to change based on your experiments. So the view is not recompiled and there you have it, you can't see the changes on your custom directive.

Based on the official documentation, there is nothing else to do than delete the compiled views when building a custom directive: https://laravel.com/docs/6.x/blade#extending-blade

From the terminal, run the `php console view:clear` command to delete the compiled views and test your directive.
