### ISSUE TITLE
Server Ubuntu 18.04 Install

### ISSUE THREAD

**Issue by Serialc0de** [themosis/themosis#334]
A simple bash script is needed to install this shit on the system. Possibly use the old version of wordpress. I will make a video about how to exactly configure the DNS and set this your website on a local web server with FREENOM domain. Please set up a script needed to install this small framework. Thanks.
By Serialc0de

**Comment by jlambe** [comment]
Requirements are the same as working with WordPress. We won't provide scripts to provision with the project. We recommend the use of Laravel Homestead for local development: 
- https://laravel.com/docs/7.x/homestead

**Comment by Serialc0de** [comment]
🖕

Il giorno dom 17 mag 2020 alle ore 13:06 Julien Lambé <
notifications@github.com> ha scritto:
