### ISSUE TITLE
Class WP_Query does not exist  

### ISSUE THREAD

**Issue by maksi55** [themosis/themosis#335]
- Themosis Version: 22.0.6
- WordPress Version: 5.4.1
- PHP Version: 7.2

Hello

I can't execute the console command that calls WP_Query

> $ php console command:send

> In Container.php line 788:
                                 
> Class WP_Query does not exist                                  

Regards

**Comment by jlambe** [comment]
Currently the WordPress APIs are not accessible from the commands. Check this pull request for a workaround:
- https://github.com/themosis/framework/pull/706
