### ISSUE TITLE
The page has expired due to inactivity.  Please refresh and try again.

### ISSUE THREAD

**Issue by maksi55** [themosis/themosis#336]
- Themosis Version: latest 
- WordPress Version: latest + Woocommerce
- PHP Version: 7.2

### Description

Hello

When I post data from my payment gateway I get a blank page with this message 

>   The page has expired due to inactivity.  Please refresh and try again.

route : checkout/order-received/9992/?key=wc_order_BNceAnQ6S4qSK

Regards

**Comment by mvdhoek1** [comment]
Hi Maksi,

You need to make sure that the form you are using contains a hidden field with an csrf token. The below solved it for me.

```
/**
 * Echo a hidden field with csrf token as value
 */
Action::add('woocommerce_before_add_to_cart_button', function () {
    echo '<input type="hidden" name="_token" value="' . csrf_token() . '">';
});
```

**Comment by mvdhoek1** [comment]
Or you can use this solution #303.

**Comment by maksi55** [comment]
Thanks
