### ISSUE TITLE
Can't change structure of app folder

### ISSUE THREAD

**Issue by rafflex** [themosis/themosis#337]
- Themosis Version: 2.0.7 (laravel-7 branch)
- WordPress Version: 5.4.1
- PHP Version: 7.3
### Description
When I am trying to change the structure of the app folder to match more to DDD structure everything seems to work fine except when I am moving Controllers folder. 

I am getting an error (which doesn't explain much what is wrong):

`Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in [...]/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php:64 Stack trace: #0 [internal function]: Themosis\Core\Bootstrap\ExceptionHandler->handleException(Object(Error)) #1 {main} thrown in [...]/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php on line 64

Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in [...]/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php:112 Stack trace: #0 [...]/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php(86): Themosis\Core\Bootstrap\ExceptionHandler->fatalExceptionFromError(Array, 0) #1 [internal function]: Themosis\Core\Bootstrap\ExceptionHandler->handleShutdown() #2 {main} thrown in [...]/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php on line 112`

Is Controllers path hardcoded somewhere (maybe in framework)?

When I am changing structure in the vanilla Laravel app everything works as expected.

Thanks

**Comment by rumur** [comment]
Hi @rafflex 
Have you removed the `namespace` from `RouteServiceProvider` ?
In order to place your router's wherever you need you need to remove the namespace.

```php
<?php 
// app/Providers/RouteServiceProvider.php

class RouteServiceProvider extends RouteProvider
{
    /**
     * Main controllers namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    // ...
}
```

**Comment by rafflex** [comment]
Hi @rumur 
Suggested solution works!
Thank you very much for your help.
