### ISSUE TITLE
Is the media field not available on frontend forms?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/themosis#338]
- Themosis Version: Version 1.4.0 by Julien Lambé
- WordPress Version: 5.4.2
- PHP Version: 7.4.7 (Supports 64bit values)

### Description
Made a frontend form using a media field but on the frontend, it is displayed as a number field.

is the Form::open() function completely gone now?
### Steps to reproduce
```
public function build(FormFactoryInterface $factory, FieldFactoryInterface $fields): FormInterface
    {
        return $factory->make(null, [
            'theme' => 'theme.profile'
        ])
        ->add($fields->media('avatar', [
            'theme' => 'theme.profile',
            'group' => 'avatar',
            'label' => 'User Avatar',
            'label_attr' => [
                'class' => 'block text-sm font-medium leading-5 text-gray-700'
            ],
            'type' => ['image'],
            'attributes' => [
                'class' => 'mb-6 appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5',
                'required'
            ],
            'rules' => 'required|string|max:255'
        ]))
```
### Expected behavior
Want to use a media upload input on the frontend form and be able to style the form fields using tailwind with their own wrappers.

**Comment by jlambe** [comment]
The media field is not available on the front-end. It uses WordPress administration script that are not available on the public side of WordPress.

If you need to upload files, you still have to build your own file input.
