### ISSUE TITLE
Support for third party plugins

### ISSUE THREAD

**Issue by solucionti** [themosis/themosis#340]
I have tried to integrate learnpress plugin (https://wordpress.org/plugins/learnpress/) to themosis but this has not been possible, I followed the documentation to integrate woocomerce (Thinking it would do the same), but it is not like that. How can a third party library be integrated into the rpoeycto? Does this depend on the framework? or should I do some extra customization?

Thank you.

**Comment by jlambe** [comment]
@solucionti Any WordPress plugins can be installed as is, either from the WordPress administration or through WPPackgist and Composer.
