### ISSUE TITLE
impossible to install via composer

### ISSUE THREAD

**Issue by chrisvidal** [themosis/themosis#347]
running the composer `create project` command, I encounter this issue

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/homestead[v7.0.0, ..., v7.20.0] require php ^5.6 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires laravel/homestead ^7.0 -> satisfiable by laravel/homestead[v7.0.0, ..., v7.20.0].

```

and my PHP version

```
php --version
PHP 7.3.21 (cli) (built: Aug 31 2020 14:12:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.21, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by jlambe** [comment]
@chrisvidal It seems that your composer binary is using another php-cli version than the one you use ?? Composer output that the used php version is `8.0.0` and not your `7.3.21` one.

Do you have multiple php binaries on your machine ? You can try to download and extract the `themosis/themosis` repository and then install composer locally and execute it like so:

```bash
php -f composer.phar install
```

and sees if that fixed your issue.

**Comment by chrisvidal** [comment]
after some digging:
After upgrading homebrew sometimes ago (2.6.2), it installed php8 and changed somehow the PHP binary version used by composer. So far, I didn't find a way to change the PHP binary used by Composer.

**Comment by chrisvidal** [comment]
following this guide was helpful to retrograde brew to used php7.4
