### ISSUE TITLE
How to include AngularJS

### ISSUE THREAD

**Issue by fabianmarz** [themosis/themosis#35]
I'm having trouble getting Angular included. So I'm having this code block in a .js file.

    function config ($routeProvider) {
        $routeProvider
        .when('/', {
            templateUrl: '/views/main.html',
            controller: 'MainCtrl',
            controllerAs: 'main'
        });
    }

    angular
        .module('app')
        .config(config);

In my  `angular.scout.php` file I'm having following block

    <div class="row" ng-app="app">
        <div class="all-full">
            {{ Loop::content() }}
            <div ng-view></div>
        </div>
    </div>

If I run the page I'm getting a "No route defined for this request" error

How can i solve this? The main.html file is located outside the app directory

Thanks

**Comment by jlambe** [comment]
Were you able to solve your issue ?

**Comment by fabianmarz** [comment]
Sorry, i was on vacation...I'll check it later!

**Comment by jlambe** [comment]
:+1:

**Comment by fabianmarz** [comment]
finally I did it a stupidly easy way... haven't had thought about it earlier ![](http://www.metroid-database.com/forum/images/smilies/facepalm_smiley.png)

footer.scout.php:

```html
<script>
    var baseurl = "<?php echo get_template_directory_uri() ?>";
</script>
```

app.js:

```js
function config ($routeProvider) {
    $routeProvider
    .when('/', {
        templateUrl: baseurl + '/app/views/angular/main.html',
        controller: 'MainCtrl',
        controllerAs: 'main'
    });
}
```

Now it works.

Thanks for your help! I really appreciate it :)

**Comment by jlambe** [comment]
Glad it works. Here is another tip for you:

In place of defining another `<script>` tag in your views for your `baseurl` variable, you can also simply add it to the global js object like so:

```php
// admin/application.php or inside any controllers or route closure.
add_filter('themosisGlobalObject', function($data)
{
    // Add your data.
    $data['baseurl'] = get_template_directory_uri();

    return $data;
});
``` 
This output inside the `<head>` tag, the following object:

```html
<script type="text/javascript">
//<![CDATA[

var themosis = {
    ajaxurl: 'http://super.dev/cms/wp-admin/admin-ajax.php',
    baseurl: 'the-template-direcory-uri'
};

//]]>
</script>
```

So inside your `app.js` file, you mention your `templateUrl` like so:

```js
function config ($routeProvider) {
    $routeProvider
    .when('/', {
        templateUrl: themosis.baseurl + '/app/views/angular/main.html',
        controller: 'MainCtrl',
        controllerAs: 'main'
    });
}
```

Using this, you avoid the browser to parse your script tag as full JS (because of the cdata statement) and your global variable is prefixed, which may be better to avoid conflicts.

Also, the `themosis` js object var name can be changed to anything you want inside the `application.config.php` file.

**Comment by jlambe** [comment]
I forgot to mention that this tip can be found inside the `Ajax` documentation:
- [http://framework.themosis.com/docs/ajax/](http://framework.themosis.com/docs/ajax/)

**Comment by fabianmarz** [comment]
Nice! Thank you.

**Comment by drejohnson** [comment]
This is awesome!
