### ISSUE TITLE
301 on wp-api on subsite

### ISSUE THREAD

**Issue by motchju** [themosis/themosis#366]
- Themosis Version: dev-master
- WordPress Version: 5.8.1
- PHP Version: 8.0.10

### Description

My version of wordpress is a multisite, form the main site no issue.

However on the subsite, the issue is present

### Steps to reproduce

Metabox (on a subsite) are not visible I have this error

`TypeError: Cannot read properties of undefined (reading 'data')
    at themosis.core.js?ver=8.0.0:37337`

The url called is the one of the subsite, in my case

https://site1.multigreng.test/wp-api/themosis/v1/metabox/champs_libre?post_id=65 -> this will gave me a 301 redirection

If I trigger the same query but from the main site, no issue

https://multigreng.test/wp-api/themosis/v1/metabox/champs_libre/?post_id=65 -> I will have a json respond and no redirection

### Expected behavior

How to allow the call to the wp-api from a subsite ?

One dirty solution could be to change in app>Hooks>Application.php the base_url but that will gave me CORS issue (as the subsite is calling the main site)

**Comment by jlambe** [comment]
By curiosity. is the `wp-api` root endpoint is also accessible on a subsite ? 

You're free to modify the `app/Hooks/Application.php` class to your needs. The stack comes with a default configuration but you can change it. And based on your issue, I would look at the `Filter::add('network_site_url')` declaration in the same file. From there you can modify the network url and I think you might resolve yours there.

**Comment by motchju** [comment]
Hi, 

Thanks for the hint will check your proposal.

What do you mean by 'root endpoint is also accessible on a subsite' ?

https://multigreng.test/wp-api/ -> 404
https://site1.multigreng.test/wp-api/ -> 404

**Comment by jlambe** [comment]
There is probably an error in how the framework is registering its endpoint because it doesn't use the WordPress APIs to register it but is using a custom route. See here: https://github.com/themosis/framework/blob/master/src/Metabox/MetaboxRoutingServiceProvider.php#L22

So playing with the `network_url` is not the solution. Perhaps registering the same core route for all sub-sites like so:

```php
// Declare this before any other routes
// in routes/web.php
Route::domain('{site}.multigreng.test')->group(function () {
    Route::middleware('api')
            ->namespace('Themosis\Metabox\Controllers')
            ->prefix('wp-api/themosis/v1')
            ->group(function () {
                Route::apiResource('metabox', 'MetaboxApiController')->only([
                    'show', 'update'
                ]);
            });
});
```

**Comment by motchju** [comment]
Thanks will give it a try, however on my Vanilla multisite this is working as expected. So I believe another setting should be wrong and gave me this error

Anyway thank you so much for the help
