### ISSUE TITLE
composer file installs plugin to mu-plugins

### ISSUE THREAD

**Issue by andybeak** [themosis/themosis#37]
Following the installation guide results in the plugin not appearing in the list of plugins in the admin page.  This can be remedied by moving the themosis-framework from content/mu-plugins to plugins.

It is placed there by composer.

Either composer needs to be updated or there is code (I haven't looked) that is supposed to hook this mu-plugins folder.

**Comment by andybeak** [comment]
Actually it's just the installation comments that cause the confusion.  It says you need to activate the plugin, but because its installed to mu you don't need to.

**Comment by jlambe** [comment]
Hi! Before release 1.1.0, it was installed as a classic "plugin" but there is no need for that anymore thanks to "mu-plugins". I'll update the docs to avoid the confusion, thanks for catching this one ;)
