### ISSUE TITLE
Setup on localhost

### ISSUE THREAD

**Issue by stanwarri** [themosis/themosis#41]
I'm trying to set themosis on my localhost but it keeps redirecting and giving me error 404

http://localhost/themosisl/cms/wp-admin/install.php
"Not Found
The requested URL /themosis/cms/wp-admin/install.php was not found on this server."

Is there a different procedure to get it to work on localhost

**Comment by jlambe** [comment]
Hi,
it is best practice to setup a `virtualhost` for your local development.
Habitually I don't work with sub-folders but how is setup your `.env.local.php` file? Regarding your URL, does it look like this:
- http://localhost/themosis/
- http://localhost/themosis/cms/

If it doesn't work, you'll need to setup a virtual host then.

**Comment by stanwarri** [comment]
@jlambe The main reason i setup sub-folders is so that you can cover multiple of use cases. You really can't tell if the person that downloaded your software is installing it a sub-folder or not. I want to ensure it can work under any scenario.

**Comment by jlambe** [comment]
I can understand but the simplest scenario is still a website installed on a single domain. If you want to manage sub-folders installation, I would use a multi-site installation perhaps ?

**Comment by rovillesarate** [comment]
Hi! I would suggest using easyphp and use their virtualhost addon. so you can use
http://yourdomainname.com as your local wordpress domain and use http://www.yourdomainname.com as your production url.

Just make sure to point the directory in the virtual host addon to your themosis directory /htdocs for it to work.

as for the scenario you can also do it using the virtualhost addon and creating instances of the domains like

http://domainname1.com, http://domainname2.com

and create multiple subholder being pointed to their respective virtualhosts

**Comment by leonharvey** [comment]
Since sending my first message I solved the issue. Thanks for the reply though, but I'm after receiving this response several times from you now as well as I think being CCd on some of your other support tickets. If you can stop sending them that'd be great.
Well done on the framework though, I haven't fully invested time into using it for a full project yet but the Laravel-ish like syntax is awesome. Thanks for making it!
Date: Mon, 2 Mar 2015 17:53:07 -0800
