### ISSUE TITLE
Corcel integration

### ISSUE THREAD

**Issue by jgrossi** [themosis/themosis#42]
Hi! I'm have a project on Github that collects data from Wordpress databases using Laravel/Eloquent. The project is called Corcel and maybe we can integrate Corcel and Themosis. Check it out [here](http://github.com/jgrossi/corcel). Please take a look and let me know. Thanks!

**Comment by jlambe** [comment]
It sounds interesting plus more people coming from Laravel are asking for an Eloquent implementation.
Did you use your library on production/live projects?

**Comment by jgrossi** [comment]
Yes! Corcel uses Illuminate\Database (Eloquent), so I have some projects using it with Wordpress + Composer. I have used it with Silex too and pure PHP projects ;-) Just add Corcel to composer.json and install it.

**Comment by laravelish** [comment]
thank you i'm goin to switch to [Corcel ](https://github.com/jgrossi/corcel) right now !
