### ISSUE TITLE
Question about .gitignore

### ISSUE THREAD

**Issue by santivila** [themosis/themosis#43]
Hi Julian.

First of all thanks for your work, I have been using **Themosis** for a while now and couldn't be happier. 

I see that folder <code>/htdocs/content/themes/themosis-theme/</code> is included by default in <code>.gitignore</code>, am I right?

Am I supposed to comment it out from <code>.gitignore</code> once I have started working on my theme and I want to push changes to my repo? or what would be your recommended workflow?

**Comment by jlambe** [comment]
I always suggest to rename the `themosis-theme` folder to something that reflects your project name. So your theme will be tracked correctly with git.

Also when updating, composer will look after the `themosis-theme` package. If found, it will replace it and you'll lose your work (except if you track it of course, you can rollback...).

When starting a new project, run the `composer create-project`  and simply change the `themosis-theme` folder name to something else and you're good to go.
