### ISSUE TITLE
Add Metabox for specific pages

### ISSUE THREAD

**Issue by ramon-villain** [themosis/themosis#45]
Hi Julien,
I'd like to see, if you know an easier way or if there's something similar in the core to do something like this, that's working, btw. 

```
$fields_products = array(
    Field::text('size'),
    Field::infinite( 'product', array(
        Field::media( 'product_image', [ 'title' => '' ] )
    ) )
);

//if(isset($_GET['post']) && $_GET['post'] == '5' || isset($_POST['post_ID'])){
if(isset($_GET['post']) && in_array($_GET['post'], ['7', '9','11']) || isset($_POST['post_ID'])){
    Metabox::make( 'Lightbox Images', 'page' )->set( $fields_products );
}
```

**Comment by ramon-villain** [comment]
Dammit, wrong place. Sorry.

Would you rather I transfer to another branch?

**Comment by jlambe** [comment]
There is an helper function called `themosisIsPost()` for this:
```php
if (themosis_is_post(5))
{
     Metabox::make();
}
```

Also, what I was used too these past days is to set a custom template to any page. And in place of hard coding an ID or find a page with specific title or slug, I'm looking to pages with my template and grab their ID dynamically.

**Comment by ramon-villain** [comment]
Hmm, this themosisIsPost() won't work for arrays, right?

I got the idea of the templates, but how can I check (in back-end) if that page has set a custom template?
```
var_dump(is_page_template('custom-template'));
var_dump(get_page_template());
```

**Comment by ramon-villain** [comment]
Just to be more clear my scenario is: I have 2 static pages "about" and "contact", so I wanna add the Metabox just to the first.

So in my mind I'll check the post id, and add the metabox (like I did above). This is the better way?

**Comment by jlambe** [comment]
I used to write this code for a specific page.
```php
$page = get_page_by_path('about');

if (themosis_is_post($page->ID))
{
    Metabox::make();
}
```

The `themosis_is_post()` only accepts an ID (int) variable.

Regarding the page templates, the value is registered as a `post meta`. You can check if a page has a template associated like so:

```php
// The PageModel::all() method use the WP_Query to get all "published" only pages.
foreach (PageModel::all() as $page)
{
    $template = Meta::get($page->ID, '_themosisPageTemplate');

    if (!empty($template) && 'about' === $template)
    {
        Metabox::make();
    }
}
```

**Comment by infinitation** [comment]
I tried the recommended above  and added it into a template-admin.php file in the app/admin folder. I had to make some edits for it to work for saving my updates. I'd love to know if there is an easier way to do this that I might be overlooking, or if in a future version, templates could be built out a bit more with the Meta section. This framework is insanely awesome too!

```
//Check for templates and create custom Meta for editing
if (!empty($_GET['post']))
{
	$template = Meta::get($_GET['post'], '_themosisPageTemplate');
}

//Save template metabox data
if (!empty($_POST['post_ID']))
{
	$template = Meta::get($_POST['post_ID'], '_themosisPageTemplate');
}

//Check empty and use switch for multiple templates (if you have them)
if (!empty($template))
{

	switch ($template)
	{
		case 'about-template':

			Metabox::make('Additional Information', 'page', [
				'context'   => 'normal'
			])->set([
				Field::editor('content-lead'),
			]);

			Metabox::make('Random Metabox Title', 'page', [
				'context'  => 'normal',
				'priority' => 'high'
			])->set([
				Field::infinite('something', [
					Field::text('title'),
					Field::textarea('content')
				], [
					'title' => 'Title',
					'limit' => 10
				])
			]);

			break;
  
	}
}
```

**Comment by jlambe** [comment]
Looking at your code, you're looking after any post type. Perhaps using the `themosis_is_post($postID)` helper function will reduce your `if` statements. Also run your code only if the post type is a page.

The `PageModel::all()` method is running a `WP_Query` only to retrieve those pages post type. The run a loop where you apply your metabox regarding the template.

Currently there is no direct implementation of the metabox with the templates but this might come.

**Comment by Antoinebr** [comment]
If you want to add custom field for the HomePage 

```php
$home_id = get_option('page_on_front');

if (themosis_is_post($home_id)){
  Metabox::make();
}

```
