### ISSUE TITLE
Does it the right choice?

### ISSUE THREAD

**Issue by mbnoimi** [themosis/themosis#47]
I want to build a web applications (I'm desktop/mobile developer using Qt) rapidly using PHP so I googled to find that Laravel is the most popular framework but some guy advices me to develop my applications depending on CMS built from Laravel or create a plugin for some popular CMS (WordPress is the one) but unfortunately I couldn't make my mind which is best for me so may you please help me by answering these questions to be able to get the right decision?

1. What's the difference between **themosis** and **themosis** plugin?
2. Can I use another theme instead of default **themosis** theme?
3. Unfortunately I couldn't find any tutorial for **themosis** but I found [this YouTube Portages playlist](https://www.youtube.com/watch?v=-nn4vNx304M) (I don't speak Portages) Is there any tutorial I can learn from?
4. Let's say I want to build HR system. Does **themosis** supports front-end types or I've to create the shortcodes by myself (I don't want to allow the registered users to login WordPress admin)?
5. Depending on the above assumption how can I show DataGrid (for read/write data using custom queries) for registered users? Do I've to build it by myself using some kind of Js frameworks or **themosis** already support this kind of UI controls (you can see [this DataGrid for Laravel](https://github.com/Nayjest/Grids))?
6. Depending on the above assumption, Do you encourage me to use **themosis** or using a standalone web framework (Laravel)?
7. **UPDATE**: What's the difference between **themosis** and [WP MVC](https://github.com/tombenner/wp-mvc)?

Sorry for lame questions guys

**Comment by jlambe** [comment]
Hi,

1. Themosis framework is WordPress development with extra tools. The Themosis plugin (framework repo) is a WordPress plugin containing the core classes of the framework. The Themosis/themosis package is the root of the project where an instance of WordPress is installed + the themosis/framework plugin as a WordPress plugin.
2. Yes you can use any theme you want. You'll still be able to access the core classes from whatever theme you want.
3. There is a complete documentation available on http://framework.themosis.com/. Follow the "Getting started" sections and you should be ready to go.
4. Like any WordPress project, you can create your own user interface/admin pages in the front-end.
5. It uses composer to autoload dependencies. Simply add any php grid library and you're good to go.
6. Both will do the job, just pick the one you're more comfortable with.
7. Same objectives, different way to go I suppose. I've never tried it. Same as 6, test both and pick the one you prefer.

I'll never say a solution is better than another. There are always multiple ways to achieve the same results with whatever tools you use. Test each solution and pick the one you feel is right for your project or for yourself.

**Comment by mbnoimi** [comment]
@jlambe Thanks a lot for the response.

> Themosis framework is WordPress development with extra tools. The Themosis plugin (framework repo) is a WordPress plugin containing the core classes of the framework

You mean I can't deploy my modifications on any WordPress without installing Themosis plugin before?

> There is a complete documentation available on http://framework.themosis.com/. Follow the "Getting started" sections and you should be ready to go.

May you please add a tutorial to the docs. Getting started good for installing process while in tutorial you can create a demo project to tech the newbie how themosis really works.

**Comment by jlambe** [comment]
Yes you can deploy existing code without Themosis. The plugin provides classes. If your theme or plugin is using those classes, then you have to install the themosis/framework plugin into your WordPress installation in order to make it work.

Currently there are no tutorials but there are 2 complete projects available on our Github account so you can check what and how the application is built:

1. Bookstore: https://github.com/themosis/bookstore
2. ToDo application: https://github.com/themosis/todo

Also, the framework website code is also available so you can check how it's done:
- https://github.com/themosis/website

**Comment by mbnoimi** [comment]
@jlambe Thanks a lot for useful answers.
I know this is out the scope can I take a five minutes of your time in this post:

Which type of frameworks?
https://wordpress.org/support/topic/which-type-of-frameworks?replies=1

Thanks in advance for help :)
