### ISSUE TITLE
Calling singular custom post type via Ajax

### ISSUE THREAD

**Issue by aliasim** [themosis/themosis#49]
Hi, 
We have just started using this and are loving the flexibility - few questions though -

How can call in a single custom post type contents via ajax in a div on the same page

This is code for the static site - 
            jQuery.ajax({
                    url: url,
                    type: 'GET',
                    dataType: 'html',
                    timeout: 10000
                })
                .done(function(result) {
                    t.updateSinglePage(result);
                })
                .fail(function() {
                    t.updateSinglePage('AJAX Error! Please refresh the page!');
                });

I have also created a singular view called singular.

Also, can we implement relational metabox data - for instance on a singular  "books" post type can we add associations to other related "books" via drag and drop and display them in the front end?

Good example would be this - 
http://www.advancedcustomfields.com/resources/relationship/

thanks,
Ali

**Comment by jlambe** [comment]
Hi,

glad you like the framework :+1: 

Regarding how to work with Ajax in WordPress, you can check the Ajax class documentation with a code sample: http://framework.themosis.com/docs/ajax/ or I encourage you to dig into WordPress codex as well: https://codex.wordpress.org/AJAX_in_Plugins

For relational custom fields, you can easily do it with `Field::select`  and simply set the options with a list of posts. If you need to map several, simply allow to select multiple choices at once. For better user-friendly interface, I also encourage you to load one of those js librairies:
- select2: https://select2.github.io/examples.html
- chosen: http://harvesthq.github.io/chosen/

Within a couple of minutes you get a custom relational field. Hope this helps.

**Comment by aliasim** [comment]
Hey Julien,
Thank you for responding - I think we got ajax going but are struggling in the following -

To get a gallery, whenever I print_r($gallery) or var_dump it gives me the id value to those images but I need the src to the image.

                    $gallery = Meta::get(Loop::id(), 'gallery');
        print_r($gallery) 

ideally the following should work: 
                        @foreach($gallery as $img)
                        {{ $img['src'] }}

                        @endforeach


Another thing is getting the post slug - so when I type {{Loop::link()}} in the singular main it gives me the permalink but what about just the slug for the post type?


Finally - can I attach meta fields ideally a color picker to taxonomies.
I tried installing  the plugin "Category Colors" but that gave me a fatal error.

thanks,
Ali

**Comment by jlambe** [comment]
1- Yes, the collection field save the ID of the attachment so you can easily grab any value attached to it. So if you want the "src" value, use the [wp_get_attachment_image_src($id)](https://codex.wordpress.org/Function_Reference/wp_get_attachment_image_src) function.

2- As you're running a WordPress loop, the post slug/name is already in use. You can retrieve the post slug from the main post variable which is by default available on each route as first argument. So on your singular route:

```php
Route::singular('post-type', function($post)
{
    return View::make('singular')->with('post', $post);
});
```

Then inside your view, use the `$post` variable to re-use the post type slug.
> Note: There is also the main query object available as a second argument in the route Closure or Class method.

```php
Route::singular('post-type', function($post, $query)
{
    // some code...
});
```

Hope this helps. Let me know how it goes.

**Comment by jlambe** [comment]
Currently the field API only works for metabox and options. The next release brings the field API to users then comes the taxonomy custom fields. You'll need to wait a little longer for these or you can fork the `themosis/framework` package and try to add it for taxonomy.

**Comment by aliasim** [comment]
Hey, 
So the images wp_get_attachment_image_src($id)  worked out great - now for select for related posts - I need them to be dynamic - so how can I call / query custom post :  @query(array('post_type' => 'postname', 'posts_per_page' => -1))  with in admin - ideally excluding the existing post user is editing in the cms.

$Related = array(
    Field::select('related-', array(
        array(
           
        )
    ), false, array('title' => 'Choose a post:')),
);

thanks,
Ali

**Comment by jlambe** [comment]
For admin, use the `WP_Query` class to retrieve a list of your posts: https://codex.wordpress.org/Class_Reference/WP_Query

Also, I recommend you to create a model class for your post where you defined all the methods in order to retrieve and set your posts. So for your select field, you'll only need to call one method to get the field populated.

Check this documentation: http://framework.themosis.com/docs/models/

**Comment by aliasim** [comment]
So this was resolved back a while ago - just wanted to make sure I post on how I was able to achieve this

My Model -
<?php
class CaseStudyModel {
    /**
     * Return a list of all published posts.
     *
     * @return array
     */
    public static function all()
    {
        $query = new WP_Query(array(
            'post_type'         => 'case-studies',
            'posts_per_page'    => -1,
            'post_status'       => 'publish'
        ));

        return $query->get_posts();
    }

} 

Under admin/application.php

// Define related case studies
$posts = CaseStudyModel::all();
$relatedcaseslist = array();
foreach($posts as $post){
    $relatedcaseslist[$post->ID] = $post->post_title;
}
$caseStudyRelated = array(
    // case studies
    Field::select('related-cases',array(
       $relatedcaseslist
    ), true, array('title' => 'Choose a case study:')),
   
);

**Comment by jlambe** [comment]
Only for a cleaner approach, personally I would have made the `foreach` loop from the `application.php` file inside another method in your `CaseStudyModel` class so you'll only write this for the select field:
```php
$cases = CaseStudyModel::getCases();
// Metabox code...then field...
Field::select('related-cases', [$cases], true, ['title' => 'Choose a case study'])
```
