### ISSUE TITLE
Call to undefined method WP_Error::setRole()

### ISSUE THREAD

**Issue by CodeBrauer** [themosis/themosis#50]
The curious thing: It only shows on the stages testing/production - on dev everything works fine.

But I really can't figure out whats the error.

```
Fatal error: Call to undefined method WP_Error::setRole() in /usr/www/users/xxxxx/htdocs/content/themes/xxxxx/app/controllers/UserController.php on line 134
```

Code:
```php
130: // create user with dummy password (inactive)
131: $password = $this->generatePassword(50);
132: $user = User::make($email, $password, $email);
133:
134: $user->setRole('customer');
```

Everything is updated (with composer) and all other files are git-synced...

**Comment by jlambe** [comment]
It seems that your user is not created in the database. So your first line where you call `User::make` returns an instance of `WP_Error` which doesn't have a `setRole` method.

Does WordPress allow that the username is the same as the email?

**Comment by CodeBrauer** [comment]
Oh, I found the issue: https://codex.wordpress.org/Function_Reference/is_wp_error

Just wrap it and see the error message - in my case the email-address was already used.

[Monday mornings...](http://giphy.com/gifs/11oLdpZb2mrv8c/html5)

**Comment by jlambe** [comment]
:+1: Yes that's definitely the issue ;) Would you share the link to your live project? I'm curious to see what you've done with the framework and I also intent to add a "showcase" page on the framework website.

**Comment by CodeBrauer** [comment]
@jlambe I have to ask my boss about this but I think it is possible. The website is an online textile cleaning service with pickup and delivery

**Comment by jlambe** [comment]
Ok, thanks!
