### ISSUE TITLE
Custom route with woocommerce

### ISSUE THREAD

**Issue by brokleen** [themosis/themosis#51]
Hello, i want use your fabulous framework Themosis with woocommerce but i don't understand how to route the shop page. 
I try this 
Route::any('page', function(){
    return View::make('page');
});
Route::any('shop', function(){
    return View::make('shop');
});
Route::any('singular', function(){
    return View::make('shop');
});
But nothing works.

thank for help

**Comment by jlambe** [comment]
Hi,

for WooCommerce, you'll need to write your custom routes for some request and also add/overrides some default templates.

Check this issue (#36), you should find the solution for yours: #36 

If you still have troubles, let me know and we'll try to resolve this.

**Comment by jlambe** [comment]
You can also write this code for listening to the `shop` page:

1 - Write the custom route for the shop page:
```php
// in .../admin/shop.php file for example
add_filter('themosisRouteConditions', function($conds)
{
    // Add the product condition.
    $conds['shop'] = 'is_shop';
    return $conds;
});
```
2 - Add the `archive-product.php` template at the root of your theme and add this code only to the file:
```php
<?php
themosis_start_app();
```
3 - Now you can listen, from the `routes.php` file, the request for the shop page using the custom route defined previously:
```php
// routes.php
Route::get('shop', function()
{
    return 'Shop page';
});
```
This solution is best than the one detailed in #36. It's the same except the code inside the default template. Let me know how it goes!

**Comment by brokleen** [comment]
Hello, i don't understand where insert the woocommerce child theme ?

**Comment by jlambe** [comment]
You don't have to create a child theme. Use the `themosis-theme` for your project but at its root (where is located the `functions.php`, `index.php` files), create the `archive-product.php` file and simply add the code above at point 2.

**Comment by brokleen** [comment]
I trying your solution But it does not work.
I have this error : 
Unhandled Exception

Message:

Thème sans header.php. est déprécié depuis la version 3.0, aucune alternative n’est disponible. Veuillez inclure un modèle de type « header.php » à votre thème.
Location:

/home/ubuntu/workspace/themosis/htdocs/cms/wp-includes/functions.php on line 3450
Stack Trace:

#0 /home/ubuntu/workspace/themosis/htdocs/content/themes/themosis-theme/functions.php(232): Themosis\Error\Error::native(1024, 'Th??me sans hea...', '/home/ubuntu/wo...', 3450)
#1 [internal function]: {closure}(1024, 'Th??me sans hea...', '/home/ubuntu/wo...', 3450, Array)
#2 /home/ubuntu/workspace/themosis/htdocs/cms/wp-includes/functions.php(3450): trigger_error('Th??me sans hea...')
#3 /home/ubuntu/workspace/themosis/htdocs/cms/wp-includes/theme-compat/header.php(10): _deprecated_file('Th??me sans hea...', '3.0', NULL, 'Veuillez inclur...')
#4 /home/ubuntu/workspace/themosis/htdocs/cms/wp-includes/template.php(501): require_once('/home/ubuntu/wo...')
#5 /home/ubuntu/workspace/themosis/htdocs/cms/wp-includes/general-template.php(46): load_template('/home/ubuntu/wo...')
#6 /home/ubuntu/workspace/themosis/htdocs/content/themes/themosis-theme/archive-product.php(17): get_header('shop')
#7 /home/ubuntu/workspace/themosis/htdocs/cms/wp-includes/template-loader.php(74): include('/home/ubuntu/wo...')
#8 /home/ubuntu/workspace/themosis/htdocs/cms/wp-blog-header.php(16): require_once('/home/ubuntu/wo...')
#9 /home/ubuntu/workspace/themosis/htdocs/index.php(11): require('/home/ubuntu/wo...')
#10 {main


When you say "// in .../admin/shop.php file for example", this page is autoload or need a require ?

**Comment by brokleen** [comment]
Edit, it's work. 
But if I need a child theme how does it work ?

**Comment by jlambe** [comment]
Take a look at this issue which gives you tips to build a child theme #39 : https://github.com/themosis/themosis/issues/39

All files located at the root of the `admin` folder are autoloaded in alphabetical order. Make sure to read carefully the "getting started" part in the documentation: http://framework.themosis.com/docs/installation/

If you prefer, you can continue in french for your issue if it's easier for you ;)

**Comment by brokleen** [comment]
Mmhm thank you !
I will try to build a project before using it in my workflow.

Merci Julien ;)

**Comment by brokleen** [comment]
Par contre j'ai essayé le même process pour single-product mais cela ne marche pas. 
add_filter('themosisRouteConditions', function($conds)
{
    $conds['product'] = 'is_product';
    return $conds;
});
Route::any('product', function()
{
    return 'product page';
});

et dans le fichier single-page :  
themosis_start_app();

**Comment by jlambe** [comment]
De mon côté, je viens d'essayer le même code et tout fonctionne correctement.

Voici une copie de mon code avec en commentaires le fichier où l'écrire:

1 - Ajouter les routes personnalisées.
```php
// admin/shop.php
<?php

add_filter('themosisRouteConditions', function($conds)
{
    // Add the product conditions.
    $conds['shop'] = 'is_shop';
    $conds['product'] = 'is_product';

    return $conds;
});
```
2 - Ajouter le fichier `single-product.php` à la racine du thème.
3 - Ajouter le code suivant dans `single-product.php`:
```php
<?php

themosis_start_app();
```
4 - Dans le fichier `routes.php`, ajouter une route pour `product`:
```php
Route::get('product', function()
{
    return 'One product';
});
```
Ajouter un ou deux produits pour tester et ça doit retourner le texte "One product" pour chaque page normalement.

**Comment by brokleen** [comment]
Il faut changer les permaliens pour que cela fonctionne ;)

**Comment by tdserviceco** [comment]
![skarmavbild 2015-11-24 kl 13 50 55](https://cloud.githubusercontent.com/assets/10770786/11367215/816e5a70-92b2-11e5-896a-a14cb2791223.png)
![skarmavbild 2015-11-24 kl 13 51 00](https://cloud.githubusercontent.com/assets/10770786/11367218/857b6a40-92b2-11e5-892e-ba2707f21708.png)




Hi, I got everything to work now (except single-product)

I used this: 

<?php

$route = Route::get('product', function()
{
    // This is calling the view stored inside app/views/shop/product.scout.php
    return View::make('shop.product');
});

// Output the route response content...
echo($route->run());

inside single-product.php (inside root of theme) and I get the code and all.. but something is missing..
First image is my master.scout.php file.. second one is the shop/product.scout.php

**Comment by joelcdoyle** [comment]
Using the tips on this page, I have fixed the error message similar to this: 
```
Thème sans header.php. est déprécié depuis la version 3.0, aucune alternative n’est disponible. Veuillez inclure un modèle de type « header.php » à votre thème.
```

But how do I load the archive-product.php template?!?!

My goal was to slightly modify the shop page to my needs, but now all I have is a page that shows up like a regular post page. It shows the title of the first product and nothing else.
