### ISSUE TITLE
after_setup_theme execution order 

### ISSUE THREAD

**Issue by Cezarion** [themosis/themosis#53]
Hello, 

I would like to use some features of the roots/soil plugin but it seem's that the after_setup_theme action executed by this plugin is called before the init of the configuration file supports.config.php. 

The Roots/soil plugin do :
```
function load_modules() {
  global $_wp_theme_features;
  foreach (glob(__DIR__ . '/modules/*.php') as $file) {
    $feature = 'soil-' . basename($file, '.php');
    if (isset($_wp_theme_features[$feature])) {
      Options::init($feature, $_wp_theme_features[$feature]);
      require_once $file;
    }
  }
}
add_action('after_setup_theme', __NAMESPACE__ . '\\load_modules');
````
If I do `var_dump($_wp_theme_features)` it return null.

Have you an idea ?

NB : Thank's for this great wordpress review

**Comment by jlambe** [comment]
Hello,

currently the framework is also bootstraped during the `after_setup_theme` action hook, so this might explained the "conflict".

If you need the `Roots/soil` plugin to load after your theme `supports.config.php` file, you'll need to manually change the priority of the `add_action()`:

```php
// In the plugin
add_action('after_setup_theme', __NAMESPACE__. '\\load_modules', 12, 3);
```
Probably for next release, it won't be necessary to bootstrap the framework with `after_setup_theme` or I will lower the priority so it loads before everything else.

Let me know how it goes.

**Comment by jlambe** [comment]
Hi @Cezarion ,
the framework 1.2.0 won't load based on WordPress hooks so in theory you won't get execution order issues and it should bootstrap faster.
