### ISSUE TITLE
Themosis and Custom frontend Userflow

### ISSUE THREAD

**Issue by aliasim** [themosis/themosis#54]
So I'm working towards a ecommerce solution using themosis / stripe checkout (popup) version.
I want to base it of the following theme:
http://live.spacexthemes.com/xscholar/

I want to do a full user registration / dashboard flow - the way these guys have done it in the (xscholar) theme is using - https://github.com/dasllama/User-Frontend

when I use the form code provided in the theme - it gives me "theme without header.php is deprecated since version 3.0 ... warning

I realize I need to make sure the route is in place for post - but not sure how should I go about it.

Ideally I would like to use the Scout's form validation and other goodies on all the forms for the user flow.

thanks,
Ali

**Comment by jlambe** [comment]
Hi,

1.header.php: simply add an empty header.php file at the root of your theme and work from there if the theme needs it. Or you can find the line for this warning and remove it.
2. You can use any APIs of the framework anywhere.
3. Regarding the Scout engine, simply create views as usual inside the `views` directory. And if you need to use the default `header.php` file, type this code, for example, inside the file:
```php
<?php
// Start of header.php - Use a view to build the header content...
$view = View::make('header')->render();
echo($view);
````
The code above is going to echo the view called `header.scout.php` located inside the root of your views directory. Use the `render()` method to build the output of your view and echo it.
Hope this helps.
