### ISSUE TITLE
lost-password/ Permalink

### ISSUE THREAD

**Issue by djgadd** [themosis/themosis#55]
The lost-password/ permalink appears to be getting processed by the routes file, can't see anything in the docs to indicate this is intentional. I don't think it's anything I've done, I removed all routes and it's still being picked up (though pointing to the 'no matching routes' error page) and I've had a look through the various config files and can't see anything. It appears to be getting intercepted by the home route at the moment.

Is this intentional or a bug?

**Comment by jlambe** [comment]
Hi,
the default lost-password URI is this one: `http://yourdomain.com/wp-login.php?action=lostpassword`. Normally this one is working as expected.
Do you have any plugins that overwrite this default URI for lost-password, like WooCommerce for example: `my-account/lost-password`?
If that's the case, you're using a WordPress page so you need to specify a route to display it.

**Comment by djgadd** [comment]
It was woo-commerce, my apologies I'd completely forgotten it does that.

Thanks!
