### ISSUE TITLE
Post Type specific view?

### ISSUE THREAD

**Issue by anakinjay** [themosis/themosis#57]
Hello!

Not a wordpress guy for the exact reason you built this framework. Love it so far!  I've followed along the docs all the way until post type views.

I'm making a custom post type which works fine:
```
PostType::make('mando', 'Mandalorians', 'Mandalorian')->set();

$fields = array(
  Field::text("Name", $extras = array()),
  Field::text("Rank", $extras = array()),
  Field::text("Brigade", $extras = array()),
  Field::select("Clan", array(array("BMG"=>"Black Mountain Guard","OTHER"=>"Some Other Cool Clan")), $multiple = false, $extras = array()),
  Field::textarea("Comments", $extras = array()),
  Field::checkbox("Official Member", array("Yes","No"), $extras = array()),
  
);

Metabox::make("Mando Info", "mando", $options = array(), $view = null)->set($fields);

```

then in my routes.php file I have:
```
Route::get('postTypeArchive', array('mando', function(){

    return View::make('page');

}));

Route::get('single', array('mando', function(){

    return View::make('page');

}));

```

When I go to view a post of my custom post type though, it tells me:
"No route defined for this request..."

Any idea what I'm doing wrong?  I'm sure I'm just missing something dumb.   
Thanks!

**Comment by jlambe** [comment]
Hi,

use this code for single custom post type view:
```php
Route::get('singular', ['mando', function()
{
    return View::make('page');
}])
```

This should keep you on track ;)

**Comment by anakinjay** [comment]
Thanks for the quick reply but it's still not working for me :(   I even took out all my other routes, and copy and pasted in what you suggested as the only route and it still isn't working.

**Comment by jlambe** [comment]
Ok I found the other issue, by default your custom post type is not set as public. Update your `PostType` code as follows:
```php
PostType::make('mando', 'Mandalorians', 'Mandalorian')->set([
    'public'    => true
]);
```
By specifying your custom post type to be public, Wordpress will generate URLs to access them. Visit the permalinks page once after this code update and try to visit your post type in the front. Let me know how it goes!

**Comment by anakinjay** [comment]
That worked!  Thank you so much! :+1:

**Comment by jlambe** [comment]
Cool, glad it works :smile:
