### ISSUE TITLE
Is there a way to say "if @yield('footer') is empty hide it"

### ISSUE THREAD

**Issue by tdserviceco** [themosis/themosis#58]
Hi liking the framework (just playing around right now) and was wondering like the title says if there is a "if" or "else" way?

**Comment by jlambe** [comment]
Hi,
the `@yield` statement defines an area in a layout. By default it is empty and somehow hidden. I suggest you to look at variable you want to pass to your view and check if its value is empty or not and then provides an `@if` statement to show or hide your content.
