### ISSUE TITLE
Follow up on Issue 51

### ISSUE THREAD

**Issue by tdserviceco** [themosis/themosis#59]
Hi again!
I got shop to work but somehow the instuction on how to get production to work doesnt work 100%

This is how it looks like.
![skarmavbild 2015-11-24 kl 16 20 03](https://cloud.githubusercontent.com/assets/10770786/11371137/4285dca6-92c7-11e5-9db6-6b8fe8bda726.png)

and 2nd question is on cart/cart when empty.. are they 1 same file? I didnt need to use a custom route to get it to work.. but I want to style it myself via the custom route.. but it doesnt seem to work for me..

Did I do something wrong here?

**Comment by jlambe** [comment]
I suppose they use the same file, check their templates. Inside the `woocommerce` plugin, there is a `templates` folder with all the templates for the front-end. Check those for the cart. If there are 2 templates, create both in the root of your theme and call your custom view on it. 

If they use the same template, check the query var value. Depending of its value, use the appropriate view. Or if you really want to play with the route, create a function that check the cart template query var, add it to the custom route array through the filter, then write your route as usual.

**Comment by tdserviceco** [comment]
Okay, how about my first question then? Why doesnt my layout match my master file?
![skarmavbild 2015-11-24 kl 18 28 32](https://cloud.githubusercontent.com/assets/10770786/11375004/3629a660-92d9-11e5-81bd-42bb9084aaa8.png)

And this is how my "shop.php" looks like in admin folder:
![skarmavbild 2015-11-24 kl 18 27 16](https://cloud.githubusercontent.com/assets/10770786/11375021/48426878-92d9-11e5-8866-727d9f45fea7.png)

And this is how routes.php looks like:
![skarmavbild 2015-11-24 kl 18 27 29](https://cloud.githubusercontent.com/assets/10770786/11375035/57dac50a-92d9-11e5-8cdf-b09cef5bb3b7.png)

and how my controller.php looks like:
![skarmavbild 2015-11-24 kl 18 26 56](https://cloud.githubusercontent.com/assets/10770786/11375040/629c1b74-92d9-11e5-9205-7ca61fd0107d.png)

Is there im missing? since master.scout.php is working and shop is working but not single_product...

**Comment by jlambe** [comment]
Probably the request to your single product in routes.php which is wrong. Products are custom post type, Try the `Route::get('singular', 'product', 'AppController@posts');` Verify in WordPress the product custom post type slug name, can't remember if its singular or plural.

**Comment by tdserviceco** [comment]
I got it to work.. somehow the "position" on my routes was wrong.. i put my product on top and then it worked...  (after I changed some code) I post image later

**Comment by jlambe** [comment]
Glad you solved your issue.
