### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by ekandreas** [themosis/themosis#60]
Probably beginners trouble. I'm all new to Themosis.
Running Themosis inside a Homestead Vagrant box, configed the .env.local.php and wp install pages gives the following error result:

Unhandled Exception

Message:

Undefined index: host
Location:

/home/vagrant/www/intra/htdocs/cms/wp-includes/http.php on line 468
Stack Trace:

#0 /home/vagrant/www/intra/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(8, 'Undefined index...', '/home/vagrant/w...', 468)
#1 /home/vagrant/www/intra/htdocs/cms/wp-includes/http.php(468): THFWK_Themosis->{closure}(8, 'Undefined index...', '/home/vagrant/w...', 468, Array)
#2 /home/vagrant/www/intra/htdocs/cms/wp-includes/class-http.php(186): wp_http_validate_url('https://downloa...')
#3 /home/vagrant/www/intra/htdocs/cms/wp-includes/class-http.php(426): WP_Http->request('https://downloa...', Array)
#4 /home/vagrant/www/intra/htdocs/cms/wp-includes/http.php(72): WP_Http->get('https://downloa...', Array)
#5 /home/vagrant/www/intra/htdocs/cms/wp-admin/includes/file.php(461): wp_safe_remote_get('https://downloa...', Array)
#6 /home/vagrant/www/intra/htdocs/cms/wp-admin/includes/class-wp-upgrader.php(237): download_url('https://downloa...')
#7 /home/vagrant/www/intra/htdocs/cms/wp-admin/includes/class-wp-upgrader.php(650): WP_Upgrader->download_package('https://downloa...')
#8 /home/vagrant/www/intra/htdocs/cms/wp-admin/includes/class-wp-upgrader.php(1956): WP_Upgrader->run(Array)
#9 /home/vagrant/www/intra/htdocs/cms/wp-admin/includes/class-wp-upgrader.php(1846): Language_Pack_Upgrader->bulk_upgrade(Array, Array)
#10 /home/vagrant/www/intra/htdocs/cms/wp-admin/includes/translation-install.php(209): Language_Pack_Upgrader->upgrade(Array, Array)
#11 /home/vagrant/www/intra/htdocs/cms/wp-admin/install.php(258): wp_download_language_pack('sv_SE')
#12 {main}

**Comment by ekandreas** [comment]
Selecting the english version of WP doesn't give the error. I'm going to try the localized wp version of WP in the composer.json settings.

**Comment by ekandreas** [comment]
No, the swedish localized WP generates the "Undefined index: host" directly.

**Comment by jlambe** [comment]
Hi @ekandreas, it is a core WordPress issue apparently. Set your local environment to not report all errors by setting the `THEMOSIS_ERROR_REPORT` constant to `0` inside your `config/environments/local.php` file. Do your installation then reset the value to `-1` for development.

I've reported this issue on WordPress trac but it hasn't been fixed yet: https://core.trac.wordpress.org/ticket/34164

**Comment by jlambe** [comment]
@ekandreas The issue has been reproduced by WordPress core developers. Hope this will come for next release or at least next minor one.

**Comment by BenceSzalai** [comment]
> Hi @ekandreas, it is a core WordPress issue apparently. Set your local environment to not report all errors by setting the `THEMOSIS_ERROR_REPORT` constant to `0` inside your `config/environments/local.php` file. Do your installation then reset the value to `-1` for development.

This advice seems to be outdated. I was getting the same error when using a non "English (United States)" language during install. I've managed to set up WP with non default locale by setting `APP_DEBUG=false` in `.env`.

```
ErrorException thrown with message "Undefined index: host"

Stacktrace:
#6 ErrorException in /home/vagrant/code/htdocs/cms/wp-includes/l10n.php:1075
#5 Themosis\Core\Bootstrap\ExceptionHandler:handleError in /home/vagrant/code/htdocs/cms/wp-includes/l10n.php:1075
#4 load_script_textdomain in /home/vagrant/code/htdocs/cms/wp-includes/class.wp-scripts.php:582
#3 WP_Scripts:print_translations in /home/vagrant/code/htdocs/cms/wp-includes/class.wp-scripts.php:314
#2 WP_Scripts:do_item in /home/vagrant/code/htdocs/cms/wp-includes/class.wp-dependencies.php:116
#1 WP_Dependencies:do_items in /home/vagrant/code/htdocs/cms/wp-includes/functions.wp-scripts.php:109
#0 wp_print_scripts in /home/vagrant/code/htdocs/cms/wp-admin/install.php:452
```

On the other hand I have no idea why am i getting this same issue, when using a non "English (United States)" language while the related WP issue was closed 5 years ago... Should I open a new one for this?
