### ISSUE TITLE
Featured Image on Woocommerce

### ISSUE THREAD

**Issue by tdserviceco** [themosis/themosis#61]
Hi.. where do I add the featured image?
IT wont show then I go to product.. is it in support.config.php file?
or do I need to add somewhere else?

add_theme_support( 'post-thumbnails' );

**Comment by jlambe** [comment]
In the `support.config.php`file, add the `product` custom post type slug in the post-thumbnails array.

**Comment by tdserviceco** [comment]
Thanks :D like always your quick and easy to fix my problems :+1:

**Comment by jlambe** [comment]
Don't forget it is still php and WordPress development at the end. The framework mainly provides a code structure only. So for some issues, don't hesitate to also look on the WordPress codex and php resources for help.
I'm glad your issue is solved. I'm closing this ticket now.
