### ISSUE TITLE
Implement Scout equivalent of get_template_part

### ISSUE THREAD

**Issue by ArondeParon** [themosis/themosis#62]
As it is now, there does not seem to be a proper equivalent of `get_template_part`. In my opinion, this would be a good addition to the Scout compiler, because it decreased code repetition. 

For example: 

I have several post types, all with archives. The actual templates are pretty much the same, but the way the individual posts are rendered differs. Currently, there are two ways to handle this kind of situation:
1. Create multiple archive templates and use the router to route the CPTs to the corresponding templates
2. Use a single archive template with a lot if/else statements. 

My suggestion: extend the `@include` operator with an optional second argument, mimicking the original `get_template_part` syntax. That way, you could have a single template with multiple content types in it as such:

`@include('pages.content', $contentType)`

**Comment by jlambe** [comment]
Can you provide a code example of what you're trying to achieve and what would you like to suggest with the `@include` statement so I can better understand ?

**Comment by lauhakari** [comment]
@ArondeParon couldn't you just do a @include('pages.content.' . $contentType) ?

But yeah I see what you mean and it could be nice. Looks nicer with a parameter.

**Comment by ArondeParon** [comment]
@lauhakari that would break when a page of that type is not present. The great thing about `get_template_part` is that the `type` argument is optional and provides native fallback capabilities. This allows developers to write extensible page templates that don't need to be overridden when you want to change the "inner" contents.

**Comment by jlambe** [comment]
@ArondeParon Ok I seem to understand what you're trying to achieve thanks to @lauhakari comment.

Currently the second argument of `@include` is used to pass data to the included view file. Don't forget that you can use the `get_template_part()` inside your view between PHP tags.

If we wanted to add a scout statement for this, I would suggest to create a new tag like for example `@template` which is not yet used with the engine and would wrap the `get_template_part()` function.

**Comment by ArondeParon** [comment]
Seems like a pretty good idea :) 

Would love to be able to do these kind of things myself, but as it is now, it does not seem to be possible to override core igniterservices. Am I right? :)

**Comment by jlambe** [comment]
There is a hack but it won't be compatible with next release as I want to provide an easy/structured way of doing it.
But you can still contribute by forking the `themosis/framework` repository and make a pull request with your feature.

**Comment by jlambe** [comment]
@ArondeParon I'm going to move this feature for the next release as it demands more work. In order to get fallback capabilities with the views, we need to define an index of views to minimally use in all projects. Without that, it's just creating a view directive to include a view based on a base path into which we can append or not a view file name which doesn't bring that much.

The next version has full Blade templating so it is easy to create custom directives by project. You can explore the idea of an `@template()` directive and I'll be happy to dig more into it for the next release.

**Comment by jlambe** [comment]
@ArondeParon I'm going to close the issue here and re-open it on the `themosis/framework` repository as it is best suited there.

**Comment by jlambe** [comment]
https://github.com/themosis/framework/issues/355
