### ISSUE TITLE
Using Themosis with Divi theme

### ISSUE THREAD

**Issue by NettSite** [themosis/themosis#64]
Hi,

I saw in a prevuious thread that one should be able to use Themosis with a theme other than the "themosis-theme".

I want to use Divi by Elegant Themes, as it handles all the display stuff just as I want it to, but I need to add a lot of functionality beyond the typical WordPress blog / CMS thing.

I have developed a bit of a plugin framework, but Themosis looks better. 

How should I use Themosis with Divi - or any other theme?

I have had a bash at installing Divi in the normal WordPress way, but if I activate it I get:

`Unhandled Exception

Message:

The called constructor method for WP_Widget is deprecated since version 4.3.0! Use 
__construct()
 instead.
Location:

/home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/functions.php on line 3619
Stack Trace:

#0 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(1024, 'The called cons...', '/home/nettsite/...', 3619)
#1 [internal function]: THFWK_Themosis->{closure}(1024, 'The called cons...', '/home/nettsite/...', 3619, Array)
#2 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/functions.php(3619): trigger_error('The called cons...')
#3 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/class-wp-widget.php(171): _deprecated_constructor('WP_Widget', '4.3.0')
#4 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/content/themes/Divi/includes/widgets/widget-about.php(6): WP_Widget->WP_Widget(false, 'ET About Me Wid...', Array, Array)
#5 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/class-wp-widget-factory.php(43): AboutMeWidget->AboutMeWidget()
#6 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/widgets.php(113): WP_Widget_Factory->register('AboutMeWidget')
#7 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/content/themes/Divi/includes/widgets/widget-about.php(58): register_widget('AboutMeWidget')
#8 [internal function]: AboutMeWidgetInit('')
#9 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/plugin.php(525): call_user_func_array('AboutMeWidgetIn...', Array)
#10 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/widgets.php(1463): do_action('widgets_init')
#11 [internal function]: wp_widgets_init('')
#12 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-includes/plugin.php(525): call_user_func_array('wp_widgets_init', Array)
#13 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-settings.php(392): do_action('init')
#14 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/wp-config.php(16): require_once('/home/nettsite/...')
#15 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-load.php(42): require_once('/home/nettsite/...')
#16 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-admin/admin.php(31): require_once('/home/nettsite/...')
#17 /home/nettsite/domains/themosis.tk/jhbchev/htdocs/cms/wp-admin/index.php(10): require_once('/home/nettsite/...')
#18 {main}`

**Comment by NettSite** [comment]
Sorry, not a Themosis issue - it is a Divi problem.

Am I correct that to use another theme I add the "resources" folder to it?

**Comment by jlambe** [comment]
Indeed, your Divi theme is not up to date. The error you get is from the Themosis framework error handling mechanism. By default, on a `local` environment, all errors  are shown.

So if you want to use your own theme, the Divi one, just adding the `resources` will not make it work. it does already work as the main plugin from the framework is adding PHP classes that are globally available to plugins and themes.

For example, let's say you want to add a custom post type from your current theme `functions.php`, just write this code:
```php
// Inside the functions.php file
PostType::make('cpt-slug', 'PluralName', 'SingularName')->set(['public' => true]);
```

If you use the latest version, PHP aliases are already defined for you from the framework. In case you haven't them, use the PHP class long name: `\Themosis\Facades\PostType::make()`.

Also, check the `themosis-theme` [functions.php](https://github.com/themosis/theme/blob/master/functions.php#L146) file to add your theme paths thanks to the `themosis_set_paths()` function and check the [bootstrap/start.php](https://github.com/themosis/theme/blob/master/bootstrap/start.php) file to add extra framework functionalities to your Divi theme.

**Comment by NettSite** [comment]
Thanks, I really appreciate the help!

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>
