### ISSUE TITLE
Metabox 'post-thumbnails' not longer working?

### ISSUE THREAD

**Issue by APEWAW** [themosis/themosis#67]
Hello, 

The 'post-thumbnails' support seems not longer working since the last WordPress update. The metabox has disappeared on posts and pages, but it still there for custom posts. 

Do you have any idea?

Thank you for your help, 
Amandine

**Comment by jlambe** [comment]
Hi,
'post-thumbnails' output the "Featured Image" metabox. If you define your custom post type to support 'post-thumbnails', you also have to define your custom post type slug inside the `supports.config.php` file of your theme.

Currently I haven't encounter this issue with latest version of WordPress, can you post your code?

**Comment by APEWAW** [comment]
Hello, 

Thank you for your reply.

In fact, it works perfectly for my custom posts but not for default post/page WP format. Really strange...
 
Here is my code:

<?php
return array(
  /**
   * Edit this file to add features to your theme. Un-comment each feature to
   * add it.
   * http://codex.wordpress.org/Function_Reference/add_theme_support
   */

  /* --------------------------------------------------------------- */
  // Enable post thumbnails
  /* --------------------------------------------------------------- */

  'post-thumbnails' => array('post', 'slide', 'page', 'team-member', 'client', 'event', 'download', 'learning'),

**Comment by jlambe** [comment]
Code seems correct...
What about de-activating each plugin and check how it works?
Also, is the "Featured image" metabox is displayed when you look at the "Screen options" on top right of the posts and pages screens?

**Comment by APEWAW** [comment]
Hello, 

Thank your for the tip. 
I just checked and the bug is due to WP eCommerce plugin... :(

**Comment by jlambe** [comment]
Try the previous version and warn the plugin author, perhaps there is a fix.
