### ISSUE TITLE
Composer install issue - Set https for wpackagist

### ISSUE THREAD

**Issue by tomhking** [themosis/themosis#71]
I get the following error when trying to run `composer install`

` [Composer\Downloader\TransportException]
  Your configuration does not allow connection to http://wpackagist.org. See
  https://getcomposer.org/doc/06-config.md#secure-http for details.`

Any help would be appreciated.

**Comment by jlambe** [comment]
Hi,

sorry for late response but it seems that you have added a `secure-http:true` statement inside your `composer.json`. The error you receive tell composer to only fetch packages from `https` URLs which wpackagist.org is not.

Remove that statement and run your `composer install` or `composer update` command in the cli and it should be good to go ;)

**Comment by tomhking** [comment]
Thanks a ton! Oh, and no need to apologize. I'm sure you're plenty busy.

**Comment by smcjones** [comment]
This is the top hit when I googled, so fwiw, the quick fix for this issue is to just use https://wpackagist.org rather than http://wpackagist.org. For some reason, they do not have that in their documentation. I will give them a heads up.

**Comment by jlambe** [comment]
Didn't know the repositories were available under https. Thanks @smcjones, will update composer for next release.

**Comment by jess-bart** [comment]
Hello, maybe its a dumb question but where can I change the repository via a windows installation?
I'm new in composer and i have installed it with the installer.
After I launch the command : composer create-project themosis/themosis my-project-name
Where can i change the repo? 
Thanks

**Comment by jlambe** [comment]
Simply open the `composer.json` file at the root of your project and look after the `http://wpackagist.org` reference to update it. Save your file then run as many `composer update` commands to download plugins.

**Comment by jess-bart** [comment]
But I have no project and no composer.json :(

**Comment by jlambe** [comment]
@jess-bart Normally after the create-project command you typed above, there should be a folder called `my-project-name` on your computer with a `composer.json` file in it otherwise you should have had errors on your console.

**Comment by budda** [comment]
@jess-bart @jlambe Same issue for me - using ```→ composer create-project``` I cannot connect to the ```--repository-url=``` specified.

I've added ```    "config": {
        "secure-http": false
    }``` to my config and tried changing global composer.json, deleting the composer.lock, adding a new project level composer.json file too.

Testing with:
```Composer version 1.0-dev (a8e9df55dc62d8806360be2f79ad112b8678d397) 2016-03-17 11:42:19```

**Comment by jlambe** [comment]
That's weird as I can't manage to reproduce the issue.
When you create your project following the documentation, you get the error directly? or is it later when you update your `composer.json` file to add plugins from `wpackagist` ?

**Comment by tomhking** [comment]
This problem occurs on Windows 10 but not OS X. I haven't tested it on Windows 8 and have not tested recently on Windows 7, but until I upgraded Windows 10 about 4 months ago from Windows 7, I never had this problem.

**Comment by jlambe** [comment]
Ok will test this then on Windows 10. It's really weird.

**Comment by jlambe** [comment]
I encounter the issue on installing a project on a Debian machine. A `https` connection was required in order to install the dependencies coming from WPackagist. The fix was simply to define the URL like this `https://wpackagist.org` in the `composer.json` file and it worked like expected.

I haven't yet test on windows 10, will update this soon.

**Comment by tomhking** [comment]
Very strange, indeed. I'm not getting the error on Ubuntu 14.04. Thanks for looking into it, Julien.

**Comment by wunc** [comment]
I just updated my composer and noticed this issue pop up. It probably has to do with the composer version: more recent versions default to `secure-http: true`. See https://github.com/composer/composer/releases/tag/1.0.0-beta1 and the bolded breaking change.

So, if you haven't updated your composer version for awhile, you won't see the secure-http error. Fix would be to either set it to false or change wpackagist to https.

**Comment by jlambe** [comment]
@wunc Thanks for the precision. I can confirm on Windows 10 that it's working correctly with url set to `https` and running latest version of Composer.

**Note**: Join the [Gitter chat room](https://gitter.im/themosis/framework?utm_source=share-link&utm_medium=link&utm_campaign=share-link) about the framework. There is also [showcase room](https://gitter.im/themosis/framework/showcase?utm_source=share-link&utm_medium=link&utm_campaign=share-link) for those who want to show their work.

**Comment by lojasmarques** [comment]
Look, I cannot solve this problem, if someone could help me, i really apreciated that help.
My WhatsApp is +55 53 981426029

**Comment by flik** [comment]
Here is simple solution:
`composer config -g secure-http false`
