### ISSUE TITLE
Setup for Shared Hosting Environments?

### ISSUE THREAD

**Issue by techpines** [themosis/themosis#72]
How do you setup Themosis to operate in shared hosting environments, or is this even possible.

Specifically, I'm looking to setup a Themosis site on WPEngine.com.  However, they only give you access to the `wp-content` folder.

Will Themosis work in this type of environment?

**Comment by jlambe** [comment]
Yes you can install it but you can't use the default installer with Composer as explained in the docs.

All you need is to install the `themosis/framework` package as a `mu-plugins` or `plugins` and install a copy of the `themosis-theme` inside your current `themes` directory.

You can simply get a copy of each from our Github account. Once you unarchived the plugin, open the command line tool and navigate to the root of the `themosis-framework` plugin and run the `composer install` command.

Then simply activate the plugin (if installed as a plugin) and activate your theme and you're good to go.
Not sure if WPEngine allows you to define mu-plugins but don't worry, install the framework as a plugin.

Using the framework in a "classic" WordPress installation won't give you access to the multiple environments but all the other APIs are available.

Let me know how it goes with you installation.

**Comment by techpines** [comment]
I'm getting the following error:

```md
Themosis framework: The autoload.php file is missing or there is 
a namespace error inside your composer.json file.
```

https://github.com/themosis/framework/blob/master/bootstrap/start.php#L21

I guess it's an autoloading issue, but I'm not sure how to debug it / fix it.  

Any ideas?

**Comment by jlambe** [comment]
Did you run the `composer install` command inside the plugin?
Can you describe all the steps you've done in order to install WordPress and the framework, it will help me find what's missing?

**Comment by techpines** [comment]
I ran `composer install` inside the framework folder, which created a `vendor` folder.   The plugin was recognized by wordpress, and I was able to activate it.

However based on the error I'm getting above, it seems like it's not autoloading the initial Themosis class based on this line:

https://github.com/themosis/framework/blob/master/bootstrap/start.php#L14

**Comment by techpines** [comment]
@jlambe Alright, progress!  

I was using Git to push the code up, and the vendor folders weren't getting pushed up because of the .gitignore files.  So I fixed that, which is great.

Now, I'm getting the following because it can't find `storage/views`, do you know how I can configure / fix this one?

```
Unhandled Exception

Message:

_wpe_old_file_put_contents(//views/e6bc21f0f706880185e78af2e7836fdf): failed to open stream: No such file or directory
Location:

/opt/nas/www/common/production/php_prevent_flock.php on line 22
```

**Comment by techpines** [comment]
Alright, I'm all sorted out now.

For posterity, on a "classic" wordpress install you also need to add `storage/views` to `wp-content`.  As it is written here in the docs:

https://github.com/themosis/documentation/blob/master/installation.md#project-structure

Closing this issue, great framework @jlambe

**Comment by jlambe** [comment]
Thx for the reminder, I forgot to tell you about the `storage` folder... Glad I put it in the docs :smile:

**Comment by marcell-ferenc** [comment]
First of all thanks for this great framework @jlambe . I have some additional info that may could help someone in the future.

According to the descriptions found above I successfully deployed a `themosis/framework` based  theme in a classic WP project on [WPEngine](https://wpengine.com/) recently. However at the very beginning I have experienced some challenges due to WPEngine's limitations. At the very beginning I have received errors from `\Twig_Cache_Filesystem`:

> PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to write cache file ...

After a quick search I arrived to a github post [Twig cache fails to save on WP Engine](https://github.com/timber/timber/issues/1311) related to this problem. [After some experiment](https://github.com/timber/timber/issues/1311#issuecomment-379058476) and reading I found that WPEngine prohibit the creation of `.php` files under the `wp-content/storage/twig` folder. As an ugly but a quick solution I directly modified `\Twig_Cache_Filesystem` and that worked which proved this assumption. Now I just need to apply these changes on a robust way.

**Comment by marcell-ferenc** [comment]
I can extend `Twig_Cache_Filesystem` to implement my changes.
Also I can feed a `Twig_Cache` instance as a `cache` option to `Twig_Environment`.

Could you give me some hints how to extend `Themosis\View\ViewServiceProvider` in a robust way to accept a different `cache` option than `'cache' => $container['path.storage'].'twig'`?

**Comment by moometric** [comment]
@marcell-ferenc did you ever find a solutions to this on WPEngine - Facing the same issue

**Comment by marcell-ferenc** [comment]
@moometric [this was the solution](https://github.com/timber/timber/issues/1311#issuecomment-379058476) that worked for me WPEngine.

**Comment by alcook** [comment]
> You can simply get a copy of each from our Github account. Once you unarchived the plugin, open the command line tool and navigate to the root of the `themosis-framework` plugin and run the `composer install` command.

Are these steps this still accurate?

I've followed the steps (getting source from https://github.com/themosis/framework) but I can't get Wordpress to recognise it as a plugin once copied to wp-content/plugins.

**Comment by jlambe** [comment]
@alcook The Themosis framework is no longer a WordPress plugin and honestly has never intended to be one. It's custom stack to build WordPress application and I'm not sure WPEngine is flexible enough to run it.

If you want to learn more about working with the Themosis framework, you can take a look at our ["Getting started" tutorial](https://blog.themosis.com/2019/11/21/getting-started-with-the-themosis-framework-part-1/) and see how the stack is structured and perhaps how it might fit to your hosting provider.

**Comment by alcook** [comment]
Thanks @jlambe, I appreciate the update. The framework looks like a great solution, we'll check it out for future projects.

**Comment by jlambe** [comment]
@alcook No problem at all 😉 We also provide an enterprise support to help people get on board on their new Themosis framework projects:

- https://support.themosis.com

**Comment by iamroi** [comment]
@jlambe Great framework! It's a bit disappointing that I can't use it with WPEngine as our agency hosts all of the projects there.

It would be great to have some flexibility or a hack to support WPEngine. Thanks
