### ISSUE TITLE
Unhandled exception after installation - Let git push empty directories (storage/views)

### ISSUE THREAD

**Issue by Specro** [themosis/themosis#73]
Hi,
I installed the framework according to the documentation but I get an exception upon entering the page:

Unhandled Exception

Message:

file_put_contents(//views/f885ab824a4e0fff32c94b368aa5e1a1): failed to open stream: No such file or directory
Location:

/app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Compilers/ScoutCompiler.php on line 58
Stack Trace:

#0 /app/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(2, 'file_put_conten...', '/app/htdocs/con...', 58)
#1 [internal function]: THFWK_Themosis->{closure}(2, 'file_put_conten...', '/app/htdocs/con...', 58, Array)
#2 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Compilers/ScoutCompiler.php(58): file_put_contents('//views/f885ab8...', '...')
#3 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/ScoutEngine.php(48): Themosis\View\Compilers\ScoutCompiler->compile('/app/htdocs/con...')
#4 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(109): Themosis\View\Engines\ScoutEngine->get('/app/htdocs/con...', Array)
#5 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(92): Themosis\View\View->getContent()
#6 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(69): Themosis\View\View->renderContent()
#7 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/View.php(288): Themosis\View\View->render()
#8 /app/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(422): Themosis\View\View->__toString()
#9 /app/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Symfony\Component\HttpFoundation\Response->setContent(Object(Themosis\View\View))
#10 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(311): Symfony\Component\HttpFoundation\Response->__construct(Object(Themosis\View\View))
#11 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(283): Themosis\Route\Router->prepareResponse(Object(Themosis\Core\Request), Object(Themosis\View\View))
#12 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(249): Themosis\Route\Router->dispatchToRoute(Object(Themosis\Core\Request))
#13 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(238): Themosis\Route\Router->dispatch(Object(Themosis\Core\Request))
#14 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(223): Themosis\Core\Application->dispatch(Object(Themosis\Core\Request))
#15 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(207): Themosis\Core\Application->handle(Object(Themosis\Core\Request))
#16 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(109): Themosis\Core\Application->run('', NULL)
#17 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionNotifier.php(28): Themosis\Action\Action->run()
#18 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionSubject.php(27): Themosis\Action\ActionNotifier->update()
#19 /app/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(96): Themosis\Action\ActionSubject->notify()
#20 /app/htdocs/cms/wp-includes/plugin.php(525): Themosis\Action\Action->action('')
#21 /app/htdocs/content/themes/finnto/bootstrap/start.php(224): do_action('themosis_run')
#22 /app/htdocs/content/themes/finnto/index.php(9): themosis_start_app()
#23 /app/htdocs/cms/wp-includes/template-loader.php(89): include('/app/htdocs/con...')
#24 /app/htdocs/cms/wp-blog-header.php(16): require_once('/app/htdocs/cms...')
#25 /app/htdocs/index.php(11): require('/app/htdocs/cms...')
#26 {main}

Admin panel seems to be working correctly. I'm using Heroku with Apache. What may be causing this issue?

**Comment by jlambe** [comment]
Do you have a `storage/views` directory at the root of your project?

**Comment by Specro** [comment]
Yeah, I have. 
This is how my root directory looks if it's any help:
![image](https://cloud.githubusercontent.com/assets/15341550/13722925/ceb9785e-e85d-11e5-99dc-709079a87d49.png)

**Comment by jlambe** [comment]
Is it working locally?
It seems your application do not have the path to the `storage` directory. It tries to get a compiled view to this path: `//views/f885ab824a4e0fff32c94b368aa5e1a1`, which is wrong.

Do you have this constant in your `themosis-framework/themosis.php` mu-plugin file: https://github.com/themosis/framework/blob/master/themosis.php#L25

**Comment by Specro** [comment]
That's the thing - locally everything works correctly.
I checked the file and the constant is there.

I'll try to debug more when I have time to figure this out.

**Comment by jlambe** [comment]
Ok, let me know how it goes. Perhaps there is something to enhance with file paths.

**Comment by Specro** [comment]
I figured it out, `storage/views` directory actually was missing in the remote production repo. I used git to push the project to the server and it doesn't add empty directories. That's why those folders weren't pushed. 

As a fix I entered this line `!.gitignore` in the `storage/views/.gitignore`. 

Sorry for bothering you and thank you for the help :)

**Comment by jlambe** [comment]
No need to be sorry! I'm glad your issue is solved. Will add this fix for next release!

**Comment by jlambe** [comment]
Fixed.
