### ISSUE TITLE
Bug with Yoast plugin?

### ISSUE THREAD

**Issue by APEWAW** [themosis/themosis#74]
Hello, 

I get a strange issue when the Yoast plugin. Setting tabs don't load in the administration.

Here is the error message: 

> Unhandled Exception
> Message:
> 
> Undefined property: stdClass::$wp_locale
> 
> Location:
> 
> /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/vendor/yoast/i18n-module/i18n-module.php on line 253
> 
> Stack Trace:
> 
> #0 /Sites/Matriochka/htdocs/content/themes/matriochka/functions.php(232): Themosis\Error\Error::native(8, 'Undefined prope...', '/Sites/Matrioch...', 253)
> #1 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/vendor/yoast/i18n-module/i18n-module.php(253): {closure}(8, 'Undefined prope...', '/Sites/Matrioch...', 253, Array)
> #2 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/vendor/yoast/i18n-module/i18n-module.php(215): yoast_i18n->retrieve_translation_details()
> #3 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/vendor/yoast/i18n-module/i18n-module.php(228): yoast_i18n->find_or_initialize_translation_details()
> #4 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/vendor/yoast/i18n-module/i18n-module.php(187): yoast_i18n->translation_details()
> #5 [internal function]: yoast_i18n->promo('')
> #6 /Sites/Matriochka/htdocs/cms/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
> #7 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/admin/class-yoast-form.php(112): do_action('wpseo_admin_foo...')
> #8 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/admin/pages/dashboard.php(261): Yoast_Form->admin_footer()
> #9 /Sites/Matriochka/htdocs/content/plugins/wordpress-seo/admin/class-admin.php(352): require_once('/Sites/Matrioch...')
> #10 [internal function]: WPSEO_Admin->load_page('')
> #11 /Sites/Matriochka/htdocs/cms/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
> #12 /Sites/Matriochka/htdocs/cms/wp-admin/admin.php(236): do_action('toplevel_page_w...')
> #13 {main}
> 

Can you help me to solve this?

Thank you in advance, 
Amandine

**Comment by jlambe** [comment]
It's an error inside the SEO plugin in fact... which is detected by the framework and displayed for you.

To avoid this during local development, you can de-activate the display for errors by setting the `THEMOSIS_ERROR_REPORT` constant value to `0` inside the `config/environments/local.php` file located at the root of your project.

**Comment by APEWAW** [comment]
Hello Julien, 

Thank you for your prompt and operative reply! 
This fixed the issue. 

I have similar troubles with other plugin like wpecommerce (impossible to download product image due to an ajax error). Do you also have a track for this?

Thank you, 
Amandine

**Comment by jlambe** [comment]
Hmm nope. Be sure to run on their latest version otherwise submit your issue to their support. I won't be able to help in this case.

**Comment by sergiohidalgo** [comment]
```php
if(strpos($_SERVER['REQUEST_URI'], 'wpseo')):
	define('THEMOSIS_ERROR_REPORT', 0);
else:
	define('THEMOSIS_ERROR_REPORT', -1);
endif;
```
