### ISSUE TITLE
Installation problem: Access denied

### ISSUE THREAD

**Issue by mehany** [themosis/themosis#75]
I have and themosis site running on LEMP on vagrant on my local machine, when I pushed the same code to my production LEMP server i get ** access denied**.  I am not even sure how to start troubleshooting the issue since all my configuration seem to be fine.

.env.production.php and .env.local.php are the same
```
   return [

    'DB_NAME'       => 'example_db',
    'DB_USER'       => 'db_user',
    'DB_PASSWORD'   => 'db_password',
    'DB_HOST'       => 'localhost',
    'WP_HOME'       => 'https://example.com',
    'WP_SITEURL'    => 'https://example.com/cms'

   ];
```
#### nginx block

```
   server {
     listen 80;
     server_name example.com  www.example.com;
     # enforce https
     return 301 https://$server_name$request_uri;
   }

       server {
       listen 443 ssl;
       server_name example.com  www.example.com;
       root /home/forge/example.com/html/htdocs;

       ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
       ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/default-error.log error;

    error_page 404 /index.php;

     location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;

	fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name";
	fastcgi_param environment production;
       }
       location ~ /\.ht {
          deny all;
      }
   }
```

**Comment by jlambe** [comment]
I'm not sysadmin expert but it looks like an issue of file/directory permission. Try another chmod configuration for your `htdocs` folder and don't forget to make the `storage` folder as writeable.

**Comment by mehany** [comment]
Inside  ```htdocs``` i tried

For Directories:

```
sudo find .  -type d -exec chmod 755 {} \;
```
For Files:
```
sudo find . -type f -exec chmod 644 {} \;
```

and i set the htdocs directory to 

```
sudo chmod 755 htdocs/
```

**Comment by jlambe** [comment]
Frankly I won't be able to help you on this. Did you try to post your project folder structure with your nginx config on [Server Fault](http://serverfault.com/)? With your issue.

On the browser you get `access denied` but what's in your nginx error_log file? Same stuff? Perhaps you'll find a hint there.

**Comment by mehany** [comment]
Well, I really appreciate that you at least tried to help. I am getting the same error on a regular wordpress installation too so this is definitely a server config issue which i am looking into. Cheers :)

**Comment by mehany** [comment]
@jlambe this had to do with http://php.net/manual/en/ini.core.php#ini.cgi.fix-pathinfo setting it to 1 solved the problem!

**Comment by jlambe** [comment]
@mehany Glad you solved your issue :+1: Thanks for sharing the fix :wink:
