### ISSUE TITLE
multiples mu-plugins feature

### ISSUE THREAD

**Issue by rauluranga** [themosis/themosis#76]
Hi!
i want to add more mu-plugins, but i can't, themosis is taking the load.php as a single and unique mu-plugin.
for example:

```php
<?php
/*
Plugin Name: Mu-Plugins Loader
Description: Simple loader in order to run the Themosis framework core files.
Author: Julien Lambé
Version: 1.0
Author URI: http://framework.themosis.com/
*/
require_once(WPMU_PLUGIN_DIR.'/hello/hello.php');
require_once(WPMU_PLUGIN_DIR.'/themosis-framework/themosis.php');
```

my hello plugin is never loaded in wordpress

how can i achieve this??

Thanks!

**Comment by rauluranga** [comment]
i figured out, i just have to create another file at the same level of load.php that loads my plugin

for example:

hello-load.php
```php
<?php
/*
Plugin Name: PLUGIN_NAME
Description: LOREM_IPSUM
Author: AUTHOR_NAME
Version: 1.0
*/
require_once(WPMU_PLUGIN_DIR.'/hello/hello.php');
```

**Comment by jlambe** [comment]
Or simply edit the `load.php` file.
The file has been quickly written just to load the framework but there is place for improvement here in making the load.php file a multi mu-plugins loader ;)
