### ISSUE TITLE
Get Meta description and Meta keyword from Yoast SEO

### ISSUE THREAD

**Issue by ladhadha** [themosis/themosis#79]
Hi, @jlambe, since themosis have template engine an the views layouting and implementation is very similar with laravel, how to get the meta data from yoast seo, so I can add it in my header?

**Comment by jlambe** [comment]
If you're looking to catch post meta stored by Yoast, you can use the `Meta::get($postID, 'metakey')` in templates. There is currently no shortcuts for this. Or keep using core WordPress function `get_post_meta()`. Check the documentation for details: http://framework.themosis.com/docs/meta/

**Comment by ladhadha** [comment]
Thanks @jlambe :D
