### ISSUE TITLE
Child Theme Again

### ISSUE THREAD

**Issue by davidgeilfus** [themosis/themosis#80]
Hi,

I have a question closely related to [another](https://github.com/themosis/themosis/issues/39) I asked some time ago: I would like to define post types, routes and controllers that are specific to my child theme. You already explained me how to override assets and views, but I'm not sure how to load files such as `/app/config/loading.config.php`, `/app/config/templates.config.php` or `/app/controllers/MyController.php`from my child theme.

Thank you in advance! Best,

David

**Comment by jlambe** [comment]
Hi,

- You should update to the latest version 1.2.3
- Register your child theme file path like so:
```php
$paths['theme'] = __DIR__.DS.'resources'.DS;
themosis_set_paths($paths);
```
- Register your child theme config path:
```php
add_filter('themosisConfigPaths', function($paths)
{
    $paths[] = themosis_path('theme').'config'.DS;
    return $paths;
});
```
- Register the autoloading for your child theme classes:
```php
$loader = new \Composer\Autoload\ClassLoader();
$classes = \Themosis\Facades\Config::get('loading'); // Get the paths from loading.config.php file
foreach ($classes as $prefix => $path)
{
    $loader->addPsr4($prefix, $path);
}
$loader->register();
```

You can write these into your child theme `functions.php` file or if following the Themosis theme structure, put this code into a `bootstrap/start.php` file. Hope this helps.

**Comment by davidgeilfus** [comment]
Wow, I wasn't aware of this new feature! Thank you very much for the tip! ;-) Have a nice day
