### ISSUE TITLE
Wordpress Language configuration

### ISSUE THREAD

**Issue by Neidra** [themosis/themosis#81]
Hey Team Themosis,

I'm currently looking for changing the default wordpress languages from english to french.
So I had 

> define('WPLANG', 'fr_FR');

 to the htdocs/content/wp-content.php.
And add the directory "languages" in htdocs/content/ (with the french languages files).
But nothings happen.. Could you help me about that?

Thanks a lot.
Neidra

**Comment by jlambe** [comment]
With latest versions of WordPress you don't need to install this manually. Once logged in, through the `Settings -> General` options page, at the bottom, you can select a language for WordPress to install.
Select any language and click save to install new ones. Everything should work as expected.

**Comment by Neidra** [comment]
Thanks a lot!
