### ISSUE TITLE
Custom Post Type Revisions

### ISSUE THREAD

**Issue by eyeonx** [themosis/themosis#83]
Hi,

I created some custom post type using the default Themosis method, added `revisions` to the `supports` array but revision's checkbox isn't showing on the screen options tab of the post editor.

Is that default by Themosis?

**Comment by jlambe** [comment]
Can you post your code?

**Comment by eyeonx** [comment]
Sure, here the code:

`PostType::make('test', 'Test', 'Test')->set(array(
	'public'             => true,
	'publicly_queryable' => true,
	'show_ui'            => true,
	'show_in_menu'       => true,
	'query_var'          => true,
	'rewrite'            => array( 'slug' => __('banner') ),
	'capability_type'    => 'post',
	'has_archive'        => true,
	'hierarchical'       => false,
	'menu_position' 	 => 20,
	'supports'      	 => array('revisions', 'title'),

));`

**Comment by jlambe** [comment]
Which version of the framework do you use so I'll try to test your code?

**Comment by eyeonx** [comment]
I'm using the version 1.1.3

**Comment by jlambe** [comment]
Can you update to the latest 1.2.3 and let me know if the issue still persists?
Check the upgrade guide: http://framework.themosis.com/docs/upgrade-guide/

**Comment by eyeonx** [comment]
This is my loading.config.php file:

```
return array(

    /**
     * Mapping for all classes without a namespace.
     * The key is the class name and the value is the
     * absolute path to your class file.
     *
     * Watch your commas...
     */

    // Services
    'Explorer'    => themosis_path('app').'services'.DS.'File.php',
    'Inflector'    => themosis_path('app').'services'.DS.'Inflector.php',

    // Controllers
    'BaseController'        => themosis_path('app').'controllers'.DS.'BaseController.php',
    'SystemController'        => themosis_path('app').'controllers'.DS.'SystemController.php',
    'MediaUploadsController'    => themosis_path('app').'controllers'.DS.'MediaUploadsController.php',
    'SlidesController'    => themosis_path('app').'controllers'.DS.'SlidesController.php',
    'BannersController'    => themosis_path('app').'controllers'.DS.'BannersController.php',
    'FeedbacksController'    => themosis_path('app').'controllers'.DS.'FeedbacksController.php',
    'MediaController'    => themosis_path('app').'controllers'.DS.'MediaController.php',
    'UsersController'    => themosis_path('app').'controllers'.DS.'UsersController.php',
    'DashboardController'    => themosis_path('app').'controllers'.DS.'DashboardController.php',

    // Models
    'PostModel'             => themosis_path('app').'models'.DS.'PostModel.php',
);
```

How should I modify it in order to be PSR-4 compliant?

**Comment by jlambe** [comment]
Normally like this by supposing you don't use any namespace for your classes:

```php
<?php

return [
    ''  => [themosis_path('theme').'controllers', themosis_path('theme').'models',  themosis_path('theme').'services']
];
```

If using the same namespace for all classes, you can write it like so:

```php
<?php

return [
    '\\My\\Custom\\Namespace'  => [themosis_path('theme').'controllers', themosis_path('theme').'models',  themosis_path('theme').'services']
];
```

Each key is a specific namespace and its value the path to the folder where you store your classes. There is less code to write ;)

**Comment by eyeonx** [comment]
So I don't need to define all class with this syntax, only the namespace name right?

**Comment by jlambe** [comment]
Yup, the namespace only and their folder path.

**Comment by eyeonx** [comment]
I get this issue:

Warning: file_put_contents(//views/bb28957cb52350b89d7819793b194347): failed to open stream: No such file or directory in /.../htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Compilers/ScoutCompiler.php on line 58

Warning: include(//views/bb28957cb52350b89d7819793b194347): failed to open stream: No such file or directory in /.../htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/PhpEngine.php on line 36

Warning: include(): Failed opening '//views/bb28957cb52350b89d7819793b194347' for inclusion (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /.../htdocs/content/mu-plugins/themosis-framework/src/Themosis/View/Engines/PhpEngine.php on line 36

I created the storage/views folders, should I follow other steps?

**Comment by jlambe** [comment]
Yes. Normally this error should not come if you have the `storage/views` directory.

**Comment by eyeonx** [comment]
The folder is on the root directory, that's strange...

**Comment by jlambe** [comment]
Keep going until all steps are done because the new path to the storage folder is defined on new framework versions. So until you have version 1.2.3, the error will come.

**Comment by eyeonx** [comment]
I actually have version 1.2.3, I followed the steps in order to upgrade the framework to the version 1.2.0 and then the others for the version 1.2.3.

This is my folder structure:

```
project/
│
├──bootstrap/
│
├──composer.json
│
├──composer.lock
│
├──config/
│
├──htdocs/
│
├──library/
│
├──README.md
│
├──storage/
│       │
│       └──views/
│ 
├──vendor/
│
└──wp-cli.yml
```

**Comment by jlambe** [comment]
Did you update as well your theme functions.php and bootstrap/start.php files?

**Comment by eyeonx** [comment]
I updated the theme's functions.php file and the theme's bootstrap/start.php file

**Comment by eyeonx** [comment]
Ok, I had to update the bootstrap/start.php in my project root too... now it works!
I confirm that revision checkbox isn't there.

**Comment by jlambe** [comment]
Ok I'll check on this then. That's weird.

**Comment by jlambe** [comment]
Revisions does work with your code. Revisions do not show immediately in WordPress. In order to show a revision, WordPress needs one post saved, then update it, do a change in title them wait the autosave to run every 60s... and then revisions become available.

Here is a screenshot below with a sample. Check out the codex for more information: https://codex.wordpress.org/Revisions
![revisions](https://cloud.githubusercontent.com/assets/1917490/14582508/450c1060-0407-11e6-89e4-5c8e08dc89b7.png)

**Comment by eyeonx** [comment]
Hi Julien,
I made two other tests, on the first test I defined only `title` and `revisions` support, created a new post and saved it, nothing happens. On the second test I defined `title`, `revisions` and `editor` support, the wrote some text into the editor, saved and the revision feature is now working.

I think WordPress need the editor to be active in order to activate revisions on posts. I still don't understand why on your screenshot the revision feature works and there is no editor, I tried to disable all plugins and to do further tests without editor support, but I can't get it work as your example... :S

**Comment by eyeonx** [comment]
Got it! If I activate the `revisions` support on the custom post type, I need to update the title or the text in editor in order to have the feature to work. With custom fields it simply doesn't work!
It would be fine to add support for revision on custom fields too, maybe integrating this on the `Field` class, if `revisions` support is defined. What do you think?

**Comment by jlambe** [comment]
Revisions are part of a WordPress core component. Indeed I think it is limite to title and post content (editor) at the moment because it was mainly developped to offer a writing workflow, not a "data-driven" post. Perhaps check the WordPress core trac for tickets about this custom fields revisions feature and if not found, perhaps add a ticket to WordPress core ;)

**Comment by eyeonx** [comment]
You are right, I actually found that revisions on custom fields was deactivated by the WordPress team for performance purposes. Thanks anyway!

**Comment by eyeonx** [comment]
Maybe it could still be a good feature. Here how Advanced Custom Fields plugin bypassed the "problem": https://github.com/elliotcondon/acf/blob/07e1f3167b9cc052619b51466f1e7c27c71d67b4/core/controllers/revisions.php

**Comment by jlambe** [comment]
Can you open then a ticket/issue on the `themosis/framework` repository for this feature request with the links ?

**Comment by eyeonx** [comment]
Here the issue/feature request https://github.com/themosis/framework/issues/306

**Comment by jlambe** [comment]
👍
