### ISSUE TITLE
File load issue after WordPress 4.5 and Framework update...

### ISSUE THREAD

**Issue by moise** [themosis/themosis#84]
Hello @jlambe,
I had a number of errors after update WP to 4.5 and updated the Framework from 1.2.2 to .1.2.3
It seems that all classes are no longer loaded...
this is the log:
<pre>Unhandled Exception
Message:
Class 'Ajax' not found
Location:

/themosis/htdocs/content/themes/website-path/resources/admin/ajax.php on line 9</pre>

any idea on how to fix?

**Comment by jlambe** [comment]
Did you add the class aliases to your `application.config.php` file like in the upgrade guide?

**Comment by moise** [comment]
Ok sorry now all classes are loaded (in Theme) but I encountered another problem...in my project most of data area loaded in a mu-plugin by an init action.

Example:
```PHP
	/**
	 * Load Post Types
	 */
	private function registerPostType()
	{
		if ( array_key_exists( 'post_type', $this->configs ) && is_array( $this->configs['post_type'] ) ) :
			foreach ( $this->configs['post_type'] as $name => $args ) :
				$this->postType[ $name ] = \PostType::make(
					$name, $args['labels']['name'],
					$args['labels']['singular_name'] )->set( $args );
			endforeach;
		endif;

		return $this->postType;
	}
```

as you can see I'm using the PostType Class to load all my CustomPost types but after the upgrade I got this error...
<pre>Class 'PostType' not found</pre>

**Comment by jlambe** [comment]
Yes that's normal because now aliased core classes won't be available for plugins anymore. You need to use longname class: `Themosis\Facades\PostType` for example as explained in the upgrade documentation. Or simple add a `use \Themosis\Facades\PostType` in the top of your php file right after open php tags.

The use of namespaces will be a requirement for plugin development.

**Comment by moise** [comment]
Ok I fixed all with Use...last is that now the View of customized meta box is not loaed...
```PHP
		$timelineSideBox = Metabox::make(
			__( 'Informazioni aggiuntive', 'sassu' ),
			'timeline',
			[ 'priority' => 'high', 'context' => 'side' ],
			View::make( 'metabox.timeline-side' ) )->set( [
				Field::text(
					$this->prefix . '_year',
					[ 'title' => __( 'Anno', 'sassu' ) ]
				),
		] );
```

it return `View "metabox.timeline-side" not found.`
The ViewFinder is trying to load the file from: `mu-plugins/themosis-framework/src/Themosis/User/Views/metabox/timeline-side.php`

**Comment by jlambe** [comment]
If you want to use views from your mu-plugin, you need to add views locations: 
```php
// In a `plugins_loaded` action hook call
Action::add('plugins_loaded', function()
{
    add_filter('themosisViewPaths', function($paths)
    {
        $paths[] = 'path/to/your/mu-plugin/'.'views'.DS;
        return $paths;
    });
});
```
Asset use also facades: `\Themosis\Facades\Asset`.
