### ISSUE TITLE
What's the recommended way to develop a site with themosis tracked in git?

### ISSUE THREAD

**Issue by lukechilds** [themosis/themosis#87]
I've been playing around with themosis (looks really cool btw) for a new project but I'm struggling working out how I'd track the project in git.

First I tried setting up the project as a fork of `themosis/themosis` but quickly realised that won't work. I can't commit any files to `themosis-theme/resources` otherwise if a co-worker pulls down the project and runs `composer install` it will overwrite our theme changes with the fresh theme.

I thought about also forking `themosis/theme` and using that instead but then I'm gonna have to keep manually rebasing my theme from `themosis/theme` to keep up to date with update. Plus I won't have any config settings saved in git as they are all in `themosis/themosis`.

Seems like it would make more sense to symlink the `themosis-theme/resources` folder to the root of `themosis/themosis` so all dev changes can be there.

Or am I missing something really obvious? Is there a recommended way to do this?

**Comment by jlambe** [comment]
Here are the steps I use for all my Themosis projects:
1. Install a fresh copy using the composer installation (as in documentation)
2. Rename the `themosis-theme` to something else
3. Work on the theme
4. Run a git init command and commit everything except the dependencies (WordPress, Plugins, Packages)
5. Push all my project on a private git repository

If there is an update to the framework, you only need to run a `composer update`. This will install a new version of the `themosis/framework` plugin and probably a new empty theme.

In general, there is only the plugin to care about. The theme is more a folder structure and there is no update to it (sort of). If there is a manual upgrade to do, it is indicated into the upgrade guide of the documentation but it's only relevant for major updates.

**Comment by lukechilds** [comment]
Thanks, think I've got it, so you just use the existing `.gitignore`?

**Comment by jlambe** [comment]
Yes, normally I tried to provide a right gitignore setup but you can still adapt it to your project, just like composer.json ;)

**Comment by lukechilds** [comment]
Spot on, thanks!
