### ISSUE TITLE
Custom role can't access admin

### ISSUE THREAD

**Issue by lukechilds** [themosis/themosis#89]
I've created a custom user role but when I try and access the admin with that user they just get redirected to the homepage.

If I swap to a standard theme like Twenty Sixteen then the user can access the admin, it's only when Themosis is active they get redirected. I checked the permissions for subscriber and saw they have a permission `level_0` which I think is something to go with Themosis. I tried adding this capability to my role but they still can't access the admin.

I can't find anything in the docs regarding this. Do I need to whitelist a user role to give them access to the admin or something?

**Comment by lukechilds** [comment]
Think I've found the answer.

https://github.com/themosis/theme/blob/7a0b4ca2bc113fdd0a345ced6fad4f9fd52eb78e/resources/config/application.config.php#L39

**Comment by jlambe** [comment]
Yes, just add your custom role to the list of allowed roles in order to give your users access to the wp-admin.
