### ISSUE TITLE
Editing WooCommerce Product Categories with Themosis

### ISSUE THREAD

**Issue by ChrisPre** [themosis/themosis#90]
Apologies if there is a better place to have posted this.

I have a Themosis site with WooCommerce. I have everything running pretty smoothly so far...

...but in WP-Admin when I go in to Products > Categories and then click to Edit a Category I get a blank page (with just top and left menus). I have error reporting switched on in PHP and the Themosis environment files, but no errors are shown or logged.

I don't get this issue when editing a CPT taxonomy, or editing WooCommerce Attributes.

I've also tried going back to the default 'as out of the factory theme', and disabled all plugins except WooCommerce and still cannot edit the categories.

I'm using the latest version of Wordpress, WooCommerce and Themosis.

Has anybody come across this issue before, and do we know if there is a fix?

**Comment by jlambe** [comment]
Try perhaps to set off error reporting just to see if it's working back or not. Themosis is not modifying any WordPress behavior, so perhaps it's an issue in WordPress core or as it is only happening with WooCommerce custom taxonomy, perhaps there is an error into their code. Is there anything about this into their own forums?

**Comment by moise** [comment]
I had a similar issue...just try to inspect the code and search on the html something like "Error" I'm sure you will find some themosis error report...let me know...

**Comment by ChrisPre** [comment]
Thanks for the help guys; I managed to make progress with fresh eyes this morning and determined the root cause of the problem, which does indeed look like WooComm.

Thanks again.
