### ISSUE TITLE
File or entity "loading" not found.

### ISSUE THREAD

**Issue by manniR** [themosis/themosis#94]
i installed the themosis-framework as plugin and the theme in theme directory.
activating plugin worked with no errors but when i try to activate the theme it throws Fatal error:

Fatal error: Uncaught Themosis\Finder\FinderException: File or entity "loading" not found. in wordpress/wp-content/plugins/themosis-framework/src/Themosis/Finder/Finder.php:125 Stack trace: #0 wordpress/wp-content/plugins/themosis-framework/src/Themosis/Finder/Finder.php(102): Themosis\Finder\Finder->findInPaths('loading', Array) #1 wordpress/wp-content/plugins/themosis-framework/src/Themosis/Config/ConfigFactory.php(32): Themosis\Finder\Finder->find('loading') #2 [internal function]: Themosis\Config\ConfigFactory->get('loading') #3 wordpress/wp-content/plugins/themosis-framework/src/Themosis/Facades/Facade.php(66): call_user_func_array(Array, Array) #4 wordpress/wp-content/themes/theme/bootstrap/start.php(17): Themosis\Facades\Facade::__callStatic('get', Array) #5 wordpress/wp-content/themes/theme/functions.php(162): require_once('/Users/macbookp...') #6 /Users/macbookpro/Code/wp in wordpress/wp-content/plugins/themosis-framework/src/Themosis/Finder/Finder.php on line 125

**Comment by jlambe** [comment]
Did you follow the installation guide on the website or simply add it as a mu-plugin to your existing project?
It seems your theme is missing the `loading.config.php` file from the `resources/config` folder inside the theme. Try to add it manually if missing.

**Comment by manniR** [comment]
thanks jlambe for fast response;)

i followed your instructions here https://github.com/themosis/themosis/issues/72 'setup for shared hosting environments' - cloned themosis/framework to wp-content/mu-plugins - run composer install in framework directory - load it as mu-plugin - all worked fine - no errors - cloned themosis/theme into wp-content/themes/theme

loading.config.php is in resources/config - please see attached screenshot


![screen shot 2016-06-19 at 18 53 00](https://cloud.githubusercontent.com/assets/105642/16178711/4f0b6392-3650-11e6-81be-af1926c57288.png)

**Comment by jlambe** [comment]
@manniR Did you also add the `load.php` file inside your `mu-plugins` directory in order to load the framework because inside `mu-plugins` folder, WordPress do not load plugins defined in sub-directories automatically.
