### ISSUE TITLE
Wordpress Install Error: 

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/themosis#96]
Hello,
I've got the following error:
```
Unhandled Exception
Message:
Call to undefined function get_bloginfo()
Location:
/home/httpd/vhosts/swissler.ch/httpdocs/swissler.ch/htdocs/cms/wp-includes/class-http.php on line 181
```
All files are uploaded and the vhost go on the htdocs folder.

Environment is set correctly ...

Do you know the reasion for tht ?

**Comment by heikobihlmaier** [comment]
New install. Now I get

Fatal error: Call to undefined function wp_initial_constants() in /home/httpd/vhosts/swissler.ch/httpdocs/swissler.ch/htdocs/cms/wp-settings.php on line 42

**Comment by jlambe** [comment]
You can set local development to not show errors if WordPress has ones by setting the constants to false in `local.php` file in `config/environments`.

Now looking at your path, it seems there are errors in your installation, it seems weird to have both `httpdocs`, `swissler.ch` twice and `htdocs`.

Perhaps you're calling those functions too early in your code. Try to use a hook to call them later on.

**Comment by heikobihlmaier** [comment]
Thanks for your answer.

```httpdocs``` is the path from hoster. The domain points to htdocs folder. is this incorrect ? Environment is loaded correctly.

**Comment by jlambe** [comment]
if the host points to `htdocs`, it is correct then ;)

**Comment by heikobihlmaier** [comment]
I found the error: The server has errors with ftp active mode what's the default of my deployment software. so I change this to passive mode and all seems okay. Sorry for stealing your time!

**Comment by jlambe** [comment]
Glad it is solved ;)
