### ISSUE TITLE
Update Version on Packagist

### ISSUE THREAD

**Issue by alpipego** [themosis/themosis#99]
The latest version on packagist.org is `1.2.3` that still has `http://wpackagist.org` as the composer url. I saw that this is fixed in your master branch but not on packagist.org yet. Could you please update the version on packgist.org to reflect this change.

**Comment by jlambe** [comment]
Will try to update this end of the week, or if you have time, make a PR against the 1.2.3 tagged version, not master.

**Comment by alpipego** [comment]
But you already have the change in your master branch... I can still create a PR against your dev branch, though. Which is the same revision as the tag.

**Comment by jlambe** [comment]
Yes but I can't make a release against the current master branch has it holds the major update version and has too much break changes for a minor release.
